### ISSUE TITLE
Problems to install the package

### ISSUE THREAD

**Issue by paduel** [RomelTorres/alpha_vantage#1]
Hola Romel.

I tried to install to package following your instructions, but wasn't possible.
I use Python 2.7, and I get this message:

```
$ sudo python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/alpha_vantage-0.0.1.egg-info
Writing /usr/local/lib/python2.7/dist-packages/alpha_vantage-0.0.1.egg-info

```
When run nosetest this other:

`ERROR: Failure: ImportError (No module named alpha_vantage.api_calls.alphavantage)`

I also install with pip correctly nose and simplejson.
What's the problem? 
Thanks

**Comment by RomelTorres** [comment]
Hola Paduel,

I have fixed the setup.py, would you be so kind as to try the following:

* Checkout the develop branch
* pip install -e alpha_vantage

Try using the package now, if it still not working reopen the issue, I will try publishing the package on pipy today, so that it is easier to use.

Thank you for the message and understanding.
Romel

**Comment by RomelTorres** [comment]
Hi again Paduel, 

I have published it in pipy and you should be able to do:
`pip install alpha_vantage`

Let me know if that resolves it,

Romel

**Comment by RomelTorres** [comment]
Closing this see #2. I hope it is working out for you, 

Best Regards,
Romel

**Comment by paduel** [comment]
Hola Romel.

Perfect! Now I could install the package from pipy.

Thanks. I will test it.

**Comment by rshimizubr** [comment]
Hi Romel,

I have the same issue. ImportError: No module named 'alpha_vantage.timeseries'

Have created env python 3.5 and re-installed the packages. Got into the python env, invoked the first statement "from alpha_vantage.timeseries import TimeSeries" and the above error message stopped execution.

Any other observation I should have taken notice?

Thanks
Roberto
