### ISSUE TITLE
Don't find requests_mock error

### ISSUE THREAD

**Issue by dwskaddouch** [RomelTorres/alpha_vantage#103]
Hello 
I dont manage to install alpha_vantage:
- requests_mock is missing and probably requests too.
Can someone help me?
Bye

 runfile('C:/Users/UD/python/alpha__vantage/alpha_vantage-develop/setup.py', wdir='C:/Users/UD/python/alpha__vantage/alpha_vantage-develop')
Traceback (most recent call last):

  File "<ipython-input-5-ea07bb41337f>", line 1, in <module>
    runfile('C:/Users/UD/python/alpha__vantage/alpha_vantage-develop/setup.py', wdir='C:/Users/UD/python/alpha__vantage/alpha_vantage-develop')

  File "C:\Users\UD\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\UD\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/UD/python/alpha__vantage/alpha_vantage-develop/setup.py", line 4, in <module>
    import nose,requests_mock,pandas

ModuleNotFoundError: No module named 'requests_mock'

**Comment by RomelTorres** [comment]
Can you install the module on your own? I don't have any windows computer to test that. :(

**Comment by dwskaddouch** [comment]
I tried with pip and it seemed to work. I check if it works correctly

**Comment by dwskaddouch** [comment]
It works. Great.
I just have another issue. I would like to take just the last value instead of taking all the latest 100 values in the compact way. Is there a simple way to do it ? - I can create a decorator but that seems more complicated.
Merry Christmas
