### ISSUE TITLE
Loading the last quotes

### ISSUE THREAD

**Issue by dwskaddouch** [RomelTorres/alpha_vantage#104]
Hello
I would like to load only the last quotes
I can every time download all but I will use a lot of memory.
Is it possible to download the last quotes simply - and not 100 with the compact option?
Bye

**Comment by buddha314** [comment]
I think this is related to date slicing.  Does this library provide a way to set the start and end date of the pull?  Thanks for providing it!

**Comment by SterlingButters** [comment]
@buddha314 I don't think it does though I, too, would enjoy this feature since the time to acquire the data is proportional to the size of the data set you are trying to retrieve. At least that would make sense I think

**Comment by RomelTorres** [comment]
No, the library does not support giving start and end dates, you have to load it all and then use pandas slicing. If it is not supported by the alpha vantage endpoint. I cannot implement it unless it is supported by Alpha Vantage itself.

**Comment by buddha314** [comment]
Thanks for the update.  I appreciate your time.
