### ISSUE TITLE
Python 3.4 issue collecting data using Alphavantage API.

### ISSUE THREAD

**Issue by me2learn** [RomelTorres/alpha_vantage#106]
Hi Romel

I'm a newbie to Python and learning on the go.

I tried collecting stock data using Alphavantage API example code, available here, but I didn't succeed.

Every time I get a different error. Is there a way, we can get in touch and discuss this issue.

I have tried all the solutions, that appeared on your GitHub page so far.

Kindly let me know

Thanks In Advance

Regards
Sridhar

**Comment by RomelTorres** [comment]
Hi just post the errors you get here and we'll see if we can help ;)

**Comment by RomelTorres** [comment]
well it is definitely not installed. Are you using a virtual environment? You said you had python 3.4? Can you check in your terminal if you can import the package?

**Comment by me2learn** [comment]
Hi Romel

Thank you for the revert

Yes, I'm using virtual environment

And I have installed alpha-vantage==2.1.0

I just checked, after seeing your response, to confirm the installation,
using "pipfreeze"

If you need I can send you a screenshot of the same.

Python version installed is 3.6.7 and not 3.4 as I have mentioned in my
previous email.

Sorry about that

Please let me know, if you need further information

Thanks In Advance for your time and assistance

Regards
Sridhar

**Comment by me2learn** [comment]
Hi Romel, did you get a chance to look into this issue. Please let me know. Thanks

**Comment by RomelTorres** [comment]
Hi did you do pip install alpha-vantage or pip install alpha_vantage?

**Comment by RomelTorres** [comment]
pip install alpha_vantage

**Comment by me2learn** [comment]
Hi Romel
I installed using the above command, but still getting the same error
Enclosing screenshots for your referencefile:///home/myubu/Pictures/Screenshot%20from%202019-01-file:///home/myubu/Pictures/Screenshot%20from%202019-01-11%2020-06-28.png
11%2020-06-47.png

**Comment by RomelTorres** [comment]
I do not know, what do you propose? I am usually quite busy due to work and right now I am out of ideas of what it could be... Could you try building from the github repository and not installing from pipy?
