### ISSUE TITLE
issue with repeatedly calling

### ISSUE THREAD

**Issue by xrocks** [RomelTorres/alpha_vantage#107]
Hi, the code works marvelously. However, there seems to be an issue with repeatedly running the get_macd or get_rsi. For example, the following simple block of code returns errors. 

```python
import pandas as pd
from alpha_vantage.techindicators import TechIndicators


ti = TechIndicators(key='my_av_api_key', output_format='pandas')
macd_d, macd_meta_d = ti.get_macd(symbol='MSFT', interval='weekly', fastperiod=12, slowperiod=26, signalperiod=9)
macd_w, macd_meta_w = ti.get_macd(symbol='MSFT', interval='weekly', fastperiod=12, slowperiod=26, signalperiod=9)
rsi_d, rsi_meta_d = ti.get_rsi(symbol='MSFT', interval='daily')
rsi_w, rsi_meta_w = ti.get_rsi(symbol='MSFT', interval='weekly')

macd_d, macd_meta_d = ti.get_macd(symbol='APPL', interval='weekly', fastperiod=12, slowperiod=26, signalperiod=9)
macd_w, macd_meta_w = ti.get_macd(symbol='APPL', interval='weekly', fastperiod=12, slowperiod=26, signalperiod=9)
rsi_d, rsi_meta_d = ti.get_rsi(symbol='APPL', interval='daily')
rsi_w, rsi_meta_w = ti.get_rsi(symbol='APPL', interval='weekly')
```
The screenshot shows the error:
![screen shot 2019-01-09 at 3 45 01 am](https://user-images.githubusercontent.com/6658319/50887359-f9f8ee00-13c0-11e9-89c4-bd61dc4191e3.png)

**Comment by RomelTorres** [comment]
Hmm interesting, is it random? or happens always with this specific call?

**Comment by xrocks** [comment]
Thanks for the response.  Yea, it always for me. I tried `output_format='json'`, and try `symbol =MU` and other tickers. Similar error messages pointing to the `alphavantage.py` code. 

If you copy over that block of code, do you get error when running it?

**Comment by RomelTorres** [comment]
I decided I am taking out the retry default of 5 which tends to make the error messages not understandable.
When I ran that particular line (but set the retries parameter to 0) I got the following error:
ValueError: This API call returns NO data. Please check documentation

Could you check if you are using the call properly?

**Comment by RomelTorres** [comment]
If you want to check if it is a python issue. Make the call directly on the browser *as done in the examples) and substitute the values you need for the call. If you get a JSON output on your browser, you should be able to get the same in python.

**Comment by xrocks** [comment]
Mystery resolved. If I tried calling directly on the browse multiple times, it will just say:

"Note": "Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency."

Ahg, I wish there is a way to access multiple company data at once.
