### ISSUE TITLE
Forex and pandas

### ISSUE THREAD

**Issue by NTavou** [RomelTorres/alpha_vantage#109]
Hi Romel, 

Congrats for the module, it is really helpful and user friendly. 
I would like to point out that the info in the README about 

> Foreign Exchange (FX) 

needs to be fixed a little bit because it is written that 

> The foreign exchange is just metadata, thus only available as json format (using the **'csv'** or **'pandas'** format **will raise an Error**)

but this is true only for the `get_currency_exchange_rate()` function.  

Calling the other four functions:
 `get_currency_exchange_intraday()`  
`get_currency_exchange_daily()` 
`get_currency_exchange_weekly()`
 `get_currency_exchange_monthly()`

with `cc = ForeignExchange(key='YOUR_API_KEY', output_format='pandas')` 

works fine to get back pandas dataframes. So I think that it would be better to clarify this in the README section about FX. 

Thanks

**Comment by RomelTorres** [comment]
You can fix it and send me the PR ;) I think is better that way :)

**Comment by NTavou** [comment]
Haha ok

**Comment by RomelTorres** [comment]
Yeah I actually don't use the library at the moment and prefer if people who actually use it make improvements :)

**Comment by NTavou** [comment]
Ok I see, fair enough. I will do it sometime in the near future along with other things that I may find as I keep using the library. Cheers
