### ISSUE TITLE
How do you stream data?

### ISSUE THREAD

**Issue by jiminssy** [RomelTorres/alpha_vantage#112]
It seems like Alpha Vantage is all periodically querying (polling) data. Is there a way to stream data with an open connection?

**Comment by dangell7** [comment]
Did you try opening a socket?

**Comment by jiminssy** [comment]
Which address do I open the socket to? And what protocol does it use for streaming?
All I found was this Alpha Vantage API documentation that has HTTP based API which is not a real-time "streaming" data ingest.

https://www.alphavantage.co/documentation/

**Comment by dangell7** [comment]
You need to read the python docs about streaming and I would google around and find a general guidlines about opening sockets. You need to limit your own rate as well. 

https://docs.python.org/3/howto/sockets.html
