### ISSUE TITLE
Wrong historical data (outputsize=full)

### ISSUE THREAD

**Issue by elbowz** [RomelTorres/alpha_vantage#115]
Hi,

 I'm the only one that get wrong data from a simple query like?:

`https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=AAPL&outputsize=full&apikey=api-key`

Obviously AAPL is not the only one...

This don't seem the real AAPL chart:
![figure_1](https://user-images.githubusercontent.com/1451484/52916713-3d5d4b00-32e3-11e9-986b-5beee73516b1.png)

...and AAPL never touch 600:
```
       "2014-05-06": {
            "1. open": "601.8000",
            "2. high": "604.4099",
            "3. low": "594.4100",
            "4. close": "594.4100",
            "5. volume": "13377300"
        },
        "2014-05-05": {
            "1. open": "590.1400",
            "2. high": "601.0000",
            "3. low": "590.0000",
            "4. close": "600.9600",
            "5. volume": "10252400"
        },
        "2014-05-02": {
            "1. open": "592.3400",
            "2. high": "594.2000",
            "3. low": "589.7100",
            "4. close": "592.5800",
            "5. volume": "6839800"
        }
```

somthing that I miss?!?

Thanks

**Comment by coryleuck** [comment]
Looks like the OP is not familiar with the concept of **adjusted** closes and was instead using the raw closes prices for AAPL which certainly touched 600 in the dotcom bubbles (circa 2000). 

[https://www.alphavantage.co/documentation/#dailyadj](Documentation)

I wonder whether it's fair for Alpha Vantage when some of its users didn't actually do what they are doing and wrongfully claim that Alpha Vantage data is "wrong"...

**Comment by elbowz** [comment]
Sorry, my bad...

Anyway I have write: 
> something that I miss?!?

so, again, sorry for have wasted your time...thanks for your speedy support

**Comment by elbowz** [comment]
![figure_1](https://user-images.githubusercontent.com/1451484/52918095-67b70480-32f3-11e9-976d-f1d6d1139361.png)

Now it's perfect, thanks for your hard work :+1:

**Comment by BeMoreDifferent** [comment]
Hi @elbowz,
I'm stuck in the same situation. Would it be possible to share the solution?
Thanks,
Daniel

**Comment by elbowz** [comment]
> Hi @elbowz,
> I'm stuck in the same situation. Would it be possible to share the solution?

If I well remember, try with **TIME_SERIES_DAILY_ADJUSTED** (https://www.alphavantage.co/documentation/#dailyadj) as linked by @coryleuck

**Comment by alexmulo** [comment]
I am having the same issue with this symbol BAS.DEX. Both historical requests does not give the same results like in yahoo finance or google. This is the request I use:
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=BAS.DEX&apikey=MYKEY&datatype=csv&outputsize=full

**Comment by pramehta** [comment]
I have just started using the TIME_SERIES_DAILY function to pull data.

question is on Ebay stock 
timeframe.= Daily 
Date - 07/17/2015

I was comparing this data with google finance

                           Date, Open, High,Low,Close,Volume
AlphaVantage   -  07/17/2015 00:00:00,66.04,66.73,64.85,66.29,26169406
Google Finance - 07/17/2015 00:00:00,11.68,11.8,11.47,11.72,26169406

As you can see, the volume is the same but the prices are way different ?  Is it something to do with split ? 

Can you tell me the reason for this ? I also checked tradingview and it matches google finance. 
There are many such instances for Ebay. 

then is used the adjusted end point and below is what I see:

   "2015-07-20": {
            "1. open": "26.89",
            "2. high": "29.35",
            "3. low": "26.5899",
            "4. close": "28.57",
            "5. adjusted close": "26.3178852989334",
            "6. volume": "37485739",
            "7. dividend amount": "38.3900",
            "8. split coefficient": "1.0"
        },
        "2015-07-17": {
            "1. open": "66.04",
            "2. high": "66.73",
            "3. low": "64.85",
            "4. close": "66.29",
            "5. adjusted close": "26.0545492303808",
            "6. volume": "26169406",
            "7. dividend amount": "0.0000",
            "8. split coefficient": "1.0"
        },
        "2015-07-16": {
            "1. open": "65.3",
            "2. high": "66.71",
            "3. low": "65.0",
            "4. close": "65.59",
            "5. adjusted close": "25.7794219945795",
            "6. volume": "31025297",
            "7. dividend amount": "0.0000",
            "8. split coefficient": "1.0"
        },

Ebay stock latest split was on 2015-07-20 with 2.376:1
If I take the price from a day before split and adjust the open price based on the split value it should be 66.04/2.376 = 27.79  
for the 20th but it is showing as 26.89.   
What am I missing here.  ?
I am building a model based on historical data and so want to make sure I get this correct.

**Comment by dhirs** [comment]
We are using premium API key for Alphavantage and pretty much most of the intraday data is incorrect. It does not tie up with what we are seeing either on TradingView or on Yahoo Finance. And no, we are talking INTRADAY, so this has nothing to do with adjusted closes as one of the Einsteins above seemed to have suggested.

**Comment by carlosml0287** [comment]
@dhirs 
I have the same problem, I use premium API key for Alphavantage. The INTRADAY data is very different from Yfinance or Tradingview, and it's not the adjusted value. How did you resolve this issue? Do you use another data provider?

Some candles have a low and high value very far from the closing price.

![Image](https://github.com/user-attachments/assets/589f379b-1fd2-4044-b40e-6724030f0eb1)
