### ISSUE TITLE
Please add VWAP in tech indicator

### ISSUE THREAD

**Issue by TonyPlayer** [RomelTorres/alpha_vantage#116]
Recently, Alpha Vantage has added VWAP in their library. 
I has tried using ti.get_vwap. and getting error like this:
Code:
from alpha_vantage.techindicators import TechIndicators
ti = TechIndicators(key=alpha_vantage_key, output_format='pandas')
vwap, metadata_vwap = ti.get_vwap(symbol='AMZN', interval='1min')

error:
AttributeError: 'TechIndicators' object has no attribute 'get_vwap'

**Comment by RomelTorres** [comment]
Hi do you think you could make a PR for it? The implementation should be rather straightforward:)

**Comment by TonyPlayer** [comment]
Hi, thanks for replay. I ended up implementing in my code. I still use rest of Tech Indicator from this repo.  Thanks, will close this.  Best, Tony

**Comment by RomelTorres** [comment]
Could you provide a Pull Request to my repo so that other people can benefit from your implementation? :)
