### ISSUE TITLE
Can't search CSE stocks

### ISSUE THREAD

**Issue by weedstreet420** [RomelTorres/alpha_vantage#117]
Search endpoint doesn't work with CSE stocks, but the same stocks can be found in the TIME_SERIES endpoints

Searching for CXXI.CN returns no result
https://www.alphavantage.co/query?function=SYMBOL_SEARCH&apikey=XXXXXX&keywords=cxxi.CN

But I can still get TIME_SERIES_DAILY for this stock (CXXI.CN)
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=CXXI.CN&apikey=XXXXXX&outputsize=full

**Comment by RomelTorres** [comment]
I think you should talk to alpha vantage about it I don't think is related to the code here :)

**Comment by weedstreet420** [comment]
I tried to contact Alpha Vantage but they are not answering e-mails.

Yes, this is related to the API. One of the endpoint (SYMBOL_SEARCH) is not returning any result with CSE stocks while the other endpoint is working (TIME_SERIES)...
