### ISSUE TITLE
Stock not adjusted after shares consolidation

### ISSUE THREAD

**Issue by weedstreet420** [RomelTorres/alpha_vantage#118]
Some stocks are not adjusted after share consolidation.

Example with VRT.CN stock: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=vrt.cn&apikey=XXXXXX&outputsize=full

The data from the above URL will return non-adjusted prices, and there are also 2 trading days returning stock price of 0.00$

http://prntscr.com/mtui1u

> Veritas Pharma Inc. (CSE: VRT; OTC: VRTHF; and Frankfurt: 2VP) (“Veritas” or the “Company”) announces that it is proceeding with a consolidation of its issued and outstanding common shares at a ratio of one (1) post-consolidation common share for every ten (10) pre-consolidation common shares (the “Consolidation”)

https://globenewswire.com/news-release/2019/02/05/1710258/0/en/Veritas-Pharma-to-Proceed-with-Share-Consolidation.html

**Comment by RomelTorres** [comment]
This issue is not related to the code, please contact alpha vantage directly:)
