### ISSUE TITLE
Invalid Date in Firefox

### ISSUE THREAD

**Issue by cykl** [RomelTorres/alpha_vantage#12]
`date` is always set to `Invalid Date` in Firefox. 

Issue is that `newSample['date'] = new Date(key + ' EDT');` isn't proper ES[56]. Date's ctor expects a RFC 2822 or ISO8601 `dateString` but `YYYY-MM-DD EDT` isn't. Chrome seems more lenient than FF. 

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by cykl** [comment]
Oops, I just noticed that I screwed up. This issue targets another project. Sorry for the inconvenience.

**Comment by RomelTorres** [comment]
No problem ;)
