### ISSUE TITLE
zero value from the data returned by TIME_SERIES_MONTHLY API

### ISSUE THREAD

**Issue by ZHIBINXI** [RomelTorres/alpha_vantage#120]

**Comment by ZHIBINXI** [comment]
we are facing one critical issue about TIME_SERIES_MONTHLY from the data API.

there's strange "0.0000" value from "low" slot. is this a error?

![image](https://user-images.githubusercontent.com/1501976/54021595-78a8b680-41cb-11e9-8550-1e1752f27d7f.png)


As above: after several data verification, we have a large number of data samples which have “0” in their “low” price slot. This is critically wrong and causing fatal error in our Apps, as following:

PS: we are pulling the data from the API address:
![image](https://user-images.githubusercontent.com/1501976/54021588-72b2d580-41cb-11e9-9377-323061110a40.png)

**Comment by RomelTorres** [comment]
Hi this is something I can not hielo you with. Sinceramente I have nothing to do with the api endpoint. I hope the people ar Alpha Vantage can help you out.

**Comment by ZHIBINXI** [comment]
Sure. I'm closing this ticket. Thanks.
