### ISSUE TITLE
KeyError when try to access too many stocks

### ISSUE THREAD

**Issue by CalumTowler** [RomelTorres/alpha_vantage#122]
Hey man, have written a loop that calls the intra-day data for a list of stocks. Here is the relevant portion:
-------------------------------------------------------------------------------------------------------------
class Stock():
    
    def __init__(self):
        self.StockTickers = ['MSFT','GOOGL','NKE','DJI']#,'NFLX', 'A', 'AA', 'AAC', 'AAN', 'AAP', 'AAT', 'AB', 'ABB', 'ABBV', 'ABC', 'ABEV']

    def collect_intraday_data(self):
        MyKey ='28M2VQTADUQ0HSCP'
        ts = TimeSeries(key=MyKey)
        Procstockdata = []
        for i in self.StockTickers:
            stockdata, meta_stockdata = ts.get_intraday(i,'1min','full')
            Indexes = []
            Procstockdata.append(i)
            for i in stockdata.keys():
                Indexes.append(i)
            for item in Indexes:
                get_interval = stockdata.get(item)
                interval_data = [item, float(get_interval.get('1. open')), float(get_interval.get('4. close')), float(get_interval.get('3. low')), float(get_interval.get('2. high')), int(get_interval.get('5. volume'))]
                Procstockdata.append([interval_data[0], interval_data[1], interval_data[2], interval_data[3], interval_data[4], interval_data[5]]) 
        return Procstockdata

Stocks = Stock()
StockData = Stocks.collect_intraday_data()
print(StockData)
----------------------------------------------------------------------------------------------------------
This runs perfectly fine and I have managed to add functionality to plot and write each of these data lists. However, when I make the list of stocks too large (more than 4 usually, depending what Im asking it to do), I get this error message:
----------------------------------------------------------------------------------------------------------
File "C:/Users/Calum/Trading Program/TradingProgram/WebExtract/TradingProgram.py", line 95, in <module>
    StockData = Stocks.collect_intraday_data()

  File "C:/Users/Calum/Trading Program/TradingProgram/WebExtract/TradingProgram.py", line 33, in collect_intraday_data
    stockdata, meta_stockdata = ts.get_intraday(i,'1min','full')

  File "C:\Users\Calum\Anaconda3\envs\TradingProgram\lib\site-packages\alpha_vantage\alphavantage.py", line 178, in _format_wrapper
    data = call_response[data_key]

KeyError: 'Time Series (1min)'*
----------------------------------------------------------------------------------------------------------
*The interval is dependent on what I called.
Do you know what this could be due to? https://github.com/CalumTowler/TradingProgram is the repository in case you wanted to look at the entire file.
Thanks a lot, and thanks for writing this library. Apart from this issue it's been awesome!

**Comment by RomelTorres** [comment]
Hi could it be that you are calling the fubctions too fast? There is a Lolita on nombre of calls per minute from the alpha vantage backend

**Comment by coryleuck** [comment]
Did you read through their FAQ, especially the following section?

https://www.alphavantage.co/support/#support

Are there usage/frequency limits for the API service?

We are proud to provide free API service for our global community of users and recommend that you make API requests sparingly (up to 5 API requests per minute and 500 requests per day) to achieve the best server-side performance. If you would like to target a larger API call volume, please visit premium membership.

https://www.alphavantage.co/premium/

**Comment by CalumTowler** [comment]
Thanks guys this is definitely the problem.
