### ISSUE TITLE
Premium Key

### ISSUE THREAD

**Issue by joshdasilva** [RomelTorres/alpha_vantage#124]
I'm using a premium key but I still get the error the following error, perhaps you should make a change to allow a premium key to be used with this wrapper.

Note': 'Thank you for using Alpha Vantage! Our standard API call frequency '
         'is 5 calls per minute and 500 calls per day. Please visit '
         'https://www.alphavantage.co/premium/ if you would like to target a '
         'higher API call frequency.'}

**Comment by RomelTorres** [comment]
I don't have a premium key to test this, but you are welcome to send a pull request for it. I am always happy to review.

BR
Romel

**Comment by azydevelopment** [comment]
This looks like an error with the API itself. The server serves that message when it thinks your key isn't a premium key and throttles you.

That being said, I have a feature request related to this note: Please allow error handling for when a limit is reached. This particular error looks like should be caught here:

https://github.com/RomelTorres/alpha_vantage/blob/4e0b5057e520e3e3de69cf947301765817290121/alpha_vantage/alphavantage.py#L164

Right now it's assumed that the data field with a key defined by data_key exists. This currently throws an uncaught KeyError exception (which it should).

**Comment by joshdasilva** [comment]
Iazydevelopment the api key has no issues ive had it checked by alphavantage. Furthermore  I've tried twopirllc's alphavantageapi python 3.7 wrapper and ive had success making frequent calls using a premium key. They've implemented a method to allow to set premium to true or false. I'd love to see something like that in this wrapper to make it usable for alpha vantage premium users.
