### ISSUE TITLE
Error handling doesn't exist for API call limits

### ISSUE THREAD

**Issue by azydevelopment** [RomelTorres/alpha_vantage#125]
Please allow error handling for when an Alpha Vantage API usage limit is reached. Ie. When you get messages like this:

`{
    "Note": "Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency."
}`

This particular error looks like should be caught here:

https://github.com/RomelTorres/alpha_vantage/blob/4e0b5057e520e3e3de69cf947301765817290121/alpha_vantage/alphavantage.py#L164

Right now it's assumed that the data field with a key defined by data_key exists. This currently throws an uncaught KeyError exception (which it should).

And here's a partial call stack showing the exception being thrown:

`File "C:\.......\alphavantage.py", line 178, in _format_wrapper
data = call_response[data_key]
KeyError: 'Time Series (Daily)'`

**Comment by AlwinLijdsman** [comment]
Running into the same problem. Proper error handling would help a lot.

**Comment by Leatherface75** [comment]
Maybe this is the problem with it only finds 1-2 of 3 sensors randomly when restarting.

**Comment by RomelTorres** [comment]
Any suggestions for improving this?

**Comment by PatrickAlphaVantage** [comment]
This is a great issue to raise... I was running into the same issue. Looks like it has been fixed and will be in the next release. Wohoo!
