### ISSUE TITLE
Premium key too

### ISSUE THREAD

**Issue by ssmlee04** [RomelTorres/alpha_vantage#126]
I have purchased a premium subscription key and I still see the following error message.

"Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/if you would like to target a higher API call frequency."

Could you help me check what's happening? Thank you.

**Comment by joshdasilva** [comment]
I suggest you use the wrapper by twopirllc available at  https://github.com/twopirllc/AlphaVantageAPI for the time being until the feature is implemented by RomelTorres. It allows switching between free and premium option.

**Comment by ssmlee04** [comment]
I contacted the support and turns out they showed a new set of key somewhere on the page when I checked out. Guess the api itself is working alright then. Thanks.

**Comment by jackson-sandland** [comment]
Anyone know how to find that premium key? They should really send an email bare minimum with that key. I checked out via Paypal and I have no way of knowing what the key is...
