### ISSUE TITLE
Momentum

### ISSUE THREAD

**Issue by kairosart** [RomelTorres/alpha_vantage#127]
Hi,
I'm developing a trading system and I'm trying your API.

I got some trouble to understand MOM (Momentum indicator) parameter. Your documentation says:

> Number of data points used to calculate each MOM value. Positive integers are accepted (e.g., time_period=60, time_period=200)

The question is:

**time_period is the same as the window parameter used to calculate Momentum?**

I was using an own function to calculate Momentum and the results are totally different. 

 Thanks.

**Comment by PatrickAlphaVantage** [comment]
Not sure what the window parameter on your function is. Could you please ask this question on a forum like StackOverflow? Issue tracking should be for issues with the repo. 

> https://www.fmlabs.com/reference/default.htm?url=Momentum.htm

The time_period is the number of times you use the interval. Let's say you have interval=1min, and time_period=60, this would get you the momentum for 60 minutes (aka one hour).
