### ISSUE TITLE
API Calls not working

### ISSUE THREAD

**Issue by rajvirkaushal** [RomelTorres/alpha_vantage#128]
I am not getting the expected response from Alpha Vantage APIs. The following are the details, could someone help?

Infrastructure - GCP Windows server
GCP Region: asia-south1-c
Error - { "Note": "Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency." }
Key - Free trial keys

Pls note our url /python code works well to fetch the details however through GCP infrastructure is not working. 

Code: 

 def __init__(self, api_key, part_url, query, function, exchange, symbol, interval, format):
        self.api_key = api_key
        self.part_url = part_url
        self.query = query
        self.function = function
        self.exchange = exchange
        self.symbol = symbol
        self.interval = interval
        self.format = format

    def get_data(self):
        #data_url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=NSE:TATAMOTORS&interval=1min&apikey=STPO0LS61SH9DZ0J&datatype=csv'
        data_url = self.part_url + self.query + self.function + '&symbol' + '=' + self.exchange + ':' + self.symbol + '&' + 'interval=' + self.interval + '&apikey=' + self.api_key + '&datatype=' + self.format
        print (data_url)

try:
            data=requests.get(data_url)
        except Exception as e:
            print ("Failed with error {0}".format(e))
            raise SystemExit

**Comment by PatrickAlphaVantage** [comment]
Could you please ask this in someplace like StackOverflow? It doesn't seem like an issue with the wrapper. It just looks like you're hitting the API call limit. Generally I'd look to offer advice anyways but I'm not familiar with GCP. 

@rajvirkaushal 
Have you asked this question elsewhere?
