### ISSUE TITLE
Canadian Equity Dividend Data not found

### ISSUE THREAD

**Issue by liamland** [RomelTorres/alpha_vantage#130]
Not sure whether this is an Alpha Vantage issue or a wrapper issue. But I haven't got a response from Alpha Vantage so I will try here. All four of the following tickers have a long history of quarterly dividends. The output is a pandas df column sum of the output from the monthly_adjusted time series. I get the same result from the daily and weekly adjusted time series.

TSX:BCE 1. open               5.076170e+03
2. high               5.212550e+03
3. low                4.937380e+03
4. close              5.095740e+03
5. adjusted close     4.254568e+03
6. volume             3.056707e+09
7. dividend amount    0.000000e+00
dtype: float64
TSX:BMO 1. open               7.827790e+03
2. high               8.064790e+03
3. low                7.591240e+03
4. close              7.867050e+03
5. adjusted close     6.742426e+03
6. volume             3.019698e+09
7. dividend amount    0.000000e+00
dtype: float64
TSX:RY 1. open               1.813900e+03
2. high               1.860310e+03
3. low                1.762530e+03
4. close              1.813360e+03
5. adjusted close     1.764814e+03
6. volume             9.226584e+08
7. dividend amount    0.000000e+00
dtype: float64
TSX:TD 1. open               5.496000e+03
2. high               5.643340e+03
3. low                5.313575e+03
4. close              5.528500e+03
5. adjusted close     4.803230e+03
6. volume             6.874716e+09
7. dividend amount    0.000000e+00
dtype: float64

**Comment by PatrickAlphaVantage** [comment]
New to the team, good question. Let's explore the question a little more...

I ran this code in a python notebook to see what it would return

```
from alpha_vantage.timeseries import TimeSeries
key = <key_here>
ts = TimeSeries(key, output_format='pandas')
data, meta = ts.get_monthly_adjusted(symbol='TSX:BCE')
data.loc[data['7. dividend amount'] != 0]
```

Looks like I get a blank dataframe here. So the next step would be to check the URL:

> https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY_ADJUSTED&symbol=TSE:BCE&apikey=<key_here>

Looks like the data is actually coming up as 0
I'll raise a ticket with alpha vantage support, thanks!
