### ISSUE TITLE
Plotting Bollinger bands

### ISSUE THREAD

**Issue by seshuthota** [RomelTorres/alpha_vantage#135]
Hi ,
I was going through your package, It was great by the way.
There was an issue while plotting bollinger bands it was plotting from right to left but it was supposed to be from left to right.
![AlphaVantageBBError](https://user-images.githubusercontent.com/13276143/62543807-366bca00-b87c-11e9-8949-10ca447d9cd1.JPG)

Thanks,
Seshu Thota

**Comment by PatrickAlphaVantage** [comment]
Looks like it's coming from the way the dataframe is being generated. 

You can just reverse the dataframe. Here is some sample code to get the same graph reversed (using GOOGL ticker as a sample):

```
from alpha_vantage.techindicators import TechIndicators
import matplotlib.pyplot as plt

# Your key here
key = 'demo'
ti = TechIndicators(key, output_format = 'pandas')
data, meta_data = ti.get_bbands(symbol='GOOGL')

from matplotlib.pyplot import figure
figure(num=None, figsize=(15, 6), dpi=80, facecolor='w', edgecolor='k')
data.reindex(index=aapl_ti.index[::-1])
data['Real Middle Band'].plot()
data['Real Lower Band'].plot()
data['Real Upper Band'].plot()
plt.tight_layout()
plt.grid()
plt.show()
```

Sort of a workaround, but this would be a bigger release, as fixing this would make the next one not backward compatible. 
Hope that helps

**Comment by seshuthota** [comment]
Thanks for the fix.

**Comment by PatrickAlphaVantage** [comment]
Going to close this as #186 has mentioned it and has suggested a better solution.
