### ISSUE TITLE
API call `ts.get_daily()` no longer working

### ISSUE THREAD

**Issue by SteffenNa** [RomelTorres/alpha_vantage#136]
Hihi

Just run the following 

```
from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries(key='AV_api_key', output_format='pandas')
ts.get_daily(symbol='^GSPC')
```
getting the following traceback:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-aa157764e46e> in <module>
----> 1 ts.get_daily(symbol='^GSPC')

~/miniconda3/lib/python3.7/site-packages/alpha_vantage/alphavantage.py in _format_wrapper(self, *args, **kwargs)
    176             if 'json' in self.output_format.lower() or 'pandas' \
    177                     in self.output_format.lower():
--> 178                 data = call_response[data_key]
    179                 if meta_data_key is not None:
    180                     meta_data = call_response[meta_data_key]

KeyError: 'Time Series (Daily)'

Looks like alphavantage changed something?

Cheers,

Steffen

**Comment by bprece** [comment]
I am with the same problem:

Fatal error: Uncaught AlphaVantage\Exception\RuntimeException: Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY

Works, but all Brazilian marketing returns empty:
https://www.alphavantage.co/query?function=SMA&symbol=OIBR3.SA&interval=weekly&time_period=10&series_type=open&apikey=

Don't work, with daily interval:
https://www.alphavantage.co/query?function=SMA&symbol=OIBR3.SA&interval=daily&time_period=10&series_type=open&apikey=

**Comment by SteffenNa** [comment]
Closing the issue. seems to have been a problem on server side. works now

**Comment by dsvf** [comment]
I have the same error here, with SUAS.L returning KeyError: 'Time Series (Daily)'

**Comment by ValentinMoullet** [comment]
I have the same error, at least in the browser, for a lot of different symbols:
CSSPX.SW, LISN.SW, CLN.SW, BION.SW, GAM.SW, IMEU.AS, IJPA.AS, IUAG.SW, IEAG.AS, ITPS.SW, IBCI.AS, IEMB.SW, IWDP.SW, IPRP.AS

Most of them (if not all) have the error through the library as well: `KeyError: 'Time Series (Daily)'`, or even `KeyError: 'Time Series (15min)'` for some of them

I definitely believe they are having some issues on their end that is not solved yet. Though this doesn't seem to be the fault of this library, so keeping this issue closed might still be correct.
