### ISSUE TITLE
How can I data for nifty index ?

### ISSUE THREAD

**Issue by mukeshkumarc** [RomelTorres/alpha_vantage#138]
How I can fetch nifty index data ?

**Comment by PatrickAlphaVantage** [comment]
Right now Alpha Vantage offers the following:

> Alpha Vantage APIs are grouped into four categories: (1) Stock Time Series Data, (2) Physical and Digital/Crypto Currencies (e.g., Bitcoin), (3) Technical Indicators, and (4) Sector Performances. 

This currently does not include all indexes (some are on there anyways)
