### ISSUE TITLE
Stock quote on a specific date

### ISSUE THREAD

**Issue by Edward-newbie** [RomelTorres/alpha_vantage#139]
I am a newbie to Alpha_vantage. I'm just wondering how to get the closing price of a stock at a specific date (say, 2019-08-26)? I don't need a long list.

**Comment by PatrickAlphaVantage** [comment]
This is one way to get data as a pandas dataframe. There are a few other ways by changing the "output_format" to either csv or json. Please see the README.md for more info

```
from alpha_vantage.timeseries import TimeSeries

# Your key here
key = 'XXXXXXXXX'
ts = TimeSeries(key, output_format='pandas')
aapl_data, meta_data = ts.get_daily(symbol='GOOGL')
aapl_data.loc['2019-08-26']
```
