### ISSUE TITLE
function sector return Invalid API call

### ISSUE THREAD

**Issue by naveenkash** [RomelTorres/alpha_vantage#149]

**Comment by PatrickAlphaVantage** [comment]
@naveenkash We had been receiving a ton of hits recently on this call (since it's demo and anyone can) that was impacting performance and had to take it down for a small period. 

Please get a key if you are going to be hitting a lot of sector performance.

**Comment by naveenkash** [comment]
i have a key and it's returning an empty object. so you guys made alpha vantage just curios

**Comment by PatrickAlphaVantage** [comment]
Yes, and abusing the demo key was impacting the performance of other users. So sadly we had to take it down again and will put it back up when we have a better solution.

**Comment by PatrickAlphaVantage** [comment]
Leaving open anyways till sector is reinstated

**Comment by naveenkash** [comment]
What the API call limit I can't even call the API I call it one time and
have to wait so long to call it again

**Comment by PatrickAlphaVantage** [comment]
Want to converse on slack? Enter the email into the form from the URL below for an invite. 
https://alphavantage.herokuapp.com/

The API call limit for the free tier is 5 calls/min. It's one of the first sections of the support page:
https://www.alphavantage.co/support/#support

**Comment by k3oni** [comment]
> Yes, and abusing the demo key was impacting the performance of other users. So sadly we had to take down the sector performance again and will put it back up when we have a better solution.

Patrick, you could decrease the call limit for the Sector API endpoint to probably 2 calls/min for the free tier with a valid key and 1 call/min for the demo. There is really no reason why anyone would need to call the Sector endpoint more often than that.
Would be nice to have this endpoint back up, i'm currently calling it every 2 mins fyi.

**Comment by PatrickAlphaVantage** [comment]
Our developer on it has been sick the past few days :( We want to keep it at 5 calls / min for everyone to keep everything as simple as possible, that's a good point though... But yes, we should have it fixed in the next few days

**Comment by PatrickAlphaVantage** [comment]
This is fixed!
