### ISSUE TITLE
Intraday call is offline at the moment.

### ISSUE THREAD

**Issue by RomelTorres** [RomelTorres/alpha_vantage#15]
The intraday API call is offline for the moment. It should be available again in a couple of weeks. 

I hope you guys can work around that for a few weeks

Saludos
Romel

**Comment by organism** [comment]
Is this an Alpha Vantage issue or an issue with the python wrapper?

**Comment by RomelTorres** [comment]
Hi there, it is the API itself. They told me they would bring the call back. But I don't have much info as to when. I posted it as an issue, so people would know about it. ;)

**Comment by RomelTorres** [comment]
Alpha Vantage has corrected the issue. I checked in Travis and all unit-tests were run without issues. All the best.

Saludos
Romel

**Comment by sivavenna** [comment]
Hi tested the below code:
from alpha_vantage.timeseries import TimeSeries
from pandas_datareader import data as web
import pandas as pd


ts = TimeSeries(key='QUQN7PJJVDVR2NV5', output_format='pandas')
data, meta_data = ts.get_intraday(symbol='DISHTV',interval='5min', outputsize='compact')
print(data)
It's throwing error as below:
![image](https://user-images.githubusercontent.com/31187473/30661467-bb438d1c-9e61-11e7-8483-bf73fa58173e.png)
