### ISSUE TITLE
Incorrect amount of data returned

### ISSUE THREAD

**Issue by JamesKBowler** [RomelTorres/alpha_vantage#150]
Hi,
Please see the following example below.

```python
data, meta_data = ts.get_daily('LON:DNL', outputsize='compact')
print(len(data))
# 100
data, meta_data = ts.get_daily('LON:DNL', outputsize='full')
print(len(data))
# 1
```

Thanks

James

**Comment by PatrickAlphaVantage** [comment]
Hmm... Looks like an issue with the API call itself and not the python wrapper. 
I'll put a ticket in, thanks!

**Comment by JamesKBowler** [comment]
Thanks @PatrickAlphaVantage, would you mind posting an update here once you have one please?

**Comment by PatrickAlphaVantage** [comment]
Sure thing, and I'll keep the issue open too actually. Looks there was an issue with the full data - so only the most recent was outputted...

**Comment by PatrickAlphaVantage** [comment]
Same as #173

**Comment by PatrickAlphaVantage** [comment]
Ah, apologies for not getting back earlier on this team.

This issue has been corrected. Thanks for putting bringing it to our attention!
