### ISSUE TITLE
Send requests over https by default

### ISSUE THREAD

**Issue by aloukissas** [RomelTorres/alpha_vantage#151]
By looking at the debug logs, the current pattern is:
- send request over http (port 80),
- get a 301,
- send request over https (port 443) -- this succeeds

The `_ALPHA_VANTAGE_API_URL` should be in https by default, no?

**Comment by PatrickAlphaVantage** [comment]
Ah thanks for pointing this out! I'll aim to fix and release this week.

**Comment by aloukissas** [comment]
It's a quick fix - I can push a PR.
