### ISSUE TITLE
KeyError: 'Time Series (Daily)'

### ISSUE THREAD

**Issue by dahifi** [RomelTorres/alpha_vantage#154]
This seems to be an issue with GBTC's data from the API, and possibly an issue with AV itself. Call was working just fine a few days ago and had me scratching my head until I tried some other calls. 

```
ts.get_daily("GBTC")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/oberyn/.local/share/virtualenvs/prophet-ssuQ7s-c/lib/python3.6/site-packages/alpha_vantage/alphavantage.py", line 164, in _format_wrapper
    data = call_response[data_key]
KeyError: 'Time Series (Daily)'
```

Other get daily calls (GOOG, LC) are working just fine, and get_weekly("GBTC") works as well. 

Not sure best way to pull the actual API response from the debugger. Let me know how you want me to proceed with this.

**Comment by dahifi** [comment]
Ok, seems that `call_response: <class 'dict'>" {}`

Pretty sure that nails it down to the API itself. I've added a ValueError for this case and submitted PR. 
https://github.com/RomelTorres/alpha_vantage/pull/155

**Comment by PatrickAlphaVantage** [comment]
`get_weekly` is working for you for 'GBTC'? I tried both on the wrapper, and by running the whole URL itself. 
https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol=GBTC&apikey=<ENTER_KEY_HERE>

Am I punching something in wrong?

**Comment by dahifi** [comment]
It's not now. Was when I submitted this issue. But at least having the ValueError tells me where it's at.

**Comment by PatrickAlphaVantage** [comment]
Agreed.
