### ISSUE TITLE
Python 3.7?

### ISSUE THREAD

**Issue by Benson563** [RomelTorres/alpha_vantage#156]
Hello, does this work on 3.7? I have been getting this ModuleNotFoundError: No module named 'alpha_vantage' error

**Comment by RomelTorres** [comment]
I did not test on 3.7 de should update the travis configuración to also test for python 3.7. Can Antoine confirm is not working?

**Comment by slepax** [comment]
No issues for me with Python 3.7

**Comment by PatrickAlphaVantage** [comment]
I use 3.7 - works fine for me. @benson563 are you using python notebooks? Sometimes your python notebook can be pointing to its own version of python. If it works in the python shell in a terminal and not the notebook that’s probably the issue
