### ISSUE TITLE
Technical Indicators - VWAP?

### ISSUE THREAD

**Issue by mansard** [RomelTorres/alpha_vantage#157]
Noticed VWAP is not included - any chance of adding it? I can attempt to put something together, but someone more familiar with the codebase would probably have more success.

**Comment by PatrickAlphaVantage** [comment]
Like the VWAP for a given date range?

**Comment by mansard** [comment]
Just a straight pass-through to the VWAP function: https://www.alphavantage.co/documentation/#vwap 

I think just being able to call it from the technical indicators functions? Looks like that section of the library has a way to use all the other functions in the TI section, just not VWAP? Looks like it would go right here? 
https://github.com/RomelTorres/alpha_vantage/blob/0ed8b0cc37c2488a9caf35f9b6c598a5518278e7/alpha_vantage/techindicators.py#L165

Apologies if I'm misunderstanding something obvious here - only been using this API a few days and I was manually calculating VWAP with the intraday data looks like they offer it?

**Comment by PatrickAlphaVantage** [comment]
No worries! I didn't notice the wrapper was missing that! I'll add that to the queue to make. I was planning on doing a new release soon anyway :)

Thank you!

**Comment by mansard** [comment]
Awesome, looking forward to it - this project has been a lifesaver for me, trying to convert from IEX to AV. Hopefully I can contribute something back in the future. Thank you!

**Comment by PatrickAlphaVantage** [comment]
This is in the develop branch now. I'll do a full release next week, but in the meantime, you can get VWAP with:

```pip install git+https://github.com/RomelTorres/alpha_vantage.git@develop```

```ti.get_vwap('MSFT')```

**Comment by PatrickAlphaVantage** [comment]
> Awesome, looking forward to it - this project has been a lifesaver for me, trying to convert from IEX to AV. Hopefully I can contribute something back in the future. Thank you!

Love it 😄
