### ISSUE TITLE
How to change time zone in alpha vantage api

### ISSUE THREAD

**Issue by Logeswaranbca** [RomelTorres/alpha_vantage#159]
Can I change the time zone in the result from Alpha Vantage API? Here is an example of the output. It's currently in EST. I'd like to get it in IST.

'Meta Data': {
    '1. Information': 'Intraday (1min) open, high, low, close prices and volume',
    '2. Symbol': 'BSE:------',
    '3. Last Refreshed': '2019-11-01',
    '4. Output Size': 'Compact',
    '5. Time Zone': 'US/Eastern  <---------------
}

'Time Series (1min)': {
    '2019-11-01 00:08:59': {
      '1. open': '70.7500',
      '2. high': '70.7500',
      '3. low': '70.7500',
      '4. close': '70.7500',
      '5. volume': '0'
    },

**Comment by PatrickAlphaVantage** [comment]
Currently, the time zone that is returned is not modifiable on the side of Alpha Vantage. You can change the time zone as you see fit in your code.

**Comment by RomelTorres** [comment]
But some pandas post processing should do the trick

**Comment by PatrickAlphaVantage** [comment]
https://stackoverflow.com/questions/58654008/how-to-change-time-zone-in-alpha-vantage-api/58662045?noredirect=1#comment103640335_58662045
