### ISSUE TITLE
Seems Issue with API call

### ISSUE THREAD

**Issue by sivavenna** [RomelTorres/alpha_vantage#16]
Hi tested the below code:
from alpha_vantage.timeseries import TimeSeries
from pandas_datareader import data as web
import pandas as pd

ts = TimeSeries(key='YOUR API', output_format='pandas')
data, meta_data = ts.get_intraday(symbol='DISHTV',interval='5min', outputsize='compact')
print(data)
It's throwing error as below:
![image](https://user-images.githubusercontent.com/31187473/30661760-9b8624ac-9e62-11e7-8fcd-c93d31b00a6d.png)

**Comment by RomelTorres** [comment]
Hi sivavenna, I will check it as soon as I have proper internet access :) thanks

**Comment by RomelTorres** [comment]
Hi sivavenna, I have tested this and it is working for me? are you sure you are using the right api key?

**Comment by sivavenna** [comment]
Hi,
 I have given right API key. I tested it again, it's working fine.Thanks
