### ISSUE TITLE
What do you guys think about Finnhub API

### ISSUE THREAD

**Issue by alpha332** [RomelTorres/alpha_vantage#160]
Hi guys,

Just wondering if we can create a new Python wrapper for Finnhub stock API as well : https://finnhub.io/ . They provide 60 free calls/minute with intraday data going back for many years.

Also websocket streaming is available for free. I think this is a way better alternative for alpha vantage.

**Comment by PatrickAlphaVantage** [comment]
Noticed you just made your account, welcome to Github! 

I haven't been able to get any historical data from them, but their real-time WebSocket seems good, I'll have to dig around some more. Have you worked with them at all yet?

**Comment by alpha332** [comment]
Thanks. I'm a student. Just trying out different finance apis. but looks like alpha vantage only has 5 free api calls at the moment which is pretty limited. If you decide to write a python wrapper for finnhub as well, please let me know.
