### ISSUE TITLE
Not able to fetch OTC timeseries quotes 

### ISSUE THREAD

**Issue by yifan-liu** [RomelTorres/alpha_vantage#161]
Hi,

I recently noticed that an ValueError is raised when fetching OTC tickers. The exception is raised by the _handle_api_call and the message is:                   
 'Error getting data from the api, no return was given.'

Ticker examples: "AYSI", "SCGLY"

This used to work fine. Does anyone know what may have changed recently?

Thanks!

**Comment by ecourreges-orange** [comment]
I concur as well, I don't have the problem with GOOG, but have it with GBTC or ETHE which are both OTC.
It has been happening since October 19, 2019.
I think this is the second time it happened, it happened for a couple of days in august 2018 if I am not mistaken.
It is obviously an alpha vantage issue and not an issue of this library, but maybe the error returned by this library could be improved.
**I will contact Alpha Vantage right away and forward if I have more info.**

```
ts = TimeSeries(key='MY_KEY', output_format='pandas')
gbtc, meta_gbtc = ts.get_intraday(symbol=ticker,
                                  interval='1min',
                                  outputsize='full')

```

```
Traceback (most recent call last):
  File "./av_intra_histo.py", line 40, in <module>
    outputsize='full')
  File "/usr/local/lib/python3.5/dist-packages/alpha_vantage/alphavantage.py", line 164, in _format_wrapper
    data = call_response[data_key]
KeyError: 'Time Series (5min)'

```

**Comment by yifan-liu** [comment]
Hey Emmanuel, 
Thank you for the info and contacting AV! It does seem to be a AV issue because I was calling a different endpoint than `ts.get_intraday` and got the same issue with OTC tickers. 

Thanks!

**Comment by PatrickAlphaVantage** [comment]
> I concur as well, I don't have the problem with GOOG, but have it with GBTC or ETHE which are both OTC.
> It has been happening since October 19, 2019.
> I think this is the second time it happened, it happened for a couple of days in august 2018 if I am not mistaken.
> It is obviously an alpha vantage issue and not an issue of this library, but maybe the error returned by this library could be improved.
> **I will contact Alpha Vantage right away and forward if I have more info.**
> 
> > https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=GBTC&interval=1min&apikey=MY_KEY
> > Returns {}
> 
> ```
> ts = TimeSeries(key='MY_KEY', output_format='pandas')
> gbtc, meta_gbtc = ts.get_intraday(symbol=ticker,
>                                   interval='1min',
>                                   outputsize='full')
> ```
> 
> ```
> Traceback (most recent call last):
>   File "./av_intra_histo.py", line 40, in <module>
>     outputsize='full')
>   File "/usr/local/lib/python3.5/dist-packages/alpha_vantage/alphavantage.py", line 164, in _format_wrapper
>     data = call_response[data_key]
> KeyError: 'Time Series (5min)'
> ```

If you upgrade to the newest version of the alpha_vantage package, the error returned is:
`ValueError: Error getting data from the API, no return was given.`

The OTC data has changed it's formatting as of Q3 2019
> As of Q3, 2019, this data is available monthly and historically in the Metrics.
[Check this out](http://utpplan.com)

We (AV) are working on a fix, thanks guys.

**Comment by ecourreges-orange** [comment]
Thanks Patrick, looks like your support team didn't get the memo or chose a different answer, this is what I got from them:

> 
> Hi Emmanuel,
> 
> We do not support the OTC markets.
> 
> Thanks
> Team Alpha Vantage

**Comment by PatrickAlphaVantage** [comment]
@ecourreges-orange - technically that is that the "more correct" answer. But we want to be able to support them as well.

**Comment by stephtouizer** [comment]
Has this ever happened. Does AV support OTC tickers?

**Comment by stephtouizer** [comment]
> @ecourreges-orange - technically that is that the "more correct" answer. But we want to be able to support them as well.
> 
> And are working on a fix

Has this ever happened. Does AV support OTC tickers?

**Comment by ecourreges-orange** [comment]
> 
> 
> > @ecourreges-orange - technically that is that the "more correct" answer. But we want to be able to support them as well.
> > And are working on a fix
> 
> Has this ever happened. Does AV support OTC tickers?

I can't tell you anymore, I switched to yfinance which does realtime but with 15 minute delay, good enough for my needs.
@PatrickAlphaC can you tell us if OTC markets are now working? Thanks.
