### ISSUE TITLE
Prices are not right

### ISSUE THREAD

**Issue by Mackral-Gozoop** [RomelTorres/alpha_vantage#166]
There seems to be an issue with the closing price of the day. The closing price for NSE we are getting from your API is 204.60 but the share market shows 205.50.

**Comment by PatrickAlphaVantage** [comment]
What ticker?

**Comment by Mackral-Gozoop** [comment]
BSE as well as NSE
https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=bse:ABFRL&apikey=XXX
https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=nse:ABFRL&apikey=XXX

**Comment by PatrickAlphaVantage** [comment]
This is a good question, and I've been meaning to do a post on it. Prices depend on who you're asking. 

If you look at yahoo finance for Nov. 13th, you'll see the closing price of bse:ABFRL is 210.55, which is concurrent with what Alpha Vantage is returning.

https://in.finance.yahoo.com/quote/ABFRL.BO/history/
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=bse:ABFRL&apikey=XXX

However, Google finance shows something different:
https://www.google.com/search?ei=csnNXeepCOLD_QaWm4q4DA&q=ABFRL+ticker&oq=ABFRL+ticker&gs_l=psy-ab.3..0i22i30.1144.1944..2065...0.2..0.322.1065.0j3j1j1......0....1..gws-wiz.......0i71j0i67j0.rU0jLmYYZ0E&ved=0ahUKEwjnqsf41OrlAhXiYd8KHZaNAscQ4dUDCAs&uact=5

https://www.bloomberg.com/quote/ABFRL:IN

Prices can be different stock market to stock market, and closing price can depend a lot on how it's actually measured. Many exchanges offer an official "last trade" price, which they consider the closing price, which may or may not be the actual last trade, depending on how trades settle. 

Also, many data vendors give out "consolidated quotes" which are generally the combination of close price from many exchanges.

To make matters harder, after-hours trading also affect the "close price"

For more information:
https://www.investopedia.com/ask/answers/09/closing-price-last-traded-price.asp
