### ISSUE TITLE
`indexing_type='integer'` gives reversed result

### ISSUE THREAD

**Issue by MerienU** [RomelTorres/alpha_vantage#168]
Hi,

When I ask AV to give me the data with `indexing_type='integer'` the data gets reversed compared to when you leave it at `'date'` (default). I don't know what other parameters play a role. See below for an example where it does this.

The only way I found to fix it is `close = pd.Series(close.values,index=close.index[::-1])`.

Is this supposed to be? It seems to me the chronology of the data shouldn't change.

Edit: just noticed that the data with `indexing_type='date'` is also given in reverse. It plots normally because it keeps the datetime index in order on the x-axis en subsequently also the corresponding values.

```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from alpha_vantage.timeseries import TimeSeries

ticker = 'GOOGL'
apikey = 'YOUR_API_KEY' # Fill in your own API key

""" Download the Alphabet stock with a DATE index """
ts = TimeSeries(key=apikey,output_format='pandas',indexing_type='date')
stock, meta_data = ts.get_intraday(symbol=ticker,interval='5min', outputsize='full')

close = stock['4. close']

plt.figure()
plt.title(ticker)
plt.grid()
plt.plot(close)

""" Download the Alphabet stock with a INTEGER index """
ts = TimeSeries(key=apikey,output_format='pandas',indexing_type='integer')
stock, meta_data = ts.get_intraday(symbol=ticker,interval='5min', outputsize='full')

close = stock['4. close']
#close = pd.Series(close.values,index=close.index[::-1]) # only way I found to get it properly reversed

plt.figure()
plt.title(ticker)
plt.grid()
plt.plot(close)
```

**Comment by PatrickAlphaVantage** [comment]
Yes, this is the same as https://github.com/RomelTorres/alpha_vantage/issues/135. We are hesitant about patching it yet since anyone who currently runs their code would have to change their code. (If they run the workaround they'd then have to go back and remove their workaround. )

**Comment by MerienU** [comment]
Yeah, I came to this realisation over the weekend. 
Thanks for your answer though. 
Will do a better search of the issues next time!
