### ISSUE TITLE
Support for changing time period

### ISSUE THREAD

**Issue by shubhinderrana** [RomelTorres/alpha_vantage#169]
Hi,
I don't see any method in documentation with which i can change time period for historical data. It says it has 20+ years of it. How do you pull full intraday data ? eg. i want to pull QQQ prices from 2011 to 2019 at intraday level. Is this possible ?

**Comment by PatrickAlphaVantage** [comment]
Currently, the time period for intraday only goes back to a certain number of entries, depending on the interval selected. It's not possible to get 8 years of intraday data at the moment.
