### ISSUE TITLE
can we control the outputsize with numbers?

### ISSUE THREAD

**Issue by bharath917** [RomelTorres/alpha_vantage#17]
Hello,

In order to only get the latest real-time data point with

get_intraday(symbol='AAPL', interval='30min', outputsize = 'compact' )

according to the docs. output size is either 'full' or 'compact'.

if I call the API every 15min with 'compact' I am still getting 100 data points per API call.
so I have to delete all the 99 points and append my database with the latest (100th) data point.

Is there a way to query only the latest datapoint or control the outputsize with numbers?

get_intraday(symbol='AAPL', interval='30min', outputsize = '1' )

thank you

**Comment by RomelTorres** [comment]
Hi there. No, there is no option to do that at the moment. If you are using the pandas data format, it should not be an issue to just use one value..

Best Regards

Romel
