### ISSUE TITLE
Inaccuracies with intraday data

### ISSUE THREAD

**Issue by Savarani** [RomelTorres/alpha_vantage#174]
From research I understand this may be a previously addressed issue. 

I have noticed consistent inaccuracies with intraday price data of over 0.1% relative to data streaming services such as tradingview or my personal broker. Is this an issue that is currently being looked into?

Or is this inaccuracy at acceptable levels?

Thank you,

**Comment by PatrickAlphaVantage** [comment]
Thanks for the message @Savarani!

It really depends on who is being compared and where the data comes from. We've written an article that expresses something similar here:

https://medium.com/alpha-vantage/why-is-the-price-of-ticker-xxx-different-1daa1871922c

We use consolidated quotes, which means we get data from the major exchanges, and take something of a VWAP. I'm not sure where Tradingview gets their data from, I'm sure its reputable as well, and maybe the slight differences in consolidation account for the margin of difference.
