### ISSUE TITLE
ModuleNotFoundError: No module named 'alphavantageclient'

### ISSUE THREAD

**Issue by QAdri25** [RomelTorres/alpha_vantage#175]
Hi,

I installed alpha_vantage for anaconda using "conda install -c r r-alphavantageclient". Unfortunately I cannot use it in jupyter.

I am trying to import it as:
**from alphavantageclient.timeseries import TimeSeries**
and I receive the error in the subject . 

Could you please support me to find the issue in this case?

Best,
Adriana

**Comment by PatrickAlphaVantage** [comment]
This might be a question to ask on [stackoverflow](https://stackoverflow.com/). alphavantageclient isn't the name of the package. Could you try using ```pip install alpha_vantage```
