### ISSUE TITLE
Many stocks with the same ticker symbol

### ISSUE THREAD

**Issue by bharath917** [RomelTorres/alpha_vantage#18]
Hello,

It seems like there are many stocks with the same ticker symbol, the API is not able to differentiate between various stock markets, priority is given to NYSE over others.
ex:
American Campus Communities, Inc.(NYSE:ACC)
ACC Ltd(NSE:ACC)
Is there a way to use NSE's ACC
I found more than 30 scrips with same ticker symbol in the top 250 scrips.

Thank you

**Comment by RomelTorres** [comment]
Yo, as far as I know, they uno y have support dir NSYE at the moment. Maybe write directly to them and see if they think on adding support in the future. 

Romel

**Comment by ACPK** [comment]
@RomelTorres - Do you know who is behind it?

**Comment by RomelTorres** [comment]
@ACPK No, I actually don't know who is behind the API. I usually send them emails on their contact page and they answer...
