### ISSUE TITLE
import errors

### ISSUE THREAD

**Issue by OdincoGaming** [RomelTorres/alpha_vantage#180]
no module named 'alpha_vantage' found. help?

**Comment by PatrickAlphaVantage** [comment]
For future issues, be sure to post more than just the error. You want to give as much information as possible to help us help you. Like what machine you're running it on, what's the code look like, the exact error as opposed to paraphrasing. This will make it much easier to triage your issue in a timely manner. 

I'm assuming you're running this on some sort of linux based system. 
Did you run:
```pip install alpha_vantage``` 
In your shell?

**Comment by OdincoGaming** [comment]
windows, ran pip install alpha_vantage, ran pip install alpha_vantage<=2.0, ran pip install alphavantage

code:

from alpha_vantage.timeseries import TimeSeries (also tried alphavantage)

^^ both edits of code failed  while both alpha_vantage and alphavantage appeared on my pip list

never gets past the import statement

**Comment by OdincoGaming** [comment]
also tried the same with just alphavantage and just alpha_vantage installed

**Comment by PatrickAlphaVantage** [comment]
```pip freeze | grep "alpha-vantage"```
