### ISSUE TITLE
Weekly TimeSeries and Technical Indicators on the weekly timeframe incorrectly delimits dates

### ISSUE THREAD

**Issue by aalphav** [RomelTorres/alpha_vantage#181]
Hi,

When retrieving the adjusted weekly TimeSeries for a stock using get_weekly_adjusted or even when retrieving the exponential moving average (EMA) using the weekly time interval, the API returns dates that do not correctly delimit a week. More especifically, the dates it returns are not always 7 days apart.

Take the following code, for instance.

```python
from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.techindicators   import TechIndicators
from pprint import pprint

ts = TimeSeries(key='xxx', output_format='pandas')
pd, md = ts.get_weekly_adjusted(symbol='SULA11.SAO')

ti = TechIndicators(key='xxx', output_format='pandas')
emad, emamd = ti.get_ema(symbol='SULA11.SAO', interval='weekly', time_period=9, series_type='close')

pprint(pd.head(10))
print('--')
pprint(emad.tail(10))
```

Its output follows.

```
            1. open  2. high  3. low  4. close  5. adjusted close   6. volume  7. dividend amount
date
2020-01-23    65.31    67.88   65.31     67.15            67.1500   8519000.0              0.0000
2020-01-17    64.17    65.00   62.35     65.00            65.0000  11545100.0              0.0000
2020-01-10    63.62    65.18   62.39     64.32            64.3200  17137400.0              0.0000
2020-01-03    60.06    64.85   59.07     64.85            64.8500  15252500.0              0.0000
2019-12-30    58.98    60.94   58.49     60.34            60.3400   1712800.0              0.0000
2019-12-27    57.38    58.50   56.79     58.21            58.2100   2978800.0              0.0000
2019-12-23    56.83    57.59   56.34     57.39            57.3900   2147400.0              0.0000
2019-12-20    53.99    57.00   53.29     56.60            56.6000  12732800.0              0.2839
2019-12-13    53.55    53.83   50.79     53.70            53.4252  14030800.0              0.0000
2019-12-06    53.57    54.42   52.20     53.55            53.2759  13193700.0              0.0000
--
                EMA
date
2019-12-06  49.4717
2019-12-13  50.3174
2019-12-20  51.5739
2019-12-23  52.7371
2019-12-27  53.8317
2019-12-30  55.1333
2020-01-03  57.0767
2020-01-10  58.5253
2020-01-17  59.8203
2020-01-23  61.2862
```

Notice that there are dates such as 2019-12-20 (friday) followed by 2019-12-23 (monday), and 2019-12-30 (monday) followed by 2020-01-03 (friday). The values for the EMA also do not match data from other sources, like Trading View, for example, which suggests the possible problem with the week delimiting is somehow influencing the EMA calculation.

**Comment by PatrickAlphaVantage** [comment]
Welcome to GitHub! 

Glad to see new users on the package here. Good question.
12/25 was a holiday as was 01/01, so the API notates that with the functionality you're seeing above. This way users don't get weird holiday data.

If you have a link to TradingView, feel free to drop it here.

**Comment by aalphav** [comment]
Hi @PatrickAlphaVantage, thank you for the prompt and helpful replies.

However, I don't understand why the API should "notate" holidays. A weekly candle is a weekly candle; it has an opening, a high, a low and a closing price, no matter the number of business days (or holidays) within that week. 

Moreover, it seems that when you break weeks with irregular time intervals (!= 7 days) you affect how technical indicators are calculated. Take, for instance, the 9 period EMA I have mentioned in my original post. Say I want to calculate the 9 period EMA for the last complete weekly candle, I'd consider the following close values:

week 9
week 9
week 9
week 9

**Comment by aalphav** [comment]
Hi @PatrickAlphaVantage, thank you for the prompt and helpful replies.

However, I don't understand why the API should "notate" holidays. A weekly candle is a weekly candle; it has an opening, a high, a low and a closing price, no matter the number of business days (or holidays) within that week.

Moreover, it seems that when you break weeks with irregular time intervals (!= 7 days) you affect how technical indicators are calculated. Take, for instance, the EMA, which I have mentioned in my original post. If you consider 2019-12-23  and 2019-12-27 are separate weeks, then your result will be wrong, because in fact they both represent dates within the same week and should be treated as a single candle.

You can check how the results I posted earlier for the 9 period EMA (closing price) for the SULA11.SAO stock differ from the results shown in Trading View by looking at https://www.tradingview.com/chart/?symbol=BMFBOVESPA%3ASULA11&interval=W.

**Comment by PatrickAlphaVantage** [comment]
Thanks @aalphav, at the moment this is the intentional functionality. If we get enough interest we will change it to what you see with tradingview, or maybe add a new endpoint/variable. Thank you!
