### ISSUE TITLE
Past EMA values changing in time

### ISSUE THREAD

**Issue by aalphav** [RomelTorres/alpha_vantage#182]
Hi,

When retrieving the EMA for a cryptocurrency, I have noticed that past values are changing. In particular, the EMA value for D-1 (the previous day) changes depending on when the code is ran.

Take the following code as an example.

```python
from alpha_vantage.techindicators import TechIndicators
from pprint import pprint

ti = TechIndicators(key='xxx', output_format='pandas')
emad, emamd = ti.get_ema(symbol='LTCUSD', interval='daily', time_period=9, series_type='close')

pprint(emad)
```
I am located in UTC-3. I executed this code on 16-01-2020 at aprox 23:00 UTC-3 (i.e., aprox 17-01-2020 02:00 UTC). The EMA part of the output showed the following with regards to the last couple of days:

```
2020-01-13 47.5134
2020-01-14 49.6798
2020-01-15 51.3631
2020-01-16 54.3200
2020-01-17 53.5277
```

I executed the same code again on 17-01-2020 at aprox 08:00 UTC-3 (i.e., aprox 17-01-2020 11:00 UTC). This time, the same part of the output showed the following:

```
2020-01-13 47.5134
2020-01-14 49.6798
2020-01-15 51.3631
2020-01-16 52.5905
2020-01-17 53.5277
```

Notice that the value for 16-01-2020 changed. It doesn't seem to make sense. The value for the present day (17-01-2020) could change, since the daily candle has not closed yet, but the previous day value should not.

**Comment by PatrickAlphaVantage** [comment]
First two support questions posted, love it. 

Another good question. The crypto daily refreshes at midnight EST, so you're seeing exactly the correct functionality. The close price for 16-01-2020 wouldn't be final until the day is actually over, by EST standards.

Thank you!
