### ISSUE TITLE
NESN.SWI + outputsize=full produces error

### ISSUE THREAD

**Issue by ymyke** [RomelTorres/alpha_vantage#183]
Here's another ticker that produces the "invalid API call" error:

https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=NESN.SWI&outputsize=full&apikey=KEY

See also #173 .

**Comment by ymyke** [comment]
3 more: IWDC.SWI, IUSC.SWI, SPICHA.SWI.

**Comment by PatrickAlphaVantage** [comment]
Thanks @ymyke , these happen when there is an issue with the full history data. Instead of returning wrong data it returns nothing. I'll keep the issue open here though.

**Comment by ymyke** [comment]
Thanks, @PatrickAlphaVantage. So is this a bug in AVs API/data? Should this be reported to them? And if so, what is the best way to do so?

**Comment by PatrickAlphaVantage** [comment]
@ymyke correct, this is an AV bug. Yes it should be reported. I've let them know already :D

**Comment by RDZipZap** [comment]
Same for UBI.PA

**Comment by 013robert** [comment]
Same for: GLPG.AMS , HEIJM.AMS , NSI.AMS and VASTN.AMS

**Comment by NateFern1007** [comment]
AlphaVantage returned data for the indices listed below.

# UBI.PA
# NESN.SWI
# GLPG.AMS
# HEIJM.AMS
# NSI.AMS
# VASTN.AMS

If someone wants to take a second look that would be great!

**Comment by mykhailo-saienko** [comment]
Also, all Lse-traded symbols:
VOD.LON
ISF. LON
SN.LON, etc
Some Hongkong-based:
0268.HG
and ETFs:
SLV, ILTB, etc.

**Comment by carloswm85** [comment]
Guys, what's the best solution for this problem?
