### ISSUE TITLE
The stock data seems incorrect

### ISSUE THREAD

**Issue by flyingbee2012** [RomelTorres/alpha_vantage#185]
Hi, I am trying to develop a personal website which can analyze stock data. While leveraging your API, it seems that the historical data doesn't match with what I see in Yahoo finance as the stock prices in Google. I am just wondering if this is an expected.
For example: According to 
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&outputsize=full&apikey=demo
The close price at 2/02/2000 is 100.81, but it is actually 30.41 in Yahoo finance as well as other stock data platform.

**Comment by PatrickAlphaVantage** [comment]
You want to use the adjusted close endpoint. The close gives the raw price, the adjusted close is what the close would be given splits and corporate actions (considered the true closing price)
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=MSFT&outputsize=full&apikey=demo

You'll see the adjusted close is 33.18

When I pulled from YFinance I got 33.11, 33.18 from Intrinio. How'd you get 30.41?
