### ISSUE TITLE
Returned FX data in reversed order as of 3Feb20

### ISSUE THREAD

**Issue by roark52** [RomelTorres/alpha_vantage#186]
Using Python 3.6.5; recent update to Pandas1
Data requests to AlphaVantage seem to be returned in reverse order  from previously:
Example1 - Previously data returned oldest to newest...
![image](https://user-images.githubusercontent.com/40121349/73661089-0dfa4680-46cc-11ea-9f76-c8d5b524e316.png)

Example2 - As of 3rd Feb '20, data returned newest to oldest...
![image](https://user-images.githubusercontent.com/40121349/73661313-6fbab080-46cc-11ea-95bb-8763ec32abce.png)

This creates a problem when current code is now slicing differently formatted data, resulting in incorrect values (due to incorrect location of slices) being passed.
thx

**Comment by PatrickAlphaVantage** [comment]
Hmmm, yeah there seems to be an issue when converting the JSON to pandas. Maybe it's best if some functionality is added to return all calls in desc. or asc. order

**Comment by roark52** [comment]
Hi Patrick - contacted AV, they said no change to their data feed.
But i’ve not updated api...
I did update pandas to v1

I’ll insert a date-sort for now
but hopefully other folks are catching the uncertain prices before applying to trades

thx for the good work!
mark

Sent from my iPhone

On 4 Feb 2020, at 00:38, Patrick Collins <notifications@github.com> wrote:

﻿

Hmmm, yeah there seems to be an issue when converting the JSON to pandas. Maybe it's best if some functionality is added to return all calls in desc. or asc. order

**Comment by PatrickAlphaVantage** [comment]
I think this would make a good enhancement for the package too, it's not the first issue raised about the ordering of data. Thanks for the suggestion!
