### ISSUE TITLE
Search for Nasdaq-100 index quote

### ISSUE THREAD

**Issue by thburkhalter** [RomelTorres/alpha_vantage#187]
I am AlphaVantage free version with an API key. ISIN search does not return any satisfactory result.

https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=US6311011026&apikey={key}

https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=nasdaq100&apikey={key}

Appreciate if anyone can point me in the right direction.

(Similar challenges with other indicies, is there a repository to look up?)

**Comment by PatrickAlphaVantage** [comment]
Indicies are currently not supported with the Alpha Vantage API. You can get a list of the index's constituents and pull them to generate the index yourself if interested. 

Your use of the search endpoint is correct.

**Comment by thburkhalter** [comment]
This is interesting Patrick,

Your statement is written all over the chat groups, etc.....

I draw myself from time to time 3 distinct index quotes from the website. It works and matches Bloomberg quotes. These indicies are equivalent or less popular to the Nasdaq-100 index.

(is there a repository to look up what is possible?)

Does the paid service offer more response, help to understand the possibilities?
