### ISSUE TITLE
Retries keyword argument doesn't work properly

### ISSUE THREAD

**Issue by PatrickAlphaC** [RomelTorres/alpha_vantage#188]

**Comment by SandersAaronD** [comment]
It looks like this literally isn't implemented, maybe it accidentally got removed during an update?

**Comment by PatrickAlphaVantage** [comment]
Maybe, in any case it would be a nice functionality to have, and just default to 0

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.

**Comment by xxccy668** [comment]
> 由于自上次发布响应以来的时间较长，暂时关闭此问题。如果需要，将重新打
Can you restore the "retries" function?

**Comment by xxccy668** [comment]
> 由于自上次发布响应以来的时间较长，暂时关闭此问题。如果需要，将重新打开。

Can you restore the "retries" function?
