### ISSUE TITLE
Something between Compact and Full?

### ISSUE THREAD

**Issue by techietrader** [RomelTorres/alpha_vantage#19]
Hey,

Is there a way to download daily data of 2-3 years. 
I am downloading data for around 270 Healthcare stock in python and I want it for atleast 3 years.

outputsize='full', takes a lot of time, even compact mode took 20 mins

Is there any other way to do it

**Comment by RomelTorres** [comment]
Hey @techietrader 

Sadly not, that's just what the people from the alpha vantage API offer. Maybe you can contact them and ask if they would like to implement that differently. If they do I would change the library to reflect the change.

Best Regards,

Romel

**Comment by techietrader** [comment]
😥😣

Okay. Will contact them
