### ISSUE TITLE
There is issue with symbol of different stocks

### ISSUE THREAD

**Issue by lakhan47** [RomelTorres/alpha_vantage#192]
There is issue with symbol of stocks which contains '&'  such as 'M&M' .
So when you pass this stock name into argument then it will consider '&'  as one of the part of url and that's why it'll break name into to like 'M' and 'M' as key/value pair.
`https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=NSE:M&M&interval=60min&apikey=demo`

so as temporary solution i suggest to use regex and %26 in place of '&',
`import re`
`regex = re.compile('[@_!#$%^&*()<>?/\|}{~:]') `
`if(regex.search(symbol) == None):
       print("Symbol is accepted")` 
`else:` 
`    Symbol = Symbol.replace('&','%26')`
 `   print(Symbol)`

also you can solve `ValueError: Invalid API call.` using above solution if it occurs because of this symbol issue.

**Comment by PatrickAlphaVantage** [comment]
This isn't an issue with different symbol names, URLs just don't use ampersands.

Take a look here:
https://stackoverflow.com/questions/16622504/escaping-ampersand-in-url
