### ISSUE TITLE
No Error on Invalid Key

### ISSUE THREAD

**Issue by dprosperino** [RomelTorres/alpha_vantage#194]
I'm writing a test, which should check if a given API key is valid or not. By doing so I discovered that if you don't pass a valid API key, the request still works.
Is this a bug or a feature?

Minimum working example
```python
from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries(key="NOT A VALID API KEY", output_format="pandas")
intraday_data, _ = ts.get_intraday(symbol="GOOG", interval="1min", outputsize="full")
```

**Comment by PatrickAlphaVantage** [comment]
This is a bit of a feature. There are some measures taken to allow users who may not know of the api limits to still make calls, but they will eventually get a message saying to sign up for a free key or upgrade to a premium key.
