### ISSUE TITLE
Python 3.7.0 issue time series

### ISSUE THREAD

**Issue by expedyst** [RomelTorres/alpha_vantage#196]
Hi I get the following issue  when I do this:

from alpha_vantage.timeseries import TimeSeries

issue is:
can't read /var/mail/alpha_vantage.timeseries

I am wondering why?

**Comment by PatrickAlphaVantage** [comment]
https://stackoverflow.com/questions/16069816/getting-python-error-from-cant-read-var-mail-bio

Here is a link that may lend some insight. Could you give some more information? Are you running it on a Linux box? What’s the command you’re using to run it? Are you in the right directory?

**Comment by expedyst** [comment]
Hi patrick I am using MacOs

command is 

from alpha_vantage.timeseries import TimeSeries
