### ISSUE TITLE
Adjusted Close SMA

### ISSUE THREAD

**Issue by jayvle** [RomelTorres/alpha_vantage#197]
I would like to be able to get the SMA of the adjusted close prices. Now if I plot the adjusted close price with the SMA i can see those huge diffrences because of stock splits. Could you be able to make a fuction that can take the SMA, EMA and others from the adjusted values.

**Comment by PatrickAlphaVantage** [comment]
Thanks for the suggestion jayvle! I'll add that as a suggested enhancement for this repo, and put in a suggestion for the API itself.

**Comment by jayvle** [comment]
Thank you very much, AlphaVantage is honestly the best API out there. I've been using the yfinance API (substitute for the deprecated yahoo-finance API) now quite some time, but writing my own get_sma, get_obv etc. functions has gotten old, but than I found AlphaVantage which has these functions built in. I hope you will add this feature, that allows you to get the technical indicators of the adjusted prices. Please keep me up to date if it isn't much work for you. If I can help in any way, (I am proficient at python & C#) please contact me. Thanks in advance.

**Comment by AlphaVantageSupport** [comment]
Closing as all the technical indicators (e.g., SMA) are now calculated from adjusted OHLCV values.
