### ISSUE TITLE
Pandas Key Error

### ISSUE THREAD

**Issue by AdiSai** [RomelTorres/alpha_vantage#198]
When I try to get data from differentl technical indicators for a specific timestamp for the 1min interval (say '2020-03-27 15:56'), it works perfectly for the MACD. However, when I try querying RSI, VWAP, or SMA with the same timestamp I get KeyError: '2020-03-27 15:56' despite the code being very similar for the two.

        if req is 'ta':
            indicator = reqExtra[0]
            interval = reqExtra[1]
            if reqExtra[2] is None:
                timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
            else:
                timestamp = reqExtra[2]
            if len(reqExtra) > 3:
                time_period = int(reqExtra[3])
            else:
                time_period = 20
            ti = TechIndicators(key=api_key, output_format='pandas')
            if indicator is 'macd':
                data, meta_data = ti.get_macd(symbol=stock, interval=interval)
                return data[timestamp]
            elif indicator is 'rsi':
                data, meta_data = ti.get_rsi(symbol=stock, interval=interval, time_period=time_period)
                return data[timestamp]
            elif indicator is 'sma':
                data, meta_data = ti.get_sma(symbol=stock, interval=interval, time_period=time_period)
                return data[timestamp]
            elif indicator is 'vwap':
                data, meta_data = ti.get_vwap(symbol=stock, interval=interval)
                return data[timestamp]

Do you have any suggestions for why this is the case? For the other indicators, I am able to query up to the hour timestamp, but after that I get this key error from pandas, but with MACD it works even with the minute timestamp.

**Comment by AdiSai** [comment]
This is the output I get in console: ![Screen Shot 2020-03-29 at 10 54 13 PM](https://user-images.githubusercontent.com/1911913/77870753-3e63ea00-7210-11ea-88a4-d68a4828f394.png)

**Comment by garethiv** [comment]
could you try adding a breakpoint at one of the offending lines to manually search the data frame for your desired timestamp? 

e.g.
`
elif indicator is 'rsi':
            data, meta_data = ti.get_rsi(symbol=stock, interval=interval, time_period=time_period)
 breakpoint here>>           return data[timestamp]
`

**Comment by AdiSai** [comment]
The timestamp does appear to be in the dataframe:
![Screen Shot 2020-03-30 at 12 32 26 AM](https://user-images.githubusercontent.com/1911913/77875492-3b6ff600-721e-11ea-9f4f-586684f52dfc.png)

**Comment by AdiSai** [comment]
Fixed by using: `data.loc[timestamp]`
