### ISSUE TITLE
Just after a pip install : ImportError: No module named 'alpha_vantage'

### ISSUE THREAD

**Issue by Cxrille** [RomelTorres/alpha_vantage#2]
It looks like it doesn't work out of the box. What I did :
- set my environment with virtualenv
- pip install alpha_vantage
- type python and try to import module
- fail :)

I look forward to be able to test your module!

-----------
Python console
-----------

$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import alpha_vantage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'alpha_vantage'
>>>

-----------
pip install
-----------

pip install alpha_vantage
Collecting alpha_vantage
  Downloading alpha_vantage-0.1.3.tar.gz
Requirement already satisfied: simplejson in ./env/lib/python3.5/site-packages (from alpha_vantage)
Collecting pandas (from alpha_vantage)
  Downloading pandas-0.20.1-cp35-cp35m-manylinux1_x86_64.whl (24.0MB)
    100% |████████████████████████████████| 24.0MB 38kB/s 
Collecting nose (from alpha_vantage)
  Downloading nose-1.3.7-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 253kB/s 
Requirement already satisfied: python-dateutil>=2 in ./env/lib/python3.5/site-packages (from pandas->alpha_vantage)
Requirement already satisfied: pytz>=2011k in ./env/lib/python3.5/site-packages (from pandas->alpha_vantage)
Requirement already satisfied: numpy>=1.7.0 in ./env/lib/python3.5/site-packages (from pandas->alpha_vantage)
Requirement already satisfied: six>=1.5 in ./env/lib/python3.5/site-packages (from python-dateutil>=2->pandas->alpha_vantage)
Building wheels for collected packages: alpha-vantage
  Running setup.py bdist_wheel for alpha-vantage ... done
  Stored in directory: /home/cyrille/.cache/pip/wheels/37/2b/e9/95c76cfabd97fa92b83c1ff19e3ee3b17d7d9620b373d8b577
Successfully built alpha-vantage
Installing collected packages: pandas, nose, alpha-vantage
Successfully installed alpha-vantage-0.1.3 nose-1.3.7 pandas-0.20.1

**Comment by RomelTorres** [comment]
Hello there, hmmm I just did the same and for me it worked:
* I set my environment with virtualenv to python 3.5
* I activated the environment
* pip install alpha_vantage
* open python console and import.

I am wondering what it could be.  
## Pip Install
(alpha_vantage_35)  ~/Tmp  pip install alpha_vantage
Collecting alpha_vantage
  Using cached alpha_vantage-0.1.3.tar.gz
Collecting simplejson (from alpha_vantage)
  Using cached simplejson-3.10.0.tar.gz
Collecting pandas (from alpha_vantage)
  Downloading pandas-0.20.1-cp35-cp35m-manylinux1_x86_64.whl (24.0MB)
    100% |████████████████████████████████| 24.0MB 58kB/s 
Collecting nose (from alpha_vantage)
  Downloading nose-1.3.7-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 3.1MB/s 
Collecting numpy>=1.7.0 (from pandas->alpha_vantage)
  Downloading numpy-1.12.1-cp35-cp35m-manylinux1_x86_64.whl (16.8MB)
    100% |████████████████████████████████| 16.8MB 52kB/s 
Collecting python-dateutil>=2 (from pandas->alpha_vantage)
  Using cached python_dateutil-2.6.0-py2.py3-none-any.whl
Collecting pytz>=2011k (from pandas->alpha_vantage)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5 in ./alpha_vantage_35/lib/python3.5/site-packages (from python-dateutil>=2->pandas->alpha_vantage)
Building wheels for collected packages: alpha-vantage, simplejson
  Running setup.py bdist_wheel for alpha-vantage ... done
  Stored in directory: /home/rtorres/.cache/pip/wheels/37/2b/e9/95c76cfabd97fa92b83c1ff19e3ee3b17d7d9620b373d8b577
  Running setup.py bdist_wheel for simplejson ... done
  Stored in directory: /home/rtorres/.cache/pip/wheels/43/c5/ef/edcebbb19becffd2ba75bf219afdbb4ca85198b2d909f1b31b
Successfully built alpha-vantage simplejson
Installing collected packages: simplejson, numpy, python-dateutil, pytz, pandas, nose, alpha-vantage
Successfully installed alpha-vantage-0.1.3 nose-1.3.7 numpy-1.12.1 pandas-0.20.1 python-dateutil-2.6.0 pytz-2017.2 simplejson-3.10.0

## Import Module
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import alpha_vantage
>>>

**Comment by Cxrille** [comment]
I made a test environment and only installed alpha_vantage :
- cd /tmp
- virtualenv test
- source test/bin/activate
- pip install alpha_vantage

Then, I only got a dist-info file :

ls -1 test/lib/python3.5/site-packages

alpha_vantage-0.1.3.dist-info
appdirs-1.4.3.dist-info
appdirs.py
dateutil
easy_install.py
nose
nose-1.3.7.dist-info
numpy
numpy-1.12.1.dist-info
packaging
packaging-16.8.dist-info
pandas
pandas-0.20.1.dist-info
pip
pip-9.0.1.dist-info
pkg_resources
__pycache__
pyparsing-2.2.0.dist-info
pyparsing.py
python_dateutil-2.6.0.dist-info
pytz
pytz-2017.2.dist-info
setuptools
setuptools-35.0.2.dist-info
simplejson
simplejson-3.10.0.dist-info
six-1.10.0.dist-info
six.py
wheel
wheel-0.29.0.dist-info


Any log I could check or verbose command I should use?

**Comment by RomelTorres** [comment]
I am checking it out, I actually got the same error testing on my server. Give me some time to check if I find out the issue.

Romel

**Comment by RomelTorres** [comment]
Hey Cxrille,

after checking here and there I think I managed to find out the root of the problem, long story short the api_calls folder has been renamed back to alpha_vantage (as it was before) and it should work now fine (version 0.1.8). 

I tested it in my server where I observed the same issues and it worked there. Please uninstall the package and install it again and let me know if it worked.

Best regards
Romel

**Comment by RomelTorres** [comment]
Hey Cxrille,

after checking here and there I managed to find out the root of the problem, long story short the api_calls folder has been renamed back to alpha_vantage (as it was before) and the internal imports fixed .it should work now fine (version 0.1.9).

I tested it in my server where I observed the same issues and it worked there and the unit test ran. Please uninstall the previous version of the package, install it again and let me know if it that worked.

Best regards
Romel

**Comment by Cxrille** [comment]
0.1.9 is working great. Thank you!
