### ISSUE TITLE
can request multiple interval in techIndicators and TimeSeries?

### ISSUE THREAD

**Issue by fxdt** [RomelTorres/alpha_vantage#200]
Hi, 

is it possible to get more interval value at the same time ? i tried multiple ways below but it's now working. anyone can help me out ?

ti = TechIndicators(key='YOUR_API_KEY', output_format='pandas')
data, meta_data = ti.get_bbands(symbol='MSFT', interval='60min', time_period=60)

**Comment by PatrickAlphaVantage** [comment]
I'm not sure what you mean. Do you mean multiple symbols? If that's the case then no.

**Comment by fxdt** [comment]
hi Patrick,

thanks for looking into this. 

not multiple symbols but multiple timeframe. i am new to python so i might explain it wrongly. here is a sample where i did on tradingview to print out the values of an indicator from each timeframe. i would like to do the same in python

the result
['GBPCAD', 'M: -30.905168456807182', 'W: -44.6189529489729', 'D: -33.36257076788142', 'H4: -24.79764532744737', 'H1: -37.9932356257055', 'M30: -26.773049645391815', 'M15: -44.94047619047944', 'M5: -68.11594202899141', 'M2: -66.15384615385035']
['GBPCAD']
