### ISSUE TITLE
No module named 'alpha_vantage.timeseries'

### ISSUE THREAD

**Issue by kruzzik** [RomelTorres/alpha_vantage#202]
Hi,
I pip installed alpha-vantage 2.1.3 on a windows machine with python 3.8.1
Trying to run your example code and get the following: 

No module named 'alpha_vantage.timeseries'
Thanks!

**Comment by PatrickAlphaVantage** [comment]
Hi kruzzik, 
Sadly, that's not enough information to go off of to trouble shoot the problem. 
Have you check stackoverflow? https://stackoverflow.com/questions/15052206/python-pip-install-module-is-not-found-how-to-link-python-to-pip-location

I'm closing the issue, but feel free to keep asking.

**Comment by robertpearce** [comment]
i have the same issue also, for what it's worth. 

linux docker container, centos 8.  pip3 install of alpha_vantage which pulled down alpha_vantage 2.1.3

from alpha_vantage.timeseries import TimeSeries 

in a file called bot.py is enough to reproduce this issue.

ModuleNotFoundError: No module named 'alpha_vantage.timeseries'; 'alpha_vantage' is not a package

**Comment by robertpearce** [comment]
@kruzzik make sure you don't have a file called alpha_vantage.py in the dir, or you didn't call the file you are working on that
