### ISSUE TITLE
Timeseries for currency pairs returns always 0 in volume column

### ISSUE THREAD

**Issue by MarVL92** [RomelTorres/alpha_vantage#203]
Hi Guys,

I am currently playing with alpha vantage in python and am currently facing the following problem:

When I try to do a query for market data of currency pairs, the column "volume" only contains the value 0 in each line. If I change the query to a stock, like for example "MSFT" the values for volume seems to be reasonable. Also tried for other currency pairs and they all show the same issue. Changing the time interval also could not solve the problem.

Hope you can help me! Also, this is the code I am using:

//
from alpha_vantage.timeseries import TimeSeries
import pandas as pd

key_path = "path to my key"
ts = TimeSeries(key=open(key_path,'r').read(), output_format='pandas')
temp_data = ts.get_intraday(symbol="MSFT",interval='5min', outputsize='full')[0]
//

Kind regards,

**Comment by roark52** [comment]
Hi MarV
Perhaps should be using ForeignExchange (TimeSeries is for equities I think)
I dont think fx intraday returns volume data, only date / OHLC

try using:
from alpha_vantage.foreignexchange import ForeignExchange
cur = ForeignExchange(key=AV_KEY, output_format='pandas')
data, meta_data = cur.get_currency_exchange_intraday(from_symbol='GBP',
                                                     to_symbol='USD',
                                                     interval='1min',
                                                     outputsize='compact')

**Comment by MarVL92** [comment]
> from alpha_vantage.foreignexchange import ForeignExchange
> cur = ForeignExchange(key=AV_KEY, output_format='pandas')
> data, meta_data = cur.get_currency_exchange_intraday(from_symbol='GBP',
> to_symbol='USD',
> interval='1min',
> outputsize='compact')

I just tried but I am getting the following error message:
ValueError: Output format pandas is not compatible with the ForeignExchange class

**Comment by roark52** [comment]
you still need to import pandas...sorry, i was expecting you knew that...
in jupyter, try...

import pandas as pd
from alpha_vantage.foreignexchange import ForeignExchange
MY_KEY = 'XYZ;   # put YOUR key in quotes here
cur = ForeignExchange(key=MY_KEY, output_format='pandas')
data, meta_data = cur.get_currency_exchange_intraday(from_symbol='GBP',
                                                     to_symbol='USD',
                                                     interval='1min',
                                                     outputsize='compact')
data   # this will print heads data

**Comment by roark52** [comment]
obviously you need to format columns properly, and think about using stackoverflow for this sort of problem

**Comment by MarVL92** [comment]
> you still need to import pandas...sorry, i was expecting you knew that...
> in jupyter, try...
> 
> import pandas as pd
> from alpha_vantage.foreignexchange import ForeignExchange
> MY_KEY = 'XYZ; # put YOUR key in quotes here
> cur = ForeignExchange(key=MY_KEY, output_format='pandas')
> data, meta_data = cur.get_currency_exchange_intraday(from_symbol='GBP',
> to_symbol='USD',
> interval='1min',
> outputsize='compact')
> data # this will print heads data

I did import pandas... so this is the code I am trying to run:

import pandas as pd
from alpha_vantage.foreignexchange import ForeignExchange
MY_KEY = 'XYZ' # yes I put my key in here
cur = ForeignExchange(key=MY_KEY, output_format='pandas')
data, meta_data = cur.get_currency_exchange_intraday(from_symbol='GBP',
to_symbol='USD',
interval='1min',
outputsize='compact')

ValueError: Output format pandas is not compatible with the ForeignExchange class

**Comment by roark52** [comment]
import pandas as pd
import AV_keys_01 as av
from alpha_vantage.foreignexchange import ForeignExchange
MY_KEY = 'XYZ'
cur = ForeignExchange(key=MY_KEY, output_format='pandas')
data, meta_data = cur.get_currency_exchange_intraday(from_symbol='GBP',
                                                     to_symbol='USD',
                                                     interval='1min',
                                                     outputsize='compact')
data


works for me...

**Comment by roark52** [comment]
import pandas as pd
from alpha_vantage.foreignexchange import ForeignExchange
MY_KEY = 'IKSV4289A1I9V0JK'
cur = ForeignExchange(key=MY_KEY, output_format='pandas')
data, meta_data = cur.get_currency_exchange_intraday(from_symbol='GBP',
                                                     to_symbol='USD',
                                                     interval='1min',
                                                     outputsize='compact')
data

**Comment by roark52** [comment]
import pandas as pd
import AV_keys_01 as av
from alpha_vantage.foreignexchange import ForeignExchange
MY_KEY = 'xyz'
cur = ForeignExchange(key=MY_KEY, output_format='pandas')
data, meta_data = cur.get_currency_exchange_intraday(from_symbol='GBP',
                                                     to_symbol='USD',
                                                     interval='1min',
                                                     outputsize='compact')
data

this works for me...

**Comment by roark52** [comment]
import pandas as pd
from alpha_vantage.foreignexchange import ForeignExchange
MY_KEY = 'xyz'
cur = ForeignExchange(key=MY_KEY, output_format='pandas')
data, meta_data = cur.get_currency_exchange_intraday(from_symbol='GBP',
                                                     to_symbol='USD',
                                                     interval='1min',
                                                     outputsize='compact')
data

**Comment by PatrickAlphaVantage** [comment]
For your error, @MarVL92 could you run a `pip freeze` and see what version of alpha_vantage you're on? I have tried your code and it was successful. However, you pointed out that the readme is outdated! 

> Also when I check the documentation it says that ForeignExchange is not supporting pandas

Thank you! I'll add an issue for that. 

To solve your initial question, the intraday endpoint does not return volume. In fact, none of the FX endpoints return volume. You can see the documentation for the intraday FX endpoint (and all endpoints) here:

https://www.alphavantage.co/documentation/#fx-intraday

I'm closing the issue as this is more technical support now, but feel free to keep asking questions.

**Comment by MarVL92** [comment]
> For your error, @MarVL92 could you run a `pip freeze` and see what version of alpha_vantage you're on? I have tried your code and it was successful. However, you pointed out that the readme is outdated!
> 
> > Also when I check the documentation it says that ForeignExchange is not supporting pandas
> 
> Thank you! I'll add an issue for that.
> 
> To solve your initial question, the intraday endpoint does not return volume. In fact, none of the FX endpoints return volume. You can see the documentation for the intraday FX endpoint (and all endpoints) here:
> 
> https://www.alphavantage.co/documentation/#fx-intraday
> 
> I'm closing the issue as this is more technical support now, but feel free to keep asking questions.

Hi Patrick,

just ran the pip freeze and I am running alpha-vantage==2.0.0

I updated to alpha-vantage==2.0.0 but now I am running my code getting following error message: 
'TimeSeries' object has no attribute 'retries'

I checked the documentation and added retries to TimeSeries the following way, even though in the documentation its mentioned to be set to 5 by default:
ts = TimeSeries(key=open(key_path,'r').read(),retries='YOUR_RETRIES',output_format='pandas')
TypeError: __init__() got an unexpected keyword argument 'retries'

Maybe you can tell me which version of the alpha-vantage package your are running my code successfully on? 

Thanks and kind regards,
Marc

**Comment by roark52** [comment]
ForeignExchange 'pandas' works for me

**Comment by PatrickAlphaVantage** [comment]
I tried it on 2.0 and 2.1 and they both seemed to work ok for me. 

Maybe try uninstalling and reinstalling? 
`pip uninstall alpha_vantage`

For that error, could you just remove the retries variable? There is another issue that is looking to fix that.
