### ISSUE TITLE
Last minute missing

### ISSUE THREAD

**Issue by ssougnez** [RomelTorres/alpha_vantage#205]
I'm currently playing with the alpha vantage API and it seems pretty nice and fast so far.
I noticed something weird though. 
I'm trying to fetch a stock data with the following call: 

https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=ALNOV.PA&interval=1min&apikey=XYZ&outputsize=full

And here is the first entry of the array:

        "2020-04-23 11:29:00": {
            "1. open": "4.2050",
            "2. high": "4.2200",
            "3. low": "4.2000",
            "4. close": "4.2200",
            "5. volume": "28014"
        },

As you can see, this is the state of the stock 1 minute before closing, however, at closing, the final price is "4.21".

I also noticed that I can retrieve this price by using TIME_SERIES_DAILY but is seems odd that the last minute gets stripped from the INTRADAY report, isn't it?

**Comment by PatrickAlphaVantage** [comment]
Hmm, that is odd. Looks like an Alpha Vantage issue itself as opposed to this package. Thanks for pointing it out! I'll put a ticker in to fix it. It looks like it may only affect certain exchanges.

**Comment by PatrickAlphaVantage** [comment]
As this doesn't relate to the repo, but to AV themselves, I'll be closing this issue. Support will has added it to the queue.
