### ISSUE TITLE
BBands documentation incomplete

### ISSUE THREAD

**Issue by BWPanda** [RomelTorres/alpha_vantage#206]
The [documentation](https://alpha-vantage.readthedocs.io/en/latest/source/alpha_vantage.html#alpha_vantage.techindicators.TechIndicators.get_bbands) for `get_bbands()` seems to be missing the `time_period` argument (as seen in the [Technical Indicators](https://github.com/RomelTorres/alpha_vantage#technical-indicators) example.

That, or the example is wrong and needs updating...

**Comment by PatrickAlphaVantage** [comment]
Looks like the pypi package is messed up too in the documentation. Thanks for pointing this out!

**Comment by BWPanda** [comment]
Made a PR: https://github.com/RomelTorres/alpha_vantage/pull/207 Hope I did it right... Copied the text from: https://www.alphavantage.co/documentation/#bbands

**Comment by PatrickAlphaVantage** [comment]
Looks good! Thank you!
