### ISSUE TITLE
API call frequency error after 4 calls

### ISSUE THREAD

**Issue by thatsis** [RomelTorres/alpha_vantage#211]
Hi there,

I am making a get_daily call in a loop and on the 5th call, I am returned the ValueError: Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. 

I have a free key and I have definitely not exhausted the daily limit. Do others have the same issue?

**Comment by PatrickAlphaVantage** [comment]
> our standard API call frequency is 5 calls per minute

Try cutting back on the number of calls / minute. I'm going to close the case for now, but feel free to ask questions.

**Comment by thatsis** [comment]
Hi Patrick,
I am aware of the limitation. Did you read the original post though? On the 5th call breaks. The same code was running without issues this morning (GMT).

**Comment by BWPanda** [comment]
I'm experiencing the same thing.

In my code I have `api_count = 0` to start, then I increment it each time an API call is made (`api_count += 1`). I then have this code:

```python
if api_count >= 5:
    time.sleep(60)
    api_count = 0
```

But I get the 'API limit' error after only 4 calls. If I adjust my code to:

```python
if api_count >= 4:
    time.sleep(60)
    api_count = 0
```

Then it works as expected. Perhaps the limit was changed...? (seriously considering using Finnhub instead now)

**Comment by PatrickAlphaVantage** [comment]
Hmmm, I see what you're saying now actually. My mistake. I just tried it myself and only was able to get 4. Let me get back to you.

**Comment by PatrickAlphaVantage** [comment]
It's fixed! Are you two seeing it working properly on your end as well?

**Comment by BWPanda** [comment]
@PatrickAlphaVantage Nope, just tried it again now and still stopping after 4 calls...

**Comment by PatrickAlphaVantage** [comment]
Could you send me your code? I've just tried with a few different keys and was successful on the 5th attempt each time.

**Comment by BWPanda** [comment]
@PatrickAlphaVantage Ok, now it appears to be working.

Re. my code, I initialise `api_count` to `0` and increment it after each API call. So after 1 call, it's `1`, etc. Once it equals `4`, I've made 4 API calls, and that's when it stopped. But it appears whatever the fix was has propagated enough and now it's working for me for 5 calls.

**Comment by PatrickAlphaVantage** [comment]
Glad to hear it, and thank you for bringing this to our attention!
