### ISSUE TITLE
What exchanges are supported?

### ISSUE THREAD

**Issue by BWPanda** [RomelTorres/alpha_vantage#213]
Does anyone know what exchanges are supported by Alpha Vantage? I couldn't find any documentation about this...

I had a play with the API and found I could do this: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=ASX:NAB&apikey=[KEY] to get NAB's prices from the Australian Stock Exchange (ASX). However this is no longer working for me (or works intermittently). I'm wondering if ASX is officially supported...

**Comment by PatrickAlphaVantage** [comment]
Hi BWPanda, thanks for your questions. At the moment, there is no official list of supported exchanges. Generally the best way to get the ticker you want is in the format `ticker.exchange`. I've been trying different attempts to get your ticker but it looks like there might be something wrong. I've raised a support ticket with AV.

**Comment by BWPanda** [comment]
For the record, here's a list of ASX symbols I just tried and failed to get data for:

```
A2M | FPH | SHL
ALL | GMG | SUN
ANZ | IAG | SYD
APA | MQG | TCL
ASX | NAB | TLS
BHP | NCM | URW
BXB | QBE | WBC
CBA | REA | WES
COH | RHC | WOW
COL | RIO | WPL
CSL | RMD | XRO
FMG | SCG |
```
I tried both `ASX:[SYMBOL]` and `[SYMBOL].AX`...

**Comment by PatrickAlphaVantage** [comment]
This is now fixed! And for further tickers, I'd use `NAB.AX` for the symbol value. But your URL above should also work correctly again.

**Comment by alpaalpa** [comment]
It's broken again.  I'm more interested in getting quotes from the Hong Kong Stock Exchange though.

**Comment by deepakmeena635** [comment]
does it support NSE BSE ?

**Comment by Marwa-Abdelkader** [comment]
Yes, It's broken again! I can't get data to any other stock exchanges other than in USA, please help I need to get data of stocks on Egyptian Stock Exchange (EGX).
