### ISSUE TITLE
Getting "no return was given" error when trying to fetch stock data

### ISSUE THREAD

**Issue by lars-nordin** [RomelTorres/alpha_vantage#214]
How do I increase the logging to see what is going wrong?

Starting 4/29, I'm getting back the error below from the TimeSeries.get_daily call. Did the API change? 

    price_str = vantage_get_share_price('.INX')
      File "stock_notify.py", line 188, in vantage_get_share_price
    data, meta_data = ts.get_daily(symbol)
      File "/home/lars/.local/lib/python3.6/site-packages/alpha_vantage/alphavantage.py", line 161, in _format_wrapper
    self, *args, **kwargs)
      File "/home/lars/.local/lib/python3.6/site-packages/alpha_vantage/alphavantage.py", line 146, in _call_wrapper
    return self._handle_api_call(url), data_key, meta_data_key
      File "/home/lars/.local/lib/python3.6/site-packages/alpha_vantage/alphavantage.py", line 277, in _handle_api_call
      'Error getting data from the api, no return was given.')
      ValueError: Error getting data from the api, no return was given.

note "ts = alpha_vantage.timeseries.TimeSeries(...)"

**Comment by PatrickAlphaVantage** [comment]
Sadly, index data was never officially supported, stock data is what is officially supported. If they had index data it's considered a bonus. This is a good issue though on the logging front! This is what happens when the API returns a {} (a blank dict)

It probably makes sense to tell the user that it was a blank dict. What do you think?

**Comment by lars-nordin** [comment]
I agree. It would also be nice to show (or have a way to show) what was returned - in this case an empty dict.

**Comment by PatrickAlphaVantage** [comment]
Now that I think about it more, we could even just treat it as an invalid API call. A few enhancements for clarity could me made here.

**Comment by lars-nordin** [comment]
Other than computing the S&P500 from the constituent stocks, is there another way to query and get a index quote?
