### ISSUE TITLE
Intermittent wrong Alpha Vantage adjusted close values ?

### ISSUE THREAD

**Issue by PolVW** [RomelTorres/alpha_vantage#215]
Hello,
I see regular but intermittent issues with a wrong ADJUSTED CLOSE value. However it looks intermittent, it’s reproducible.

An example

https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=VIX&apikey=xxx&outputsize=full

![afbeelding](https://user-images.githubusercontent.com/64595342/80717381-2a562580-8af9-11ea-851d-cabf42ee0968.png)

![afbeelding](https://user-images.githubusercontent.com/64595342/80717409-317d3380-8af9-11ea-890e-a69b7bc770ad.png)
 
![afbeelding](https://user-images.githubusercontent.com/64595342/80717238-f5e26980-8af8-11ea-8c0d-f9b232f00429.png)

And one date with a wrong adjusted close value on 2004-12-31 with value 245397 !

Then I load the same page again in my browser:
 
 
![afbeelding](https://user-images.githubusercontent.com/64595342/80717524-55407980-8af9-11ea-8747-19ee70886975.png)

![afbeelding](https://user-images.githubusercontent.com/64595342/80717563-61c4d200-8af9-11ea-8914-1a2a5572da1c.png)

And we see for the same day a different result, and the result itself is completely out of a possible range.

As such, it shows to me that with the same request, I get different results for the ADJUSTED CLOSE, for the same day. As such, the issue is reproducible.

I'm I missing something here?
Thanks in advance,

**Comment by PatrickAlphaVantage** [comment]
Yeah that's borderline comical how out of range that is. It looks like there is some issue with how the splits are working there. I've raised a ticket with AV. Thank you

**Comment by PatrickAlphaVantage** [comment]
This has been fixed! Thank you for a great issue. 
![Uploading Screen Shot 2020-05-04 at 6.42.10 PM.png…]()

**Comment by PolVW** [comment]
Hi, 

thank you.
Can you please verify this sample I found with a, I presume, wrong close value after a SPLIT for ticker ISRG

![afbeelding](https://user-images.githubusercontent.com/64595342/81315823-15ded380-908b-11ea-93d4-772638169752.png)

We see no correct SPLIT correction ?

This sample is a correct one: WDP.BR 

![afbeelding](https://user-images.githubusercontent.com/64595342/81315929-3dce3700-908b-11ea-9c0a-759f4bf6ae7a.png)

So, it's again an intermittent issue, but I guess related to the above fix.

Thanks in advance
