### ISSUE TITLE
Question about API Throughput

### ISSUE THREAD

**Issue by shjoshi95** [RomelTorres/alpha_vantage#216]
Hi, 

I currently have a sequential workflow where I call ts.get_intraday() with a time.sleep(0.666) between calls. This should ensure I make 90 requests per minute worst case, and I have an AV key for 120 requests/minute. However, when I create a second TimeSeries client and make a single ts.get_daily_adjusted() request, I am always rate limited. Do you know of any limitations in performance when using a synchronous design or when using multiple clients with the same key? Would parallel execution help?

**Comment by shjoshi95** [comment]
Actually, found a bug on my side, and the issue can be closed. But out of curiosity, if you have any insights on API performance for sync vs async design patterns, I would love to hear your thoughts.

**Comment by PatrickAlphaVantage** [comment]
I have actually written an article on that myself! It's still being critiqued by the editor, and we have just introduced async design into the API. Here is the draft (to be posted soon!) https://medium.com/better-programming/which-should-you-use-asynchronous-programming-or-multi-threading-7435ec9adc8e

Basically, for something like this that has a lot of I/O (like I/O) async is really good. If you have a lot of CPU power, then you can also multithread. The simplest version to do that with this repo is something like this:

```python
import asyncio
from alpha_vantage.async_support.timeseries import TimeSeries
symbols = ['AAPL', 'GOOG', 'TSLA', 'MSFT']
async def get_data(symbol):
    ts = TimeSeries()
    data, _ = await ts.get_quote_endpoint(symbol)
    await ts.close()
    return data
loop = asyncio.get_event_loop()
tasks = [get_data(symbol) for symbol in symbols]
group1 = asyncio.gather(*tasks)
results = loop.run_until_complete(group1)
print(results)
```
This async calls a list of symbols you'd like. You can also check out my multithreading tutorial here:
https://medium.com/alpha-vantage/data-is-taking-to-long-to-get-back-d48e3bf8f59b

Does that help?

**Comment by shjoshi95** [comment]
> I have actually written an article on that myself! It's still being critiqued by the editor, and we have just introduced async design into the API. Here is the draft (to be posted soon!) https://medium.com/better-programming/which-should-you-use-asynchronous-programming-or-multi-threading-7435ec9adc8e
> 
> Basically, for something like this that has a lot of I/O (like I/O) async is really good. If you have a lot of CPU power, then you can also multithread. The simplest version to do that with this repo is something like this:
> 
> ```python
> import asyncio
> from alpha_vantage.async_support.timeseries import TimeSeries
> symbols = ['AAPL', 'GOOG', 'TSLA', 'MSFT']
> async def get_data(symbol):
>     ts = TimeSeries()
>     data, _ = await ts.get_quote_endpoint(symbol)
>     await ts.close()
>     return data
> loop = asyncio.get_event_loop()
> tasks = [get_data(symbol) for symbol in symbols]
> group1 = asyncio.gather(*tasks)
> results = loop.run_until_complete(group1)
> print(results)
> ```
> 
> This async calls a list of symbols you'd like. You can also check out my multithreading tutorial here:
> https://medium.com/alpha-vantage/data-is-taking-to-long-to-get-back-d48e3bf8f59b
> 
> Does that help?

Yea, this was very clear! Thanks for posting the link too. I regularly use the async/await pattern for other types of platforms, and am just starting to explore/design use cases in the finance realm.
