### ISSUE TITLE
SectorPerformances.get_sector() automatically removes digits from column names

### ISSUE THREAD

**Issue by davft** [RomelTorres/alpha_vantage#219]
```
from alpha_vantage.sectorperformance import SectorPerformances

sp = SectorPerformances(key="YOUR_KEY_HERE", output_format="pandas")
data, meta_data = sp.get_sector()
data.columns
```

> Out[6]: 
Index(['Rank A: Real-Time Performance', 'Rank B: Day Performance',
       'Rank C: Day Performance', 'Rank D: Month Performance',
       'Rank E: Month Performance', 'Rank F: Year-to-Date (YTD) Performance',
       'Rank G: Year Performance', 'Rank H: Year Performance',
       'Rank I: Year Performance', 'Rank J: Year Performance'],
      dtype='object')

the output is different from the expected (https://www.alphavantage.co/query?function=SECTOR&apikey=demo) I think the issues is in `AlphaVantage._output_format_sector()`, precisely here:
```
 # Rename columns to have a nicer name
 col_names = [re.sub(r'\d+.', '', name).strip(' ')
    for name in list(data_pandas)]
```
I am running Python 3.8.2 on a MacOS.
thank you

**Comment by PatrickAlphaVantage** [comment]
Thanks @davft, it looks like this was intentional to change it to remove the numbers. This would be a breaking fix to change the output format of the sector performance now. 

Looking for some feedback from you and the rest of the community. Do you think it should be exactly the return of AV?

**Comment by davft** [comment]
thanks for the answer Patrick! I started using `alpha_vantage` recently, and I though this was unexpected. If it was intentional, than I'll use it accordingly. Have a great day.
