### ISSUE TITLE
Alpha Vantage APIs stopped working

### ISSUE THREAD

**Issue by Hemen** [RomelTorres/alpha_vantage#22]
Can anyone let me know when this is going to be start? Even website not loading.

**Comment by RomelTorres** [comment]
hey @Haman, I don't know I am going to write to them.

**Comment by Hemen** [comment]
I think server is not working right now!! Do you know when it is going to start?

**Comment by RomelTorres** [comment]
@Hemen No Idea I just contacted them and am waiting for their reply.

**Comment by Hemen** [comment]
Okay please let me when you get hear back. Thank you!

**Comment by SteffenNa** [comment]
It is working again.

**Comment by pratikgadoya** [comment]
It's not working for NSE symbol like L&TFH. Can you please let me know how can I get data for this?

**Comment by nitaionutandreigit** [comment]
Is Alphavantage API down? FX_MONTHLY is returning error every time. Even the demo queries: https://www.alphavantage.co/query?function=FX_MONTHLY&from_symbol=EUR&to_symbol=USD&apikey=demo
