### ISSUE TITLE
Invalid API Call - ^BVSP Index

### ISSUE THREAD

**Issue by vbrenck** [RomelTorres/alpha_vantage#221]
I'm getting an "Invalid API call" error when trying to retrieve information about IBOVESPA index (^BVSP) on get_daily_adjusted and get_weekly_adjusted methods of Timeseries (the non adjusted produce the error as well) . I have been using this exact method and symbol for awhile, but it stopped working on last monday (april 27th). The weird thing is that the symbol ^BVSP is still working in the intraday API calls (Timeseries.get_intraday).

**Comment by PatrickAlphaVantage** [comment]
Stock, US ETFs, FX, and Crypto data are fully supported by AV. Index data is considered a bonus if the ticker happens to exist on the platform. Sorry for any inconvenience.
