### ISSUE TITLE
How to add tickers on the Alpha Vantage list ?

### ISSUE THREAD

**Issue by PolVW** [RomelTorres/alpha_vantage#222]
When you ask Alpha Vantage a non existent ticker, you receive the simple "invalid API call".

There exist the symbol search command to llok up the ticker list:
https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=BA&apikey=demo

Can you use wildcards in this search field?

And if so, can I use a wildcard, example "*" for foreign markets like HK, example "0*.HK" would give a list for alle companies starting with a zero in Hong Kong?

Last but not least, is there a procedure to ask Alpha Vantage that they could load the missing ticker, example the one you looking for but does not exist yet.

Thanks in advance

**Comment by PatrickAlphaVantage** [comment]
Hi PolVW!
1. At the moment, wildcards are not supported
2. To ask for an additional ticker, you can send an email to support@alphavantage.co

**Comment by PolVW** [comment]
Thank you Patrick
