### ISSUE TITLE
Invalid API Calls Error handling

### ISSUE THREAD

**Issue by riodda** [RomelTorres/alpha_vantage#223]
Hi, thanks for your hard work ! I really apreciate it ! I amworking on a script that will interactively look for some data on a list of tickers. I've donwloaded the .csv list for the digital currencies and i've noticed that several of the currencies are returning an error from the API, i have reported to Alpha but i think that i would be nice to implement and api error handling and return a code in case of api error to avoid that the scprit don't halt.

if you look at their digital_currency_list.csv avilable in the docs the first item in the list is 1ST but if i call:

`data, meta_data = cc.get_digital_currency_daily(symbol='1ST', market='EUR')`

i have 
`ValueError: Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for DIGITAL_CURRENCY_DAILY.`

**Comment by PatrickAlphaVantage** [comment]
Thanks Riodda!
Hmm... It looks like this is a missing ticker to bring up to AV support! 

The error you're getting is the error message. If you want your script to not halt, you can just add a try catch. Something like:

```
from alpha_vantage.timeseries import TimeSeries
symbols = ['AAPL', 'GOOG', 'TSLA', 'MSFT', 'asldkfjalskdjfaskdljflasdfjlasdflkajsdfjlasdf']
results = []
ts = TimeSeries()
for symbol in symbols:
    try:
        results.append(ts.get_quote_endpoint(symbol)[0]['05. price'])
    except:
        pass
print(results)
```

This will just keep going down the list, and if an error occurs, it will not break

**Comment by PatrickAlphaVantage** [comment]
Feel free to follow up with questions.
