### ISSUE TITLE
London Stock Exchange ETFs issue

### ISSUE THREAD

**Issue by Nishan-Pradhan** [RomelTorres/alpha_vantage#224]
It looks as if ETFs listed in London such as VUSA.LON, CUKX.LON, IUSP.LON, are not saving end of day adjusted close prices over the last month. It seems like something has gone wrong on Apr 3rd 2020 and has not been corrected since.

The current day close price is correct however the figure does not seem to be saving historically.

Thanks for the help.

**Comment by PatrickAlphaVantage** [comment]
Only US ETFs are supported at the moment. London ETFs are considered bonus. Sorry for any inconvenience :(
