### ISSUE TITLE
Cryptocurrency data unavailable

### ISSUE THREAD

**Issue by shjoshi95** [RomelTorres/alpha_vantage#225]
When querying monthly data for quite a few of the lesser known cryptocurrencies such as MANA, GNT, and KNC, I get the following exception from AV:

Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for DIGITAL_CURRENCY_MONTHLY.

However, these cryptos are on the [digital currency list](https://www.alphavantage.co/digital_currency_list/)...any idea for why this crypto data is not available?

**Comment by PatrickAlphaVantage** [comment]
Hmmm... This looks like something we will have to send to support. I'll send support an email.

**Comment by shjoshi95** [comment]
> Hmmm... This looks like something we will have to send to support. I'll send support an email.

Cool thanks, I also reached out to them and they said its an issue with the upstream data provider. Additionally, I found that for the crypto data, the volume for BTC, for example, has been the same all day today from 1PM EST till even 8:25PM EST (which is after the 12AM midnight UTC time at which crypto data is supposed to be updated on the AV backend).

**Comment by shjoshi95** [comment]
Nevermind, the issue with timing is related to a data center outage that is an outlier event. But it would still be nice for the other tickers to become available, and for real-time/intraday crypto price quotes to become available, to be in parity with equity data.
