### ISSUE TITLE
Alpha Vantage, intermittent wrong close values after a SPLIT

### ISSUE THREAD

**Issue by PolVW** [RomelTorres/alpha_vantage#226]
Hi,

after the fix of case 215, I noticed a different behavior after a SPLIT in some CLOSE values.

Can you please verify these two samples, one with a correction of the past CLOSE values and one without the correction. 

First sample ISRG without the SPLIT correction:
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&apikey=xxx&outputsize=full&symbol=ISRG

![afbeelding](https://user-images.githubusercontent.com/64595342/81475733-43a05580-920e-11ea-9339-18e88b7bdfb0.png)

This sample is a correct one: WDP.BR
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&apikey=xxx&outputsize=full&symbol=WDP.BR

![afbeelding](https://user-images.githubusercontent.com/64595342/81475747-51ee7180-920e-11ea-8f5a-6f07edc39554.png)

As such, it look like an intermittent issue.

Thanks in advance

**Comment by PatrickAlphaVantage** [comment]
Hmmm.... Looks like another issue for the support team to look into. I'll send support a ticket for this too!

**Comment by PolVW** [comment]
Thank you

**Comment by SteveAlphaVantage** [comment]
Closing the issue as we have established communication with the user via support.
