### ISSUE TITLE
Trouble pulling Tech Indicators data

### ISSUE THREAD

**Issue by BabyJakes** [RomelTorres/alpha_vantage#228]
Hi, I get the following error message when I try to pull for MACD data: 'TechIndicators' object has no attribute 'get_MACD'

I also get the same error for VWAP, EMA, RSI ... is there something significant I am missing?  Thank you for your help -- Code below:

`import pandas as pd

from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.techindicators import TechIndicators
from alpha_vantage.sectorperformance import SectorPerformances
from matplotlib.pyplot import figure
import matplotlib.pyplot as plt

# Personal Key for Alpha Vantage
key = 'XXXXXXX'

#Get Technical Indicators
ti_MACD = TechIndicators(key,output_format='pandas')
GOOG_MACD, GOOG_meta_MACD = ti_MACD.get_MACD(symbol='GOOG',interval='1min',series_type=close,fastperiod=12,slowperiod=26,signalperiod=9)`

**Comment by PatrickAlphaVantage** [comment]
Hi @BabyJakes!

```get_macd``` and ```get_MACD``` are different, methods are case sensitive.

Also you need quotes around `close`

Here is the adjusted working code


```
import pandas as pd

from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.techindicators import TechIndicators
from alpha_vantage.sectorperformance import SectorPerformances
from matplotlib.pyplot import figure
import matplotlib.pyplot as plt

key = "XXXXXX"

#Get Technical Indicators
ti_MACD = TechIndicators(key=key, output_format='pandas')
GOOG_MACD, GOOG_meta_MACD = ti_MACD.get_macd(symbol='GOOG',interval='1min',series_type="close",fastperiod=12,slowperiod=26,signalperiod=9)

print(GOOG_MACD)
```

**Comment by BabyJakes** [comment]
Ah, thank you!  Baby steps over here :)
