### ISSUE TITLE
FX_Intraday / Daily not working, right?

### ISSUE THREAD

**Issue by Matog666** [RomelTorres/alpha_vantage#230]
Hello kids, 
I had an invalid API call for both FX intraday and daily.. I could pull the rate but no luck with this one
data, meta_data = cc.get_currency_exchange_intraday(from_symbol='EUR',to_symbol='USD', outputsize='compact')
Just to be sure I didn't fuck up I went to the docs and tried the demo, same error
https://www.alphavantage.co/query?function=FX_INTRADAY&from_symbol=EUR&to_symbol=USD&interval=5min&apikey=demo

Thanks baby

**Comment by PatrickAlphaVantage** [comment]
Hi Matog666,

It looks like there is an issue with the endpoint at the moment, I'll put in a ticket!

**Comment by SteveAlphaVantage** [comment]
The issue has been resolved. Closing.
