### ISSUE TITLE
CryptoCurrencies.get_digital_currency_exchange_rate doesnt work

### ISSUE THREAD

**Issue by mariohanser** [RomelTorres/alpha_vantage#231]
This funtion sends the api call: 

https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&symbol=BTC&market=EUR&apikey=XXXX&datatype=json

The right one would be:

https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=BTC&to_currency=EUR&apikey=XXXX&datatype=json

To fix this the keyword arguments of CryptoCurrencies.get_digital_currency_exchange_rate should be from_currency and to_currency (line 63 in cryptocurrencys.py)

Then the return value should be changed to:
FUNCTION_KEY, 'Realtime Currency Exchange Rate', None

But im not sure with the Meta_data = None, I just couldnt figure out a secound entry in the dict.

With this changes it works for the default Outputformat but not for output_format = 'pamdas'. Maybe anyone can fix this completely.

**Comment by mariohanser** [comment]
Ah it'll works also for pandas then

**Comment by PatrickAlphaVantage** [comment]
Be sure to hide your keys when creating issues! The meta_data = None because this endpoint only returns a single dict, whereas a lot of the other endpoints return a tuple. 

Thanks for adding this issue!

**Comment by rxmxn** [comment]
@mariohanser use this function instead https://github.com/RomelTorres/alpha_vantage#foreign-exchange-fx
It's the same thing, but it's just under foreign-exhange.
