### ISSUE TITLE
Not able to fetch intra day quotes for indian stock market

### ISSUE THREAD

**Issue by JagadeeshBoyidi** [RomelTorres/alpha_vantage#233]
Code:
 ts = TimeSeries(key='key', output_format='pandas')
  intra, meta_data = ts.get_intraday(symbol='HDFC.NS',interval='1min', outputsize='full')

Error:
/usr/local/lib/python3.6/dist-packages/alpha_vantage/alphavantage.py in _handle_api_call(self, url)
    333             if not json_response:
    334                 raise ValueError(
--> 335                     'Error getting data from the api, no return was given.')
    336             elif "Error Message" in json_response:
    337                 raise ValueError(json_response["Error Message"])

ValueError: Error getting data from the api, no return was given.

**Comment by josephsr** [comment]
It used to work with NSE:HDFC. Only the recent past it has stopped working

**Comment by sabirjana** [comment]
I am too facing the issue, not able to fetch data for India tickers.

**Comment by kbsudhir** [comment]
Yes, I am also facing the same issue & this problem started for me last Thursday 11th June. I have written to support@alphavantage.co  on 12th June, but no response till now.

Requesting Alphavantage team to please provide a resolution for this issue.

**Comment by PatrickAlphaVantage** [comment]
At the moment, there is an issue with the AV API with global tickers. We apologize for the inconvenience.

**Comment by PatrickAlphaVantage** [comment]
Will be closing since this is an issue with AV and not the repo itself.
