### ISSUE TITLE
[Question] Are the api keys required for all requests? 

### ISSUE THREAD

**Issue by rafad900** [RomelTorres/alpha_vantage#234]
Hello! 
I was messing around with the functions in TimeSeries and on one of them I accidentally deleted the last character of my key but it still worked. I tried this a couple more times with all the functions and with deleting more characters and they all seemed to work. 
I'm guessing this is something with API itself or maybe I'm just doing something wrong. 
I took one of the example requests that it gives on the documentation 

`https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=RANDOM`

and just changed`apikey=demo to apikey=RANDOM`

**Comment by SteveAlphaVantage** [comment]
IP addresses and API key are used in combination to determine the rate limits. Thanks for using Alpha Vantage!
