### ISSUE TITLE
[Enhancement] Would creating a more dedicated GUI be of any interest? 

### ISSUE THREAD

**Issue by rafad900** [RomelTorres/alpha_vantage#235]
As a developer, I like to code all the stocks, exchanges, and stuff that I need, however, some of my college friends in business and economics don't know, or care, to learn python or anything coding related but they find the wrapper really interesting. Would there be a chance of making a more robust GUI for the general public?

**Comment by PatrickAlphaVantage** [comment]
This is an open sourced project, so if someone wants to make a GUI here, they are free to do so :)

As far as Alpha Vantage goes, I'm not sure, but I think you make a great point about how a lot of non-technical people would love a tool like this.
