### ISSUE TITLE
ValueError: Error getting data from the api, no return was given. while quering NSE 1 min get intraday data

### ISSUE THREAD

**Issue by raghurajpandya** [RomelTorres/alpha_vantage#236]
I get a ValueError: Error getting data from the api, no return was given.

While querying the following:
data, meta_data = ts.get_intraday(symbol='NSE:RELIANCE',interval='10min', outputsize='full')

Whereas the following works fine: 
data, meta_data = ts.get_intraday(symbol='MSFT',interval='1min', outputsize='full')

Is NSE supported by Alpha Vantage.. first query worked until last month. 
What is the causing the error and is there a fix?

**Comment by PatrickAlphaVantage** [comment]
There is currently an issue with the Alpha Vantage API with global tickers. We apologize for the inconvenience.
