### ISSUE TITLE
Alpha Vantage API return empty results [bug?]

### ISSUE THREAD

**Issue by lorenzo-gabrielli** [RomelTorres/alpha_vantage#237]
Dear,

The following query does not work anymore (returns an empty dictionary).
Do you introduce some restrictions for Italian stocks?
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&outputsize=full&symbol=ENI.MI&apikey=

Best

Lorenzo

**Comment by samgoodey** [comment]
Can confirm that we're also seeing this issue when querying the London stock exchange for multiple businesses

https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=BDEV.LON&apikey=

**Comment by lorenzo-gabrielli** [comment]
Not being alone consoles me :-)

Lorenzo

Skype : lorenzo.gabrielli




Il giorno ven 26 giu 2020 alle ore 09:03 Sam Goodey <
notifications@github.com> ha scritto:

**Comment by lorenzo-gabrielli** [comment]
Do you think this problem will be solved?
Lorenzo

Skype : lorenzo.gabrielli




Il giorno ven 26 giu 2020 alle ore 09:03 Sam Goodey <
notifications@github.com> ha scritto:

**Comment by davshoward** [comment]
Same here for London stocks.

**Comment by BaankeyBihari** [comment]
I think the issue is with alpha vantage API rather than with the python package here

**Comment by SteveAlphaVantage** [comment]
Thanks for the report, Sam, Lorenzo, & team! As @BaankeyBihari suggested, the behavior may be beyond the scope of the python library. The engineering team is on point for a fix. In the meantime, please feel free to write to support@alphavantage.co 

Many thanks again!
