### ISSUE TITLE
Fetch XAUUSD

### ISSUE THREAD

**Issue by sword134** [RomelTorres/alpha_vantage#238]
Hello, I'm trying to fetch the XAUUSD via the foreign exchange but it throws the following error:
`ValueError: Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for FX_DAILY.`

My code is as follows:
tsXAU = ForeignExchange(key='XXXXXXXXXXXXXX', output_format='pandas', indexing_type='date')
dataXAU, meta_dataXAU = tsXAU.get_currency_exchange_daily(from_symbol='XAU', to_symbol='USD', outputsize='full')

**Comment by BaankeyBihari** [comment]
Broken API, can you check in your browser
<code>https://www.alphavantage.co/query?function=FX_DAILY&from_symbol=XAU&to_symbol=USD&outputsize=full&apikey=XXXXXXXXXXXX</code>

I think there are multiple API failure today on alphavantage

**Comment by SteveAlphaVantage** [comment]
XAU is a commodity rather than a forex symbol, and is not in scope of the forex time series APIs. That being said, the product team is examining if this is something to be added in a future release. Will keep you posted.

**Comment by videni** [comment]
@sword134  how this is resolved? what is the correct way to get XAUUSD data? I am using pandas-datareader.

**Comment by dorienh** [comment]
Wondering about this.
