### ISSUE TITLE
Digital Currency: Units of 'Volume' and 'Market Cap'

### ISSUE THREAD

**Issue by ajayrlogesh** [RomelTorres/alpha_vantage#239]
I am using this Python Wrapper for Alpha Vantage API and find it very helpful. For digital currencies, the units of volume and market cap are bit confusing. Following are the inputs and output.

**Input:**
```
cc = CryptoCurrencies(key='MY-API-KEY', output_format='pandas')
data, meta_data = cc.get_digital_currency_daily(symbol='BTC', market='EUR')
data.head()
```
**Output:**
```
{'1a. open (EUR)': {Timestamp('2020-06-28 00:00:00'): 8026.0872},
 '1b. open (USD)': {Timestamp('2020-06-28 00:00:00'): 9012.0},
 '2a. high (EUR)': {Timestamp('2020-06-28 00:00:00'): 8185.5046},
 '2b. high (USD)': {Timestamp('2020-06-28 00:00:00'): 9191.0},
 '3a. low (EUR)': {Timestamp('2020-06-28 00:00:00'): 7969.142236},
 '3b. low (USD)': {Timestamp('2020-06-28 00:00:00'): 8948.06},
 '4a. close (EUR)': {Timestamp('2020-06-28 00:00:00'): 8119.02131},
 '4b. close (USD)': {Timestamp('2020-06-28 00:00:00'): 9116.35},
 '5. volume': {Timestamp('2020-06-28 00:00:00'): 30688.176421},
 '6. market cap (USD)': {Timestamp('2020-06-28 00:00:00'): 30688.176421}}
```
**Inference:**
Here, the values of volume and market cap (USD) are same. I doubt whether the units for market cap is really USD because the value seems to be really low for a day. In another try, I changed market currency to USD and checked the output. The values of volume and market cap are still the same (30688.176421). I suppose that the volume and market cap are not same. 

**Question:**
In this case, could 'volume' be the 'trading volume of Symbol currency (here BTC)' and the value of market cap is wrong? Do anyone has any idea about this?

_PS: I have contacted AlphaVantage about this ambiguity. There is no response._

**Comment by SteveAlphaVantage** [comment]
Thanks Ajay for the report. The market cap is a “legacy” field from an earlier version of the crypto API, and we plan to either update or deprecate the field in the near future. We will keep the other fields (including trading volume) as is to ensure backward compatibility.
