### ISSUE TITLE
ModuleNotFoundError: No module named 'alpha_vantage.timeseries'

### ISSUE THREAD

**Issue by vikyaiyer** [RomelTorres/alpha_vantage#24]
Successfully installed alpha-vantage-1.3.6 nose-1.3.7 pandas-0.20.3 pytz-2017.2 simplejson-3.11.1 but gives error while using!!
![screenshot 223](https://user-images.githubusercontent.com/12629498/32008356-a6bf5c94-b9c9-11e7-915b-250d5ca464f5.png)

**Comment by RomelTorres** [comment]
Hi @vikyaiyer I sadly don't have a Windows computer to test it. Can you try it in a virtual environment?

**Comment by RomelTorres** [comment]
Hi @vikyaiyer. did you manage to solve the issue?

**Comment by vikyaiyer** [comment]
Sadly I downgraded python to 3.5 version and using the library.
