### ISSUE TITLE
Warnings: Alpha Vantage is an unlicensed vendor

### ISSUE THREAD

**Issue by myxfinance223** [RomelTorres/alpha_vantage#243]
Hi,

Just want to bring it to you guys' attention that Alpha Vange is distributing market data **illegally** and legal actions have been taken against the company. I suggest you guys to switch to another provider immediately to avoid service disruption. 

Original proof of illegal activity can be found here: https://www.reddit.com/r/algotrading/comments/hnxoy6/beware_alphavantage_is_not_a_licensed_provider/

The following market data has disappeared due to legal actions and more will be coming soon:
+ US real-time data (now they only have end of day data)
+ LSE
+ NSE
+ ASX
+ Torronto stock exchange (TSX)
+ All Nordic exchanges
+ All Baltic exchanges
+ Moscow stock exchange
+ Istanbul stock exchange

I'm just as disappointed as all of you that a great idea was so poorly executed and based on entirely illegal foundation to begin with.

 I understand there are people from Alpha Vantage working in this repo so feel free to defend yourself and please disclose your data source if it's not Yahoo Finance. Which authorized vendors or direct exchange connections do you use to get the data ? Is it true that the exchanges got to you guys ?

**Comment by PatrickAlphaC** [comment]
Sigh. This is not proof. This is a reddit screenshot of an email. Alpha Vantage does not work with real-time data from these vendors. Most when often a brand new user signs up for github and posts something like this attacking another, they are from finnhub who actually IS illegally distributing data.

**Comment by myxfinance223** [comment]
lol. Closing the issue. Don't worry I will make sure the whole community know it.

**Comment by myxfinance223** [comment]
I have cached this page. Let's make sure it is recorded that Alpha Vantage instead of defending themselves or acknowledging their wrongdoing, chose to silence my voice by deleting the comment and blaming their competitor. I'm sure the whole community would love that from their provider :)

**Comment by PatrickAlphaC** [comment]
This is an open sourced project. Please, if you have issues, please send an inquiry to support@alphavantage.co, and/or place a formal complaint with your lawyer.
