### ISSUE TITLE
Current price is not being shown.

### ISSUE THREAD

**Issue by Samar-080301** [RomelTorres/alpha_vantage#247]
I wrote the following code.
```
from alpha_vantage.timeseries import TimeSeries
import pandas as pd
api_key='******************'
ts = TimeSeries(key=api_key, output_format = 'pandas')
data, meta_data = ts.get_intraday(symbol = 'MSFT',interval = '1min', outputsize = 'full')
print(data)
```
But the latest price that was shown, was of `2020-07-20 20:00:00` how can I get the live price? Please help me!

**Comment by PatrickAlphaC** [comment]
MSFT and a few other tickers are now one day lagging. Check the alpha vantage docs: https://www.alphavantage.co/documentation/
