### ISSUE TITLE
Does not recognise rate limiting related errors

### ISSUE THREAD

**Issue by Wilm0r** [RomelTorres/alpha_vantage#248]
It is quite easy for a batch job to run into Alpha Vantage's rate limits. Frustratingly AV don't just return a HTTP non-200 error so it appears that the only way to recognise this as the caller would be to interpret the error message, which is currently:

```
Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
```

Could the library try to recognise this error and possibly automatically retry after something like 12 seconds?

(Also is it worth requesting AV folks for better machine-understandable errors on this? I have no idea how open they are to bug reports like this..)

**Comment by PatrickAlphaC** [comment]
I agree. I think this would be a good improvement. How do you think this would look? Maybe we just have the error be non-200? We ignore the AV error?

**Comment by Wilm0r** [comment]
Oh, ah yes if you can address this on the AV side that would be ideal!

I believe the HTTP 429 error is meant for this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429 . A `Retry-After` header would be especially useful if possible, so that the caller will know when they've hit the 500 a day limit for example, and may need to wait for about, hmm, 80k seconds :)

**Comment by PatrickAlphaC** [comment]
I'll ping @SteveAlphaVantage on this. Otherwise we can just fix it in this open sourced code ourselves.

**Comment by StevenQu** [comment]
+1 This would be very useful when use want to do some batch daily cron jobs that would be throttled by AlphaAdvantage's rate limit per minute.

**Comment by dnlhpp** [comment]
@PatrickAlphaC Is there new information regarding the rate limiting information in the headers and response code? Would it be better to contact AlphaVantage support myself? Returning code `429` and including [rate limit related information in the headers](https://tools.ietf.org/id/draft-polli-ratelimit-headers-00.html#:~:text=The%20RateLimit%2DLimit%20response%20header,it%20MAY%20not%20be%20served.) would be the best way to go.

**Comment by PatrickAlphaC** [comment]
It might be better to ping AV, but this wouldn't be that hard to code into this repo.

**Comment by dnlhpp** [comment]
I'll ask then if this feature is upcoming and in the meantime a temporary solution should suffice.

Have you outlined any implementation details of such a feature?

Off the top of my head I would block the call until the rate-limit has cooled off with a maximum wait time to avoid waiting up to 22 hours in the worst case.

Do you know if the error message is similar when using higher tier API keys?

**Comment by AlphaVantageSupport** [comment]
@dhoeppe, feel free to reach out to support@alphavantage.co regarding the feature timeline. 

On the error message, below is the verbatim text for free and paid plans: 

Free Tier:
```
{
    "Note": "Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency."
}

```
Paid Tiers:
```
{
    "Information": "Thank you for using Alpha Vantage! Please contact premium@alphavantage.co if you are targeting a higher API call volume."
}
```

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.
