### ISSUE TITLE
VIX ticker has stopped working?

### ISSUE THREAD

**Issue by sword134** [RomelTorres/alpha_vantage#250]
Hello,
Around 2 months ago I used `dataVIX1, meta_dataVIX = tsVIX.get_daily(symbol="VIX", outputsize='full')` for fetching VIX data, it now seems that the ticker is no longer active, using ^VIX doesn't work either. So what is the new symbol for VIX?

**Comment by SteveAlphaVantage** [comment]
@sword134, the function you are using (time series daily) is for stocks and ETFs. However, VIX is an index and is therefore not in scope of the API coverage. Thanks!
