### ISSUE TITLE
Where are the fundamental data methods?

### ISSUE THREAD

**Issue by ruipiresc** [RomelTorres/alpha_vantage#251]

**Comment by Achilles718611** [comment]
I can't find methods to get fundamental data from Alpha Vantage Python library.
![image](https://user-images.githubusercontent.com/31845458/90867567-29a70f00-e3c8-11ea-8665-12b99b80604a.png)

**Comment by FreddoIsHere** [comment]
You can get it by using the _call_api_on_func in alpha_vatange.alpha_vantage and the respective keys "CASH_FLOW" etc.

**Comment by Achilles718611** [comment]
Can you add sample code here?

**Comment by nodee** [comment]
Is there more complete example of how to use _call_api_on_func mentioned above?

**Comment by uebenes** [comment]
seems with commit 4be2027, the fundamentals have been submittend to the dev branch - many thanks!

**Comment by PatrickAlphaC** [comment]
Feel free to install from the dev branch. If you get an issue there, report it back here :)

**Comment by foxy0** [comment]
Thank you for adding the fundamental methods. However, I have a slight issue. When I try to retrieve the company overview, I get KeyError: None. The following code worked fine for other methods:

`fd = FundamentalData(key=apikey, output_format='pandas')
df, metadata = fd.get_company_overview(symbol='IBM')`

**Comment by Biatrixia155** [comment]
I am not sure if I am doing something wrong but I am trying to import the FundamentalData methods as shown below. and receiving an error. 
from alpha_vantage.fundamentaldata import FundamentalData

Error: No module named 'alpha_vantage.fundamentaldata'

I also upgraded the alpha_vantage on Jupyter and in my Command prompt pip install --upgrade alpha_vantage. 

I am fairly new to coding, and would appreciate if someone could please tell me if I am doing this wrong. Thank you.

**Comment by nodee** [comment]
@Biatrixia155 it is on the develop branch, I've used this to get access to it:
pip install git+git://github.com/RomelTorres/alpha_vantage.git@develop --upgrade

That being said, I can't get it to work, I get 'ValueError - Error getting data from the api, no return value given'

`from alpha_vantage.fundamentaldata import FundamentalData
....
fd = FundamentalData(key=self.API_KEY)
....
data = fd.get_company_overview(symbol=ticker)`

**Comment by nodee** [comment]
Does the fundamentals part of the API require different symbol formatting? I can use for example `'LON:RMG'` when requesting historic prices from the TimeSeries part but the same symbol passed to the FundamentalData part returns no data/Value Error.

**Comment by Achilles718611** [comment]
When new verison will be released with fundamental data functions?

https://pypi.org/project/alpha-vantage/

**Comment by Biatrixia155** [comment]
I just ended up using financialmodelingprep api for all of my fundamental data instead. It's free too.

**Comment by YoungGohardt** [comment]
> I am not sure if I am doing something wrong but I am trying to import the FundamentalData methods as shown below. and receiving an error.
> from alpha_vantage.fundamentaldata import FundamentalData
> 
> Error: No module named 'alpha_vantage.fundamentaldata'
> 
> I also upgraded the alpha_vantage on Jupyter and in my Command prompt pip install --upgrade alpha_vantage.
> 
> I am fairly new to coding, and would appreciate if someone could please tell me if I am doing this wrong. Thank you.

I have seen the same behavior, when installing it with the `pip install alpha_vantage` command. For some reason the fundamentaldata.py is not installed. If you use the git clone for installation, fundamentaldata.py comes with it:
`git clone https://github.com/RomelTorres/alpha_vantage.git` <br> 
`pip install -e alpha_vantage' 

However, I still have the issue mentioned by @foxy0 with the `KeyError: None`

**Comment by jevinjay** [comment]
@YoungGohardt 

it looks like it's nested in a second alpha_vantage folder. Try this:

`from alpha_vantage.alpha_vantage.fundamentaldata import FundamentalData`

**Comment by AlphaVantageSupport** [comment]
Closing - fundamental data APIs have been added in the latest release.
