### ISSUE TITLE
Accounting for stock splits?

### ISSUE THREAD

**Issue by alejandroarmas** [RomelTorres/alpha_vantage#252]
Hello @PatrickAlphaC , 

Thanks for the library, its great so far. I was wondering how do I work around stock splits, is this accounted for in your wrapper? If not, what recommendation would you have if I wanted to pull and view historical data. For example:

```python
   data, _ = time.get_daily_adjusted(symbol=ticker_string, outputsize="full")

    plt.figure(figsize=(18, 8))
    plt.title(f"{ticker_string} Open Valuation Over Time")
    plt.xlabel("Date")
    plt.ylabel("Value (Dollars)")
    plt.plot(data.index.values, data[["1. open"]])
    plt.grid()
    plt.show()
```

Gives me:
![image](https://user-images.githubusercontent.com/43937630/91111471-717e9e00-e635-11ea-834d-8afaa227a8d3.png)

A quick google search shows that AAPL did a 7/1 split in 2014. Am I using the wrong function methods or is this by design from alpha vantage. How do I work around this? Thanks!

**Comment by SteveAlphaVantage** [comment]
@alejandroarmas, you were getting really close 👍 

To plot adjusted time series, please change the following line:

`plt.plot(data.index.values, data[["1. open"]])` 

into

`plt.plot(data.index.values, data[["5. adjusted close"]])`

You may also find the following documentations useful: 

- https://www.alphavantage.co/documentation/#dailyadj
- https://github.com/RomelTorres/alpha_vantage/issues/115

**Comment by alejandroarmas** [comment]
Oh I see how silly of me, thank you Steve! I had used the `data[["1. open"]]` from the `get_daily' method. Did not realize there was an extra column for `get_daily_adjusted'. 

I'm wondering now, is there any reason to want to use `get_daily' over `get_daily_adjusted' if that's the case? Would it create more overhead in the API call if you use the latter? 

Another question, say I wanted to use to visualize real time updates of the `get_intraday' call. Should I call the API every few minutes and update or is there a smarter way around that? Thanks a lot!

**Comment by SteveAlphaVantage** [comment]
@alejandroarmas, since the questions are more about API use cases rather than this Python wrapper, could you please direct your questions to support@alphavantage.co?

**Comment by alejandroarmas** [comment]
Sure thing, thanks for directing me. Thank you.
