### ISSUE TITLE
intraday data returned does not include current day

### ISSUE THREAD

**Issue by sher85** [RomelTorres/alpha_vantage#253]
The `get_intraday` function returns data for the past 7 days, not including the current day in which the code is executed. Could we add functionality to retrieve the same data for the ongoing day up to the moment the function is called or are there other functions that already complete this action?

**Comment by SteveAlphaVantage** [comment]
@sher85, this seems to be a server-side policy instead of the behavior of this particular Python library. Could you please reach out directly to support@alphavantage.co?
