### ISSUE TITLE
Is there a timeseries intraday extended history method?

### ISSUE THREAD

**Issue by carlosazpurua1004** [RomelTorres/alpha_vantage#258]
Not sure how new the time series intraday extended history is to AV but it seems like this would be straight forward to add in timeseries.py?

**Comment by thanos750** [comment]
I believe TIME_SERIES_INTRADAY_EXTENDED only returns in csv format and returns only 1 month at a time. up to 24 month slices.  So 24 csv files. 
I tried adding this func to the TimeSeries class.  
'
@av._output_format
@av._call_api_on_func
def get_intraday_extended(self, symbol, interval='15min', slice='year1month1'):
        _FUNCTION_KEY = "TIME_SERIES_INTRADAY_EXTENDED"
        return _FUNCTION_KEY, "Time Series ({})".format(interval), 'Meta Data'
'
Then ran this. 
'
from alpha_vantage.timeseries import TimeSeries
import pandas as pd

ts = TimeSeries(key=apikey,,output_format='csv')
data, meta_data = ts.get_intraday_extended(symbol='MSFT',interval='1min',slice='year1month2')
'
data returns a csv_reader object which i loop through to store into a dictionary and then convert to a dataframe.  But the slice always returns only the first month regarding of the slice arg value. Probably have to update the _call_wrapper func as well.  

What would be nice would be being able to provide a number of slices as an integer representing the number of months  to the func as a slice arg and then retrieve and merge the data as the  output as a csv, json or pandas dataframe. Maybe this can be done in  an asycio way to we aren't looping and waiting for 24 csv files?

sorry kinda of a noob to pyython.

**Comment by AlphaVantageSupport** [comment]
The extended intraday function has been added in the latest release. Kudos to the community!
