### ISSUE TITLE
timeseries

### ISSUE THREAD

**Issue by Splix76** [RomelTorres/alpha_vantage#26]
Copy and pasted the code for the basic GOOGL stock check, error is seen.

`from alpha_vantage.timeseries import TimesSeries`
`ts = TimesSeries(key='YOUR_API_KEY')`
`data, meta_data = ts.get_intraday('GOOGL')`

> from alpha_vantage.timeseries import TimesSeries
> ModuleNotFoundError: No module named 'alpha_vantage.timeseries'

**Comment by Splix76** [comment]
I have installed with the following command.

`pip3 install alpha_vantage`

This install completes without error.

If I import the overall module, there is no error
`import alpha_vantage`

**Comment by RomelTorres** [comment]
Can you try instead `from alpha_vantage.timeseries import TimeSeries` there is an extra s in `TimesSeries`. 

Let me know if that fixes it to close the issue.

Saludos

Romel

**Comment by Splix76** [comment]
Taken from my python3 shell.  I also ran the 'import alpha_vantage' to show that the module was installed via pip3 as shown above. 

```
Python 3.6.2 (default, Oct  2 2017, 16:51:32) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> from alpha_vantage.timeseries import TimeSeries
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'alpha_vantage.timeseries'


>>> import alpha_vantage

```

**Comment by Splix76** [comment]
[](https://pypi.python.org/pypi/alpha_vantage/1.3.6)

The extra s is present in the docs linked above. It was a direct copy/paste from the docs I was using to prove that the module was working. Just passing this along so it can be corrected there.

The module fails to import with and without the extra S included for me. Thanks for the prompt reply!

**Comment by RomelTorres** [comment]
That's interesting, for me it's working without problems in python 3.6.3.... 

Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from alpha_vantage.timeseries import TimeSeries
>>>

**Comment by Splix76** [comment]
You're running Anaconda python, I am running native 3.6 in Fedora 26. I wonder if there is a missing dependency in the base 3.6 Python compared to Anaconda python.

**Comment by RomelTorres** [comment]
@Splix76 Oh yeah that s is haunting me... I will correct it on the docs.... I used to run it native but environments are quite neat, specially for development. I also installed it with pip3 and it worked. Wondering how to reproduce it....

**Comment by RomelTorres** [comment]
@Splix76; any news? I haven't been able to reproduce the error...

**Comment by Splix76** [comment]
I have not had time to circle back to this yet. I plan to stand up a VM running Fedora 26 and then attempt to install alpha_vantage, if that does not work I will install the anaconda python packages and try again.

I cannot do this on my main workstation as my python environment may be impacted by the installation, so a VM is needed to perform this test.

If I can prove it works in Anaconda but not in native Fedora 26 python on a clean installation then I can start comparing the packages to find the issue.

**Comment by Splix76** [comment]
Confirmed.

If I use Anaconda Python 3.6 the import works.
If I use Python 3.6 included with Fedora 26, it does not work.

**Comment by RomelTorres** [comment]
Yeah I think you are right. Once I am back home (I am travelling for work atm) I will look at the issue more closely. 

Best Regards

Romel
