### ISSUE TITLE
KeyError:None from Overview function in Fundamental Data

### ISSUE THREAD

**Issue by swagitda** [RomelTorres/alpha_vantage#260]
The Fundamental Data module works exactly as anticipated for the Balance Sheet and Income Statement functions (thanks!), but not for the Overview function. It results in a KeyError:None result:
```
File "...\alpha_vantage\alphavantage.py", line 222, in _format_wrapper
    data = call_response[data_key]
KeyError: None
```

I invoked all the functions in a similar format, just as @foxy0 originally mentioned in https://github.com/RomelTorres/alpha_vantage/issues/251#issuecomment-693547201:
```
symbol = input('Enter Ticker Symbol:')
key = 'demo'
fd = FundamentalData(key=key, output_format='pandas')
Balance_Sheet = fd.get_balance_sheet_quarterly(symbol)
Income_Statement = fd.get_income_statement_annual(symbol)
Company_Overview = fd.get_company_overview(symbol)
```

The workaround is straightforward (for anyone who is running into something similar, see below), but would be nice to understand why it doesn't work via this module or how I'm screwing up in using it.

_Current workaround_:
```
API_URL = "https://www.alphavantage.co/query"
data = {
     "function": "OVERVIEW",
     "symbol": symbol,
     "outputsize": "compact",
     "datatype": "json",
     "apikey": key,
     }
response = requests.get(API_URL, data)
Company_Overview = response.json()
```

**Comment by PatrickAlphaC** [comment]
Thanks for this issue! It looks like there is a bug in the current implementation....
