### ISSUE TITLE
'data' from get_intraday function coming back as a dictionary, not as a dataframe 

### ISSUE THREAD

**Issue by grzesir** [RomelTorres/alpha_vantage#262]
This results in a dictionary:

```
data, meta_data = ts.get_intraday(symbol=symbol,interval='1min', outputsize='full')
logging.info(data)
```

And this results in an error:

`logging.info(data.head(2))`

**Comment by pssolanki111** [comment]
try adding `output_format='pandas'` as an argument to the `get_intraday()` call.

`data, meta_data = ts.get_intraday(symbol=symbol, output_format='pandas', interval='1min',  outputsize='full')`

**Comment by DeepOde** [comment]
Couldn't reproduce the issue. The default is `output_format = 'json'` for ` TimeSeries`. If `ts` is created with `output_format = 'pandas'`, the line `data, meta_data = ts.get_intraday(symbol=symbol, interval='1min', outputsize='full')` returned `DataFrame`.

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.
