### ISSUE TITLE
Why can't I get data of S&P 500?

### ISSUE THREAD

**Issue by TianliaoLiu** [RomelTorres/alpha_vantage#264]
Hello, I'm new to coding. 
I'm trying to get data of S&P 500 using alpha_vantage API, 
but it somehow didn't work. 
I tried IBM and Microsoft, and it all worked.
Does anyone know where the problem is? 

![捕获](https://user-images.githubusercontent.com/73066022/96369010-24d1c200-11a3-11eb-83fd-79e3e1019bc8.PNG)
![捕获2](https://user-images.githubusercontent.com/73066022/96369012-256a5880-11a3-11eb-99d2-fb43d056d760.PNG)

**Comment by swagitda** [comment]
As far as I know, AlphaVantage doesn't support indices, but the closest you could use is `SPY` to lookup [the ETF for the S&P 500](https://en.wikipedia.org/wiki/SPDR_S%26P_500_Trust_ETF). As an alternative, you could try pulling S&P 500 data from the [St. Louis Fed (FRED)](https://fred.stlouisfed.org/series/SP500) via [Pandas](https://pandas-datareader.readthedocs.io/en/latest/readers/fred.html).

**Comment by Pfed-prog** [comment]
I can't find SPN ticker either available on YahooFinance here https://finance.yahoo.com/quote/SPN/?p=SPN

**Comment by AlphaVantageSupport** [comment]
You were spot on, @swagitda. Thanks for the insightful answer. 

cc: @TianliaoLiu
