### ISSUE TITLE
Problems with international stocks

### ISSUE THREAD

**Issue by hugo-am** [RomelTorres/alpha_vantage#266]
Hello! 
I would like to obtain time series of the 31 trackers of the Mexican Stock Market. The name of the symbols on yahoo finance always end with '.MX', for example, ALSEA.MX:

https://finance.yahoo.com/quote/ALSEA.MX?p=ALSEA.MX&.tsrc=fin-srch

I was able to download the time series in the past but recently I have been unable to do so because I get an invalid API call message.
Heres the code that I am using:

from alpha_vantage.timeseries import TimeSeries
ts=TimeSeries(key='1234,output_format='pandas')

ts.get_daily(symbol='ALSEA.MX',outputsize='full')

Thank you!

**Comment by SteveAlphaVantage** [comment]
@hugo-am, since this issue is more about the underlying API rather than this Python library, please kindly direct your question to support@alphavantage.co

Thank you!
