### ISSUE TITLE
Unable to setup a connection with Alpha Vantage API

### ISSUE THREAD

**Issue by shosahu** [RomelTorres/alpha_vantage#267]
Hi,

I'm facing an issue while setting a connection and retrieving the daily data, I have entered the API key (Free API key) correctly... and when I'm trying to retrieve OHLC data it gave me `requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.alphavantage.co', port=443)` 

my simple code (just getting familiar with Alpha Vantage):
```
from alpha_vantage.timeseries import TimeSeries

app = TimeSeries('my free API key')
aapl = app.get_daily_adjusted("AAPL", outputsize = "compact")
print(aapl)
```

not sure what's the issue here, and now when I'm trying to google and open the Alpha Vantage website, it's not opening there as well, seems like my _'Ex-'_ who blocked me from everywhere. :D 

Can anybody confirm or help me with what I doing wrong and how should I proceed? 
Or Alpha Vantage servers are down, which I am not sure is the case!

**Comment by AlphaVantageSupport** [comment]
@shosahu, we are not aware of any server-side outages. Please reach out to support@alphavantage.co if you are still experiencing the issue.
