### ISSUE TITLE
intraday data ( extended history) docs

### ISSUE THREAD

**Issue by AdrianGutierrez0606199** [RomelTorres/alpha_vantage#269]
with the current state of the API on python we are not able to extract intraday stock data from more than 2 months althought the alphavantage API already have a feature to get it.

It would be very helpfull if we can make it possible some way.

ty.

**Comment by windowshopr** [comment]
I'm not super knowledgeable about how this program handles the API side of things, but I noticed that now with Pandas, you can just call the `pd.read_csv(url)` function, where `url` is the url at AV to download a `.csv` version of an extended dataset. So, using one of their demo url's, I just did:

```
import pandas as pd
df = pd.read_csv('https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY_EXTENDED&symbol=IBM&interval=15min&slice=year1month1&apikey=demo')
print(df)
```

and got this output:

```
                    time    open    high       low   close  volume
0    2020-12-17 16:15:00  125.55  125.55  125.5374  125.55  292013
1    2020-12-17 16:00:00  125.56  125.56  125.3100  125.50  306375
2    2020-12-17 15:45:00  125.60  125.74  125.4700  125.56  146309
3    2020-12-17 15:30:00  125.62  125.71  125.5635  125.61  105843
4    2020-12-17 15:15:00  125.64  125.75  125.5800  125.61   88741
..                   ...     ...     ...       ...     ...     ...
847  2020-11-18 08:15:00  118.51  118.52  118.1500  118.15    2885
848  2020-11-18 07:45:00  118.35  118.40  118.3500  118.40     658
849  2020-11-18 07:30:00  118.25  118.25  118.2500  118.25     102
850  2020-11-18 07:00:00  118.30  118.30  118.3000  118.30     100
851  2020-11-18 04:15:00  118.15  118.15  118.1500  118.15     100

[852 rows x 6 columns]
```

So it would probably be easy enough to build a function like `get_intrady_extended()` that takes in some parameters that the url needs to fulfill the request (like API key, year number, month number, whatever else is specific to "extended"), and at least the user could get a dataframe that way? Just my thoughts. :)

**Comment by PatrickAlphaC** [comment]
This has been addressed in 2.3.1, looking for help with docs and tests!

**Comment by beanhedge** [comment]
I tried:
`data, meta_data = ts.get_intraday_extended(symbol='MSFT', interval='5min')
`
and got:
`simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
any idea what I could be doing wrong?

Edit: actually the pd.read_csv line in your comment worked, so I am unblocked :)

**Comment by coopermc** [comment]
get_intraday_extended is broken, as described in the previous comment. additionally, get_intraday currently only returns data back to december 28th, 2020.

**Comment by danielfiniki** [comment]
get_intraday_extended works, but with extra steps.
You have to set the output_format to CSV, because the API returns it as CSV instead of JSON (that's where the JSONDecodeError above is coming from), so use this:
`ts = TimeSeries(key="your_key", output_format="csv")`

And you only get to pull slices from the extended endpoint, not the full thing. One slice is for one month. The oldest slice you can get is year2month12, so data from about 2 years ago.
If you don't specify a slice it will default to the newest one, so "year1month1". If you want the month before that it's "year1month2" and so on until "year2month12".
`ts.get_intraday_extended(symbol="MSFT", interval="5min", slice="year2month12")`

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.
