### ISSUE TITLE
Add Daily Adjusted API wrapper for Alpha Vanatage

### ISSUE THREAD

**Issue by samperd** [RomelTorres/alpha_vantage#27]
As a python developer using Alpha vantage python module
I want access to Time Series Daily Adjusted data from the Alpha Vantage API
So that I can extract dividend events

Details:
Docs: https://www.alphavantage.co/documentation/#dailyadj

Daily Adjusted API should expose the following data points:
* date, 
* daily open, 
* daily high, 
* daily low, 
* daily close, 
* daily volume, 
* daily adjusted close, and 
* split/dividend events

**Comment by RomelTorres** [comment]
Hi @samperd, i the timeseries module you have the function: ```get_daily_adjusted``` is not that what you are looking for? http://alpha-vantage.readthedocs.io/en/latest/source/alpha_vantage.html#module-alpha_vantage.timeseries or am i missing something there? I have been on a business trip for a while now, but as soon as I get back to Germany I can have a look at that function call to see if I have implemented it as it should.

Saludos Romel.

**Comment by samperd** [comment]
@RomelTorres Thanks for pointing me in the right direction. I did not see it in the docs, but i now see it in the code. used the dir() command to drive down to see other functions. You can close this issue.

BTW I am appreciating the use of Panda Frames. Handy way to slice through the data. But I do have an issue with sorting or slicing on the date column and columns with spaces in the names. See issue #28

Cheers

**Comment by RomelTorres** [comment]
Ok perfect, closing issue now.
