### ISSUE TITLE
Daily crypto pairs

### ISSUE THREAD

**Issue by dorienh** [RomelTorres/alpha_vantage#272]
I am trying to get daily values for pairs of crypto, e.g. 

`data, meta_data = cc.get_digital_currency_daily(symbol='BTC', market='ETH')`

However, seems the market value is not accepted. 

In the API documentation, it seems to say it allows to and from to be a crypto, however: 

CURRENCY_EXCHANGE_RATE High Usage

This API returns the realtime exchange rate for a pair of digital currency (e.g., Bitcoin) and physical currency (e.g., USD).

API Parameters
❚ Required: function

The function of your choice. In this case, function=CURRENCY_EXCHANGE_RATE

❚ Required: from_currency

The currency you would like to get the exchange rate for. It can either be a physical currency or digital/crypto currency. For example: from_currency=USD or from_currency=BTC.

❚ Required: to_currency

The destination currency for the exchange rate. It can either be a physical currency or digital/crypto currency. For example: to_currency=USD or to_currency=BTC.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-49-bf883c048d38> in <module>()
----> 1 data, meta_data = cc.get_digital_currency_daily(fromsymbol='BTC', tosymbol='ETH')
      2 data['4b. close (USD)'].plot()
      3 
      4 print(data.head(2))
      5 print(data.columns.values)

1 frames
/usr/local/lib/python3.6/dist-packages/alpha_vantage/alphavantage.py in _call_wrapper(self, *args, **kwargs)
    121             # key for it and for its meta data.
    122             function_name, data_key, meta_data_key = func(
--> 123                 self, *args, **kwargs)
    124             base_url = AlphaVantage._RAPIDAPI_URL if self.rapidapi else AlphaVantage._ALPHA_VANTAGE_API_URL
    125             url = "{}function={}".format(base_url, function_name)

TypeError: get_digital_currency_daily() got an unexpected keyword argument 'fromsymbol'
```

**Comment by AlphaVantageSupport** [comment]
At the first glance, get_digital_currency_daily maps to the **DIGITAL_CURRENCY_DAILY** function (NOT the CURRENCY_EXCHANGE_RATE function as was mentioned in the post above). 

**DIGITAL_CURRENCY_DAILY** doesn't have a `to_currency` input parameter. Below is the documentation for **DIGITAL_CURRENCY_DAILY**:

https://www.alphavantage.co/documentation/#currency-daily
