### ISSUE TITLE
Uncorrect dates

### ISSUE THREAD

**Issue by Marat2607** [RomelTorres/alpha_vantage#279]
Hello!
alpha_vantage library:
![1](https://user-images.githubusercontent.com/55015388/102862284-e6c27a00-4441-11eb-9c8a-a04331d26f49.png)

yfinance:
![2](https://user-images.githubusercontent.com/55015388/102862550-5173b580-4442-11eb-980a-bea57b08aff9.png)

For example:
2020-07-31 | 102.885002 | 106.415001 | 100.824997 | 106.260002

102.885002 * 4 = 411.535

Why some of your data multiplied by 4?

And how i can select a range of intraday data?

Thank you

**Comment by AlphaVantageSupport** [comment]
@Taram1980: There is a difference between **raw** close and **adjusted** close. You may want to refer to the following GitHub post: 

https://github.com/RomelTorres/alpha_vantage/issues/115

In brief, please check out our DAILY ADJUSTED endpoint - specifically the **adjusted close** field:
https://www.alphavantage.co/documentation/#dailyadj

Thank you!
