### ISSUE TITLE
Searching, Sorting and Slicing Pandas dataframe for dates and collumn names with spaces

### ISSUE THREAD

**Issue by samperd** [RomelTorres/alpha_vantage#28]
@RomelTorres having never used panda frames I am on a steep learning curve going through pandas docs. However I am blocked on searching the date collumn and having issues with collumn names with spaces.

Concerning date collumn:
As a alpha Avantage python developer
I want to search (query), sort and slice on the Date/Time column.
So that I can find specific values based on data and time

Issue: I can not seem to reference the date/time column in the same manner as I can for the other collumns. Am I missing something?

Concerning collumn names with spaces:
As an alpha avantage python developer
I want a consistant way to reference collumns
So that I can re-use code patterns and keep my code readable

Issue: I find that when a column name does not have a space there are nice tight and elegant ways to refer to the column names. For columns that have spaces I find that there is a limited number of ways to call those columns, and you need to use more verbose syntax (including quotes). This becomes especially challenging when using other pandas features such as query.

Perhaps the column names in the dataframe can use underscores instead of spaces to help avoid the complexities of dealing with spaces. I wonder if there is a concept in pandas that might allow a column name and a column lable to applied, where the lable has a space and the name has an underscore?

Just some thoughts.

Cheers

**Comment by RomelTorres** [comment]
Hi @samperd, sorry for the late response. I usually leave the column names as delivered by the alpha vantage api. Nevertheless, to do what you want is quite simple and will add an option for that in the next version. I just have to change  in the alpha_vantage.py file the `_output_format(cls, func, override=None)` function, I will add an option to trim column names if desired.

BR Romel Torres
