### ISSUE TITLE
ModuleNotFoundError: 'alpha_vantage.timeseries'

### ISSUE THREAD

**Issue by akmt14** [RomelTorres/alpha_vantage#280]
I've gone through the issues history & came across a few similar issues that other users have faced, but i'm not sure  about the solution.

Import alpha_vantage works fine. However, while trying to import the time_series module, an error is thrown.

**ModuleNotFoundError: No module named 'alpha_vantage.timeseries'; 'alpha_vantage' is not a package**

**Comment by akmt14** [comment]
figured it out. I'm an idiot.

**Comment by toughhou** [comment]
below method works fine.

go to work folder, then:
git clone https://github.com/RomelTorres/alpha_vantage.git
mv alpha_vantage 123
mv 123/alpha_vantage ./
rm -rf 123
