### ISSUE TITLE
URL equivalent to SectorPerformance

### ISSUE THREAD

**Issue by BastianZim** [RomelTorres/alpha_vantage#281]
Hi,

awesome tool, thank you very much for creating and maintaining it!

I was just wondering, what the URL equivalent to SectorPerformance is, as I cannot find it anywhere in the docs (https://www.alphavantage.co/documentation/)

I think it's constructed here (If I'm not mistaken):

https://github.com/RomelTorres/alpha_vantage/blob/a70f110c4883ffe66f2d1f36571a61c2a90e563d/alpha_vantage/sectorperformance.py#L36

But I cannot find `SECTOR` in the docs, only time series, fundamentals, forex, crypto and technical indicators. Am I missing something?

Thanks!

**Comment by AlphaVantageSupport** [comment]
@BastianZim, happy new year! Since this is more of an API-specific question (rather than a python wrapper specific question), could you please reach out to support@alphavantage.co?

**Comment by BastianZim** [comment]
@AlphaVantageSupport Happy New year! Of course, just wasn’t sure if the wrapper is secretly making multiple calls or if it’s really another endpoint but then I’ll write a separate email. 

Thanks!
