### ISSUE TITLE
Does retries back off exponentially?

### ISSUE THREAD

**Issue by BastianZim** [RomelTorres/alpha_vantage#282]
Hi,

I was wondering if `retries`, like in here: `ts = TimeSeries(key='YOUR_API_KEY',retries='YOUR_RETRIES')` backs off exponentially in case the error is throttling, or if it just reruns the query?

Thanks!

**Comment by AlphaVantageSupport** [comment]
It should be a simple re-run of the initial query. But please feel free to propose any advanced retry methods as a feature request (or submit a pull request if you feel ambitious 🥇 )!

**Comment by BastianZim** [comment]
Thanks for the reply and clarification! I'm not sure if I know enough about decorators to create a PR but should definitely be able to create a feature request. 
Just to check though, from what I can see, the retries are passed here 

https://github.com/RomelTorres/alpha_vantage/blob/62db439b3a43aa9b5c1e0fc79ff51ec70ac1cce1/alpha_vantage/alphavantage.py#L34

but then I'm not sure where the actual retrying is happening? Is that in a different file?

**Comment by BastianZim** [comment]
@AlphaVantageSupport Just gently bumping this again.

**Comment by dnlhpp** [comment]
After working on the code a bit I noticed that the documentation states that the amount of retries can be passed, but the parameter is never used/not implemented. I hope this answers your question @BastianZim.

**Comment by BastianZim** [comment]
Thanks @dhoeppe! Yeah I was at least suspecting it but not 100% sure, so thanks for the confirmation!
