### ISSUE TITLE
Async support for fundamental data

### ISSUE THREAD

**Issue by SoAG** [RomelTorres/alpha_vantage#283]
It looks like fundamental data  support was recently added to the synchronous version but not the the async version.

Any chance we can add async support for fundamental data as well?

**Comment by Ziinax** [comment]
yes it would be amazing if the async fundamental data support will be added.

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.
