### ISSUE TITLE
Added to conda

### ISSUE THREAD

**Issue by BastianZim** [RomelTorres/alpha_vantage#284]
Hi, I just wanted to let everyone know that I added this package to conda-forge so that it can be downloaded with conda.
See: https://github.com/conda-forge/staged-recipes/pull/13643

If there's any interest, I can also add the maintainers here as maintainers there, just ping me in the comments or make an issue/pr there. I can also add a badge to the readme but just wanted to check first. Like so: 

[![Anaconda-Server Badge](https://anaconda.org/conda-forge/alpha_vantage/badges/version.svg)](https://anaconda.org/conda-forge/alpha_vantage) 
![Conda](https://img.shields.io/conda/dn/conda-forge/alpha_vantage?label=Conda%20downloads)

(Might not work yet, as it was just merged.)

**Comment by BastianZim** [comment]
@AlphaVantageSupport It's alive! https://github.com/conda-forge/alpha_vantage-feedstock

Anyone or anything I should add here or there? Otherwise feel free to close this!

**Comment by AlphaVantageSupport** [comment]
@BastianZim - thank you for your valuable contribution!
