### ISSUE TITLE
Alpha vantage demo requests not working

### ISSUE THREAD

**Issue by sophiabulcock** [RomelTorres/alpha_vantage#289]
Hi, I am trying to do an Alpha Vantage API query for a school project. I create my API url request in python, and it produces a link to the data, but I get this error message about half the time 

{"Error Message": "Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for FX_DAILY."
}

When I try to click in any of their demo links, the same error pops up: https://www.alphavantage.co/query?function=FX_DAILY&from_symbol=EUR&to_symbol=USD&outputsize=full&apikey=demo

Anyone have any idea how to report this to them or fix it?

**Comment by AlphaVantageSupport** [comment]
We cannot seem to reproduce the behavior. That being said, we've relayed the report to our engineering team. Thanks Sophia!
