### ISSUE TITLE
misplaced parentheses causing AttributeError for CSV outputs.

### ISSUE THREAD

**Issue by Camelket** [RomelTorres/alpha_vantage#290]
when output_format  is set to "csv" some functions throw the error below, because of the misplaced parentheses. 

"C:\Users\\alpha_vantage\alpha_vantage\async_support\alphavantage.py", line 261, in _handle_api_call
    csv_response = csv.reader((response.text.splitlines()))
AttributeError: 'function' object has no attribute 'splitline

alpha_vantage\async_support\alphavantage.py", line 261, 
should be:
   csv_response = csv.reader((response.text()).splitlines())

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.
