### ISSUE TITLE
Issue with COP/INR currency pair

### ISSUE THREAD

**Issue by the-solipsist** [RomelTorres/alpha_vantage#291]
Very curiously, I find that one particular forex currency conversion doesn't work for me.

If using 
function=CURRENCY_EXCHANGE_RATE
from_currency=COP
to_currency=INR

I get this error:

```
{
    "Error Message": "Invalid API call. Please retry or visit the
documentation (https://www.alphavantage.co/documentation/) for
CURRENCY_EXCHANGE_RATE."
}
```

Interestingly, this works:

function=CURRENCY_EXCHANGE_RATE
from_currency=INR
to_currency=COP

And conversion from COP to USD works as well:

CURRENCY_EXCHANGE_RATE
from_currency=COP
to_currency=USD

So it is unclear why COP -> INR is not working.

**Comment by AlphaVantageSupport** [comment]
@the-solipsist, since this doesn't seem to be a Python wrapper related issue, we have relayed your report to our engineering team. Thanks!
