### ISSUE TITLE
DJIA and stock indices not supported anymore?

### ISSUE THREAD

**Issue by antoinecomp** [RomelTorres/alpha_vantage#292]
I am trying to download the DJIA Dataset from Alpha Vantage but I get a ValueError and read [several comments online ](https://stackoverflow.com/a/45436162/4764604) saying that the stock indices stoped working.

```
"""
Download the all-time DJIA dataset
"""
from alpha_vantage.timeseries import TimeSeries

# Update your Alpha Vantage API key here...
ALPHA_VANTAGE_API_KEY = 'MYAPIKEY'

from pprint import pprint
ts = TimeSeries(key=ALPHA_VANTAGE_API_KEY, output_format='pandas')
data, meta_data = ts.get_intraday(symbol='^DJI',interval='1min', outputsize='full')
pprint(data.head(2))
```

**Comment by AlphaVantageSupport** [comment]
@antoinecomp, this seems to be server-side behavior that is beyond the scope of this Python library. Could you please relay you message/questions to support@alphavantage.co?
