### ISSUE TITLE
Get_daily_adjusted returns error when asking for pandas format

### ISSUE THREAD

**Issue by kin0969** [RomelTorres/alpha_vantage#294]
Error message is showed as below.
"Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY_ADJUSTED."

When modifying the format from pandas to CSV, everything is fine.

**Comment by kin0969** [comment]
Root cause is inputting a wrong stock symbol. Code works well.. 
Thanks.

**Comment by xxccy668** [comment]
> 

But the correct ticker code can still make this error
