### ISSUE TITLE
Getting raw (unadjusted) intraday data

### ISSUE THREAD

**Issue by espdev** [RomelTorres/alpha_vantage#295]
Hello,

I want to get intraday data without split/dividend adjustment. How can I get raw intraday data?

From API [docs](https://www.alphavantage.co/documentation/#intraday):

> Optional: adjusted
>
> By default, adjusted=true and the output time series is adjusted by historical split and dividend events. Set adjusted=false to query raw (as-traded) intraday values.

`get_intraday` and `get_intraday_extended` methods do not contain `adjusted` argument and I assume it will be true by default.

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.
