### ISSUE TITLE
How to get the historical data of market value?

### ISSUE THREAD

**Issue by panyiming** [RomelTorres/alpha_vantage#296]
Hi, guys. I am doing some research about the financial market. Now I need the daily market value data of SP500 stocks.
So How can I get it through this package?

Thanks so much. Hope to get some help from you guys.

**Comment by azromero** [comment]
Get the daily close price of each stock and multiply by their Shares
Outstanding, you will get the daily market value.

You can do this using Google Finance functions on Google Spreadsheet

Em sáb., 13 de fev. de 2021 às 07:43, panyiming <notifications@github.com>
escreveu:
