### ISSUE TITLE
Intraday Support for Crypto

### ISSUE THREAD

**Issue by import-benton** [RomelTorres/alpha_vantage#298]
I've noticed that support for intraday crypto was removed, or at least I'm novice enough to not know where this is. I'm currently using `from alpha_vantage.cryptocurrencies import CryptoCurrencies` and can't seem to find intraday in this package. Should I be looking elsewhere, and if not, will support for this feature be returning any time soon?

**Comment by AlphaVantageSupport** [comment]
@XemnasAutomated, since this Python library is just a pass-through of the main Alpha Vantage API, could you please relay functionality-specific questions to support@alphavantage.co directly? Thanks!
