### ISSUE TITLE
Small errata in the example of the Bollinger Bands

### ISSUE THREAD

**Issue by paduel** [RomelTorres/alpha_vantage#3]
Hola Romel.

I tested your package and it's a great work!  Thank you for your effort.

I am sure it will be a very popular package now that the Yahoo Finance API service has been canceled.

But I wanted to point out that in the BB example there is a small error in the code:

You write :
```
from alpha_vantage.techindicators import TechIndicators
import matplotlib.pyplot as plt

ts = TechIndicators(key='YOUR_API_KEY', output_format='pandas')
data, meta_data = ti.get_bbands(symbol='MSFT', interval='60min', time_period=60)
data.plot()
plt.title('BBbands indicator for  MSFT stock (60 min)')
plt.show()
```
and the correct is a **ts** at line 5:

```
from alpha_vantage.techindicators import TechIndicators
import matplotlib.pyplot as plt

ts = TechIndicators(key='YOUR_API_KEY', output_format='pandas')
data, meta_data = ts.get_bbands(symbol='MSFT', interval='60min', time_period=60)
data.plot()
plt.title('BBbands indicator for  MSFT stock (60 min)')
plt.show()

```

I know that isn't very important, but this way it's perfect.

You've done a great job!

**Comment by paduel** [comment]
Or perhaps you want to write :

`ti = TechIndicators(key='YOUR_API_KEY', output_format='pandas')`

This way it's possible to use with **ts**, together.

**Comment by RomelTorres** [comment]
Hey Paduel, 

Thank you! for using the package and being so supportive. I hope you enjoy it.

Romel
