### ISSUE TITLE
Does not support CSV querys

### ISSUE THREAD

**Issue by bezeredi** [RomelTorres/alpha_vantage#30]
This package does not support CSV queries as requested by Alpha Vantage for all wrapper libraries as quoted from their FAQ page:

> **I have built a library/wrapper for Alpha Vantage with a specific programming language. May I open-source it on GitHub?**
>Certainly - we truly appreciate the help and support from the community to make Alpha Vantage even more accessible and developer-friendly. However, we ask that your language-specific library/wrapper preserves the content of our JSON/CSV responses in both success and error cases. We consider it a top priority that our users get the original debugging and troubleshooting information from Alpha Vantage.

**Comment by RomelTorres** [comment]
Hi @bezeredi, thank you for the feedback. I had not seen that before, I will add support to CSV so that alphavantage wishes are respected. It will be added in the next release.

Saludos Romel
