### ISSUE TITLE
Dates within Index of Dataframe from FundamentalData are all from year 1970

### ISSUE THREAD

**Issue by zhems** [RomelTorres/alpha_vantage#303]
![image](https://user-images.githubusercontent.com/20948642/110545232-cded6a80-80fa-11eb-83ea-f680bf2b1c9d.png)

I checked and it seems to be outputting the correct information in descending chronological order (for the year 2020, 2019, 2018, etc) but the TimeStamp in the index is wrong

**Comment by divyank0** [comment]
I have some time and can help resolve this issue.  I read the code and understood the issue, However will need a quick discussion on how to resolve it.

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.
