### ISSUE TITLE
Is "Intraday" information only for "last trading day"?

### ISSUE THREAD

**Issue by Rational-IM** [RomelTorres/alpha_vantage#304]
Not sure if there is an issue or I'm just missing something.

I'm trying Alpha Vantage and I'm quite impressed with its speed. This module is also very easy to use - congratulations Romel Torres.

However, I'm not finding a way to get "as of now" price information. I'm OK with delayed data (e.g. 20 minutes) but does "intraday" means "yesterday's intra-day" data? Below is a code and the output I get. The market is open now (March **19th**, 10:35 AM EST) and see below what I get for Coca-Cola. Note that the last trading day is for March **18th**:

from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries(key='my key here',output_format='pandas')
ticker = 'KO'
data, meta_data = ts.get_intraday(symbol=ticker, interval='1min', outputsize='compact')
print('\n'+ 'Ticker: ' + ticker)
print(data)

![image](https://user-images.githubusercontent.com/57544001/111797034-2660fc80-889f-11eb-94ff-e82e3279386b.png)

**Comment by AlphaVantageSupport** [comment]
@Rational-IM, this seems to be a server-side behavior instead of an issue with this Python library. Do you mind directing your question to support@alphavantage.co? Thanks!
