### ISSUE TITLE
7. dividend amount

### ISSUE THREAD

**Issue by Marat2607** [RomelTorres/alpha_vantage#305]
Hello
After use "ts.get_daily_adjusted(symbol=ticker, outputsize='full')" , i got column "7. dividend amount".  I understand this is not a programming issue, but maybe someone explain what this means. Is this numbers in dollars or percentages and ones relative to what, to 1 share or per 1 lot?
Thanks

**Comment by AlphaVantageSupport** [comment]
It is the amount per share (not percentage). Thanks!

**Comment by Marat2607** [comment]
Ok. And there are prices per share or per standard lot?

**Comment by AlphaVantageSupport** [comment]
It is for _per share_.

**Comment by Marat2607** [comment]
Thank you
