### ISSUE TITLE
Date Column

### ISSUE THREAD

**Issue by ACPK** [RomelTorres/alpha_vantage#31]
The date column doesn't become a valid column when I use:

    ts = TimeSeries(key=os.environ.get('ALPHAVANTAGE_API'), output_format='pandas')
    data = ts.get_daily_adjusted('aapl', outputsize='full')

**Comment by RomelTorres** [comment]
hello @ACPK I havent' had a chance to check the issue. Let me know if it still a problem for u.

Thanks, Romel

**Comment by ACPK** [comment]
@RomelTorres - Yes, I'm still having the same issue.

**Comment by bretcj7** [comment]
@ACPK I have a fix for this that could be made.  It would create a new numerical index of the data but then add the 'Date' column with its data as a true column on the data set.

`df.index.name = 'Date'
df.reset_index(level=0, inplace=True)`

Resetting the index like above will produce the following output on the DataFrame:

`Date  open  high  low  close  adjusted close 
0  2017-12-14    85.43  85.8739   84.53     84.69              84.69   
1  2017-12-15    85.26  87.0900   84.88     86.85              86.85   
2  2017-12-18    87.12  87.4999   86.23     86.38              86.38   `

Columns:
`Index(['Date', 'open', 'high', 'low', 'close', 'adjusted close',
       'volume', 'dividend amount', 'split coefficient'],
      dtype='object')`

Let me know if I should open up a PR for this change.

**Comment by RomelTorres** [comment]
Hi @bretcj7, that would be awesome if you opened up a PR. The place to change is the function 
```python
    @classmethod
    def _output_format(cls, func, override=None):
```
in the alpha_vantage.py file. 

Saludos,
Romel

**Comment by ACPK** [comment]
@bretcj7 - AlphaVantage's API calls are extremely slow so I went in a new direction. Have you found that they're very slow?

I also noticed that their error message for unknown tickers is incorrect as it says to check your API credentials.

**Comment by bretcj7** [comment]
https://github.com/RomelTorres/alpha_vantage/pull/35

**Comment by RomelTorres** [comment]
@bretcj7 Thanks for the PR i just integrated it. Awesome work.

Romel

**Comment by ACPK** [comment]
@bretcj7 - API calls on Heroku were averaging about 45 seconds for us, unless they time out and we'd have to try again.

**Comment by ACPK** [comment]
@RomelTorres - This was closed but it's still not on the Master branch?

**Comment by RomelTorres** [comment]
Hi @bretcj7, I just pushed a version in the develop brach, that it makes it optional to have either the Date or the integer indexing directly on the resulting pandas data frame. I think that way everybody is pleased,

Saludos
Romel
