### ISSUE TITLE
Feature request: Crypto Intraday

### ISSUE THREAD

**Issue by saviornt** [RomelTorres/alpha_vantage#311]
I've been experimenting with the crypto aspects of the library, and I do see that there are the endpoints for daily, weekly, and monthly, however the endpoint for intraday is not available using the "function=CRYPTO_INTRADAY" from the Cryptocurrencies  section of the API.

I would assume the format would be:
`(data, meta) = cc.get_crypto_intraday(symbol = "", interval = "", market = "", outputsize = "")`

Here is the example link from the API documentation:
https://www.alphavantage.co/query?function=CRYPTO_INTRADAY&symbol=ETH&market=USD&interval=5min&outputsize=full&apikey=demo

**Comment by M3lon1** [comment]
Hey I came across the same problem and just played around a bit and built the function. I added the following function to the cryptocurrencies.py
```
    @av._output_format
    @av._call_api_on_func
    def get_digital_crypto_intraday(self, symbol, market, interval='5min', outputsize='compact'):

        _FUNCTION_KEY = 'CRYPTO_INTRADAY'
        return _FUNCTION_KEY, "Time Series Crypto ({})".format(interval), 'Meta `Data'
```

**Comment by Galsor** [comment]
@AlphaVantageSupport, I have a pull request I can submit to implement this feature request. 
What is the best way to contribute?
Best,

**Comment by danpetrow** [comment]
@Galsor feel free to submit a pull request. Once you do so we can review your code and if it all looks good push a change.

Thanks!

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.
