### ISSUE TITLE
Format problem in TechIndicators get.bbands

### ISSUE THREAD

**Issue by Nikita-boss** [RomelTorres/alpha_vantage#312]
Code:
get.bands gives different data format for different tickers.
bollinger_time_series = TechIndicators(key=api_key, output_format='pandas', indexing_type='data')
bollinger, meta_bollinger = bollinger_time_series.get_bbands(symbol=symbol, interval='daily', time_period=20, series_type='close', nbdevup=3, nbdevdn=3, matype=0)
...
sym = ['DECK']
data = alpha_vantage_daily_adjusted_simple(sym)
// Order: Real Middle Band; Real Upper Band; Real Lower Band 
sym = ['KAR']
data = alpha_vantage_daily_adjusted_simple(sym)
// Order: Real Middle Band; Real Lower Band; Real Upper Band

This is very inconvenient for data handling.

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.
