### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by alexblee808** [RomelTorres/alpha_vantage#314]
I am going through the AlphaVantage documentation and using their default code for the 'Intraday (Extended History).' I ran across the issue of missing minute-wise data for all time slices and am wondering if this is intentional.

Running this default code:

```
  import csv
  import requests
  
  replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
  CSV_URL = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY_EXTENDED&symbol=IBM&interval=15min&slice=year1month1&apikey=demo'
  
  with requests.Session() as s:
      download = s.get(CSV_URL)
      decoded_content = download.content.decode('utf-8')
      cr = csv.reader(decoded_content.splitlines(), delimiter=',')
      my_list = list(cr)
      for row in my_list:
          print(row)
```

I get the following abridged output:

```
['time', 'open', 'high', 'low', 'close', 'volume']
['2021-06-11 19:30:00', '151.21', '151.21', '151.13', '151.13', '661']
['2021-06-11 19:00:00', '151.1101', '151.1101', '151.1101', '151.1101', '400']
['2021-06-11 18:30:00', '151.44', '151.49', '151.44', '151.49', '300']
['2021-06-11 18:00:00', '151.28', '151.4', '151.28', '151.4', '1221']
['2021-06-11 17:00:00', '151.17', '151.17', '151.17', '151.17', '292']
['2021-06-11 16:30:00', '151.35', '151.35', '151.35', '151.35', '200']
['2021-06-11 16:15:00', '151.28', '151.28', '151.28', '151.28', '119363']
['2021-06-11 16:00:00', '151.215', '151.35', '151.03', '151.3', '280735']
                 ...         ...        ...       ...      ...      ...
```

Using the 15 minute slice data, it is seen that 7 time stamps are missing. By testing with different time intervals, it is seen that data provided by one may not be included in the other.

Do you have any suggestions for obtaining a more complete form of historical data, recommendations, or an explanation as to why this feature exists?

**Comment by AlphaVantageSupport** [comment]
@alexblee808, the data is not missing. The skipped timestamps mean there were no trading volume during the specific time periods.
