### ISSUE TITLE
Add Earning API endpoint to the fundamentals.py

### ISSUE THREAD

**Issue by danpetrow** [RomelTorres/alpha_vantage#319]
It doesn't look like there is support for the [EARNINGS API endpoint](https://www.alphavantage.co/documentation/#earnings) right now. Should be a simple pull to add this support to fundamentals.py

**Comment by AlphaVantageSupport** [comment]
Yes, there was one pull request on this endpoint and unfortunately it had some merge conflicts: 

https://github.com/RomelTorres/alpha_vantage/pull/285

Seeking community help on this!

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue due to a prolonged period since the last response was posted. Will re-open if needed.

**Comment by cbesel** [comment]
I think this is still a pending/open issue right? :( 
What was the merge conflict? The commit should just be additive/no changes so should be easy to resolve :)
