### ISSUE TITLE
greeting note from alphavantage raises an error

### ISSUE THREAD

**Issue by martin3000** [RomelTorres/alpha_vantage#321]
Reading currencies, alphavantage returns a greeting note ("welcome") and this note raises an error in alphavantage.py line 363.

```
            elif "Note" in json_response and self.treat_info_as_error:
                raise ValueError(json_response["Note"])
```
For this reason, alphavantage does not work in home assistant.

**Comment by olsson17** [comment]
can i work on this?

**Comment by 78Peace78** [comment]
Can I work on this

**Comment by 78Peace78** [comment]
#328

**Comment by AlphaVantageSupport** [comment]
Closing for now. Will re-open if there is community interest. Thanks!
