### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Haseeb90** [RomelTorres/alpha_vantage#323]
This keeps happening even if I'm putting 30 second sleeps in between the calls being made.
Here's the code I have
`
      from alpha_vantage.timeseries import TimeSeries
     ts = TimeSeries(key='KEY', output_format='pandas')

    def get_data(ticker):
        price_data, meta_data = ts.get_daily_adjusted(ticker, outputsize='full')
        price_data = price_data.rename(columns=column_translations)

        price_data = price_data.sort_values(['date'], ascending=True)

        return price_data`

ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
During handling of the above exception, another exception occurred:
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
During handling of the above exception, another exception occurred:
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by AlphaVantageSupport** [comment]
Closing for now. Will reopen if there is further community response. Thanks!
