### ISSUE TITLE
Understand Quote for LAME3.SAO - Help

### ISSUE THREAD

**Issue by Guiannes** [RomelTorres/alpha_vantage#325]
Hi, 

Could you please help me to understand an information?

I have already used the DAILY ADJUSTED (TIME_SERIES_DAILY_ADJUSTED) endpoint, but I see that one stock is different from other quote tools. 

For example: 

Stock - LAME3.SAO

For 2021-07-16 

Quote was closed in 20,56
![image](https://user-images.githubusercontent.com/93716045/140315537-bf6bbec3-0ae1-4ace-99ce-6d7edeccbc23.png)

But if we look in another quote tool, for this date was 8,66.

![image](https://user-images.githubusercontent.com/93716045/140315640-95bfc4cd-08e0-438d-aa51-358d044e368b.png)

Could you please help to understand that? something that I miss?!?

Thanks

**Comment by AlphaVantageSupport** [comment]
Closing for now. Will reopen if there is further community response. Thanks!
