### ISSUE TITLE
How to get VIX?

### ISSUE THREAD

**Issue by windowshopr** [RomelTorres/alpha_vantage#327]
Wondering if Alpha Vantage has extended intraday data for the VIX, and if so, what do I use as a symbol string to download it?

I've tried `"VIX"`, `"^VIX"` and `"%5EVIX"` as per [this answer](https://stackoverflow.com/questions/52162099/fetch-api-information-for-stocks-with-in-the-ticker-name).

**Comment by AlphaVantageSupport** [comment]
@windowshopr, could you please relay ticker-specific questions to support@alphavantage.co?

**Comment by windowshopr** [comment]
I'll send them an email sure, thanks! I put it here in the hopes that someone else who uses this tool might have some direction for me. I'll post the response here from AV when I get it.

**Comment by windowshopr** [comment]
VXX, that's the ETF closest to the VIX. Thanks!
