### ISSUE TITLE
No "outputsize" for DIGITAL_CURRENCY_DAILY

### ISSUE THREAD

**Issue by jacinthes** [RomelTorres/alpha_vantage#330]
Hi,

I'm trying to get all the available values for Cryptocurrencies but the outputsize option is not available here, so I'm only getting last 1000 entries/dates. I also tried using weekly and monthly data, but those also return limited results (144 weeks and 31 months). 

Any other possible solution?

Thanks!

**Comment by EliasOlie** [comment]
You're looking for something like they described on docs https://www.alphavantage.co/documentation/#crypto-intraday?

**Comment by jacinthes** [comment]
Thanks for the suggestion, but intraday only gets data for about a year back. I'm interested in daily values for as far back as alphavantage goes for crypto. By my logic digital_currency_daily should do that (the same as time_series_daily does for stock). Is there a way to get the value of BTC in lets say 2017?

**Comment by AlphaVantageSupport** [comment]
Closing for now. Will reopen if there is further community response. Thanks!
