### ISSUE TITLE
TimeSeries.get_daily() possibly retrieving incorrect stock data?

### ISSUE THREAD

**Issue by ChristopheBrown** [RomelTorres/alpha_vantage#332]
Hello, sorry if this doesn't classify as an API issue, but upon retrieving data for NVDA, some of the numbers seem a bit off? I can't find evidence that this stock was over $500, but this is what returns from throughout early last year.

Code snippet: 
`import alpha_vantage`
`from alpha_vantage.timeseries import TimeSeries`
`nvda, _ = ts.get_daily(symbol='NVDA', outputsize='full') `
`nvda.loc['2021-01-14']`

Output:
![image](https://user-images.githubusercontent.com/43019188/149570083-9f98f5ea-2345-4d06-85ef-710c3fd83fab.png)

**Comment by ChristopheBrown** [comment]
This seems to be the case from about January to July of 2021. Then the price drops down to expected values after July 2021. This is the graph of NVDA historic values.

![image](https://user-images.githubusercontent.com/43019188/149570614-e7517f6e-60d4-43b2-b5f0-0b56387e212f.png)

**Comment by AlphaVantageSupport** [comment]
The data should be correct as there is a difference between raw vs. adjusted data. See this issue: 

https://github.com/RomelTorres/alpha_vantage/issues/115

If still in doubt, please contact support@alphavantage.co

**Comment by rabongithub** [comment]
Hello, I have the same issues. Got hourly data by API, all volume does not match and randomly Open / High / Low / Close does not match. Also downloaded Demo data from them site (  https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY_EXTENDED&symbol=IBM&interval=60min&slice=year1month3&adjusted=false&apikey=demo ) - that also does not match.

**Comment by ChristopheBrown** [comment]
> The data should be correct as there is a difference between raw vs. adjusted data. See this issue:
> 
> #115
> 
> If still in doubt, please contact [support@alphavantage.co](mailto:support@alphavantage.co)

@rabongithub please see the link that @AlphaVantageSupport shared. It explains what is going on. 

I imagine issues like this will be opened frequently unfortunately, seeing as there is a paywall for the information many are after.

**Comment by rabongithub** [comment]
Did you get the right volume ? volume has nothing to do with raw or adjusted  !
