### ISSUE TITLE
Numpy ImportModuleError when deploying to AWS Lambda via zappa serverless

### ISSUE THREAD

**Issue by openfieldbook** [RomelTorres/alpha_vantage#335]
I receive an `ImportModuleError` when deploying a package to AWS Lambda using alpha_vantage as a dependency. I do not know why, but I'm certain it relates to alpha_vantage. I've left more detail [on this stackOverflow post](https://stackoverflow.com/questions/73991967/python-why-is-this-setup-py-file-causing-an-importmoduleerror-numpy-alp).

I have no problems running the alpha_vantage code locally and the issue may ultimately revolve around the way zappa pre-packages the zip file for deployment onto AWS. Nevertheless, I don't seem to have this problem with any other dependency, including pandas itself.

**Comment by AlphaVantageSupport** [comment]
Closing for now. Will reopen if there is further community response. Thanks!

**Comment by AlphaVantageSupport** [comment]
Closing for now. Will reopen if there is further community response. Thanks!
