### ISSUE TITLE
Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY_ADJUSTED.

### ISSUE THREAD

**Issue by xxccy668** [RomelTorres/alpha_vantage#341]
Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY_ADJUSTED.
How to solve this question?

**Comment by AlphaVantageSupport** [comment]
Please contact support@alphavantage.co since this is a server-side error message, rather than specific to this library. Thanks!
