### ISSUE TITLE
Project dead(?) / alternative package

### ISSUE THREAD

**Issue by gboehl** [RomelTorres/alpha_vantage#346]
This project seems dead with no replies to issues and quite a number of open pull requests. Some more recent functionality (eg. the `month` keyword) is missing and the latest larger commits are also several years ago.

In case anyone is interested, I created an alternative python package for the Alpha Vantage API which is well documented and should be quite straightforward to use: 

https://github.com/gboehl/alpyvantage

**Comment by this-josh** [comment]
Nice work, `alpyvantage` for me.

**Comment by AlphaVantageSupport** [comment]
@gboehl, thank you for the contribution. Instead of creating a brand new repo https://github.com/gboehl/alpyvantage, are you open to becoming a maintainer for this repo?

**Comment by gboehl** [comment]
@AlphaVantageSupport thanks for the request. Is there any chance to directly get in touch?

**Comment by AlphaVantageSupport** [comment]
Certainly. Could you please reach out to support@alphavantage.co? Thank you

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this issue as we explore the community contributors for this repo.
