### ISSUE TITLE
Functions not available via free account

### ISSUE THREAD

**Issue by artconscious** [RomelTorres/alpha_vantage#349]
According to tests and documentation on https://www.alphavantage.co/documentation/#dailyadj the API call TIME_SERIES_DAILY_ADJUSTED and therefor *get_daily_adjusted* is no longer available via the free account. Not sure if this is mentioned somewhere in the documentation.

**Comment by AlphaVantageSupport** [comment]
Yes, the official API documentation mentions which API endpoints are vs. are not premium prominently: https://www.alphavantage.co/documentation/#dailyadj.
