### ISSUE TITLE
Unclear how to add entitlement for realtime | delayed

### ISSUE THREAD

**Issue by TheCrockett** [RomelTorres/alpha_vantage#354]
I'm told by support that my URL query needs to have the 

&entitlement=delayed or &entitlement=realtime 

I looked in
https://github.com/RomelTorres/alpha_vantage/blob/develop/alpha_vantage/timeseries.py

But did not see an obvious way to add

**Comment by esalto98** [comment]
Do you have a premium subscription for the underlying [alphavantage](https://www.alphavantage.co/premium/) API ?

if so then this wrapper looks like it doesn't handle that additional parameter which would be needed to utilize the paid benefits the subscription offers.

**Comment by AlphaVantageSupport** [comment]
Please feel free to re-open if you would like to contribute a refresh to the library!

**Comment by TheCrockett** [comment]
@AlphaVantageSupport 

I'm a bit confused why this was closed. 

My Alpha Vantage support team directed me to this repo to get the necessary changes implemented.

**Comment by AlphaVantageSupport** [comment]
@TheCrockett, the Alpha Vantage support team recommended that you integrate with the **official** API (https://www.alphavantage.co/documentation/) directly. This Python library is merely a wrapper and is not officially maintained by Alpha Vantage.
