### ISSUE TITLE
unexpected keyword argument 'month' in get_intraday()

### ISSUE THREAD

**Issue by StasBard** [RomelTorres/alpha_vantage#355]
Hello, 

Alpha Vantage [API](https://www.alphavantage.co/documentation/#intraday) clearly states that TIME_SERIES_INTRADAY function has an optional parameter 'month':
> By default, this parameter is not set and the API will return intraday data for the most recent days of trading. You can use the `month` parameter (in YYYY-MM format) to query a specific month in history. For example, `month=2009-01`. Any month in the last 20+ years since 2000-01 (January 2000) is supported.  

So, why do get a TypeError using this parameter: 'TimeSeries.get_intraday() got an unexpected keyword argument 'month''

Here is my code:
```
from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries(key='my_key', output_format='pandas')
ts, _ = ts.get_intraday(symbol = 'IBM', interval = '5min', month = 2023-11, outputsize = 'full', adjusted = False, datatype = 'csv')
```

By the way, the `adjusted` parameter will also raise an error!

**Comment by StasBard** [comment]
I assume this parameter merely hasn't been realised in this particular library...

**Comment by esalto98** [comment]
looks like the implementation of the wrapper function only accepts the required params for the corresponding function of main api

**Comment by AlphaVantageSupport** [comment]
Please feel free to re-open if you would like to contribute a refresh to the library!

**Comment by bastienjalbert** [comment]
@AlphaVantageSupport, new parameters (month & extended_hours) has been added in this pull request : https://github.com/RomelTorres/alpha_vantage/pull/362

**Comment by AlphaVantageSupport** [comment]
Thank you!

**Comment by bastienjalbert** [comment]
May you publish a new version/tag ? So I can use pip registry instead of local version to access the feature :)

**Comment by AlphaVantageSupport** [comment]
Do you mind contacting support@alphavantage.co? They will be able to discuss the nuances / details with you.
