### ISSUE TITLE
I can not make it work

### ISSUE THREAD

**Issue by Tonterias** [RomelTorres/alpha_vantage#356]
I have added my api key but it does not work. Is there a video or some screenshoots to make it easier for non tech users in windows?

Thanks, probably it's great

Traceback (most recent call last):
  File "c:\DATOS\BasuraTemporal\Portatil\Programación\Python\alphavantage\alpha_vantage\alpha_vantage\timeseries.py", line 1, in <module>
    from .alphavantage import AlphaVantage as av
ImportError: attempted relative import with no known parent package

**Comment by dtoralg** [comment]
Calling ".alphavantage" is generating an issue as it is not a proper way to import the package. The . at the beginning is understood as a relative reference, therefore failing.

You have some examples how to call the different modules on the README file. P.eg.:

from alpha_vantage.fundamentaldata import FundamentalData
or
from alpha_vantage.timeseries import TimeSeries

**Comment by AlphaVantageSupport** [comment]
Closing due to lack of responses.
