### ISSUE TITLE
Support for 'News and Sentiments'

### ISSUE THREAD

**Issue by usapkota** [RomelTorres/alpha_vantage#357]
Is it true that we do not currently support 'News and Sentiments'? or I am too dumb to figure it out?

![image](https://github.com/RomelTorres/alpha_vantage/assets/17654644/54fa1106-e114-4a06-8989-e7c1ee1c29b6)

**Comment by AlphaVantageSupport** [comment]
Closing this issue due to limited response. We welcome contributions to this capability. Thanks!

**Comment by usapkota** [comment]
I have a pull request adding these functionalities. https://github.com/RomelTorres/alpha_vantage/pull/358
