### ISSUE TITLE
Sector Performance stopped working

### ISSUE THREAD

**Issue by pythonian1027** [RomelTorres/alpha_vantage#359]
Sector Performances gives the following error: 

from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.sectorperformance import SectorPerformances
API_key =API_key
ts = TimeSeries(key=API_key, output_format = 'pandas')
data, meta = ts.get_daily_adjusted('NVDA', outputsize = 'full')
#%%
sp = SectorPerformances(API_key, output_format='pandas')
data, meta_data = sp.get_sector()
# %%

Error: 
    355 if not json_response:
--> 356     raise ValueError(
    357         'Error getting data from the api, no return was given.')
    358 elif "Error Message" in json_response:
    359     raise ValueError(json_response["Error Message"])

ValueError: Error getting data from the api, no return was given.

**Comment by AlphaVantageSupport** [comment]
Closing this for now, as the issue seems to be due to the API supportability rather than specific to this python wrapper.
