### ISSUE TITLE
Batch Stock Quotes 

### ISSUE THREAD

**Issue by Engietoday** [RomelTorres/alpha_vantage#36]
Can you provide an example on how to do batch quotes?

**Comment by RomelTorres** [comment]
Hi @Engietoday, I am sorry for the late reply. What do you mean by batch quotes?

**Comment by Engietoday** [comment]
Hello, thanks for getting back. So in https://www.alphavantage.co/documentation/ there is a section on Batch Stock Quotes, how do I use that?

**Comment by RomelTorres** [comment]
@Engietoday I hadn't seen that call before (I have been so busy with other things). I am going to implement the call in the next days.

Happy holidays
Romel

**Comment by RomelTorres** [comment]
@Engietoday  I finally implemented the call. It is already commited.
