### ISSUE TITLE
SectorPerformance import not working properly 

### ISSUE THREAD

**Issue by cybergeekgyan** [RomelTorres/alpha_vantage#360]
I have tried running the sectorperformance method and every time I run this I get an error;

*ValueError: Error getting data from the api, no return was given.*

<img width="647" alt="Screenshot 2024-01-18 at 8 07 06 AM" src="https://github.com/RomelTorres/alpha_vantage/assets/56320349/f270663f-3539-41ae-9a6d-ca759fb6069f">

**Comment by AlphaVantageSupport** [comment]
Closed due to the lack of take-up. Will revisit if there are new updates. Also, this seems to be an API question, instead of specific to this Python wrapper.
