### ISSUE TITLE
Net account receivables data for ALB differs from what I get from other data sources

### ISSUE THREAD

**Issue by olevasseur** [RomelTorres/alpha_vantage#361]
This is what I get from my terminal: 
![image](https://github.com/RomelTorres/alpha_vantage/assets/65046034/1a32daef-c0c4-40d4-b858-20808a8028e2)
On the image above, the latest data is the first row and is dated from 2023-12-31. The second row would be for 2022-12-31 and so on.

This is what I get from another source:
![image](https://github.com/RomelTorres/alpha_vantage/assets/65046034/f403b19f-232c-43f8-b1f1-886bc302c1a5)
On the image above, the latest data is on the right and is data from 2022. The second column from the right would be for 2021 and so on.

I have double checked the net account receivables for ALB from other sources and they seem to also be different from what I get with alpha vantage. I checked other data that I got from alpha vantage for ALB, such as cash and cash equivalents or total current assets and it is similar to what I could get from other data sources. 

This is how I am using alpha vantage from my terminal:
```
from alpha_vantage.fundamentaldata import FundamentalData
fd = FundamentalData(key='my_redacted_key', output_format='pandas', indexing_type='date')
```

Any idea on why the data for net account receivables is so different? Thanks a lot!

**Comment by AlphaVantageSupport** [comment]
Closing this temporarily due to lack of response. Will re-open as needed. Thanks!
