### ISSUE TITLE
Problem of API missing. get_intraday_extend 

### ISSUE THREAD

**Issue by 731315163** [RomelTorres/alpha_vantage#364]
Optional: month

By default, this parameter is not set and the API will return intraday data for the most recent days of trading. You can use the month parameter (in YYYY-MM format) to query a specific month in history. For example, month=2009-01. Any month in the last 20+ years since 2000-01 (January 2000) is supported.   
**Why can the 'ts.get_intraday_extend 'api only obtain data from the last two years of a specified month, while the official support is for 20 years?**

**Comment by 731315163** [comment]
@av._output_format
    @av._call_api_on_func
    def get_intraday_extended(self, symbol, interval='15min', slice='year1month1'):
        """ Return extended intraday time series in one csv_reader object.
        It raises ValueError when problems arise

        Keyword Arguments:
            symbol:  the symbol for the equity we want to get its data
            interval:  time interval between two conscutive values,
                supported values are '1min', '5min', '15min', '30min', '60min'
                (default '15min')
            slice: the trailing 2 years of intraday data is evenly divided into
                24 "slices" - year1month1, year1month2, ..., year2month12
        """
        _FUNCTION_KEY = "TIME_SERIES_INTRADAY_EXTENDED"
        return _FUNCTION_KEY, "Time Series ({})".format(interval), 'Meta Data'

**Comment by AlphaVantageSupport** [comment]
Temporarily closing this due to lack of activities. Will reopen as needed.
