### ISSUE TITLE
Getting TypeError on basic commands

### ISSUE THREAD

**Issue by awlee01** [RomelTorres/alpha_vantage#37]
When running: 
`ts = TimeSeries(key='MY_API_KEY', output_format='pandas')`
`data, meta_data = ts.get_intraday(symbol='MSFT',interval='1min', outputsize='full')`
`data['close'].plot()`
`plt.title('Intraday Times Series for the MSFT stock (1 min)')`
`plt.show()`

I am receiving a `TypeError: argument of type 'int' is not iterable` command. Not sure why this is, I'm copying the exact code from the documentation.

I receive the same error for everything except for `SectorPerformances`

**Comment by RomelTorres** [comment]
Hello @awlee01, are you using the 1.6.0 version? It could be gay some bug was not catched before releasing :(. I am on a trip now but I will check as soon as I get the chance. In the meantime, you can try version 1.3.6  that for sure is stable.

Sorry for the issue,

Romel

**Comment by RomelTorres** [comment]
Hi @awlee01, I just tested the calls with the version 1.6.0 and it all worked out fine for me, can I have more details about your set up? You can see the results in this repository: https://github.com/RomelTorres/av_example

**Comment by RomelTorres** [comment]
Hi @TheBhat 

What you mention seems to be related to issue #41 

At the moment I cannot figure out why this happens on some setups. Did you try in python3?
