### ISSUE TITLE
Date as index for pandas dataframe

### ISSUE THREAD

**Issue by SteffenNa** [RomelTorres/alpha_vantage#38]
Hello. will the recent update the index column is now an int index. Would be great if there would be an option to have the date as index again. Makes zero sense for me to have an integer index. Thanks for your consideration.
Steffen

**Comment by RomelTorres** [comment]
Hi @SteffenNa, i will be travelling for a few weeks but I will hopefully have time to address this. I am just going to make it configurable so that the integer and date index behaviour are possible. It is a rather simple change (if you want to tackle it pull requests are more than welcome) I think, the best is to document that behaviour properly in the readme ;) 

Saludos
Romel

**Comment by SteffenNa** [comment]
Great. thanks Romel. Enjoy your travels and be safe!

**Comment by PeterAVG** [comment]
But it does not work now when running the suggested commands on front page. I get the error: 
argument of type 'int' is not iterable

How can I circumvent this?
/Peter

**Comment by RomelTorres** [comment]
@PeterAVG can you let me know about your set up? Someone had this error too but I don't get it reproduced. There is already an issue opened up on the same error. Best regards, Romel

**Comment by PeterAVG** [comment]
I get the error by running your suggested code in the plotting section in readme.md:
`ts = TimeSeries(key=api_key, output_format='pandas')
data, meta_data = ts.get_intraday(symbol=stock,interval='1min', outputsize='full')`
I am using python 3.6.1.

**Comment by RomelTorres** [comment]
@PeterAVG, Ok I will try to have a look again and see  what I am missing.

**Comment by RomelTorres** [comment]
Hi @SteffenNa, I just pushed the changes to the develop branch. If you want, you can install the development branch version and let me know your thoughts. It has two changes: the indexing and the column naming of the pandas data frames are now the originals produced by the alpha vantage call (I am not removing anything to make it look prettier.)

**Comment by SteffenNa** [comment]
Thanks Romel will try to take a look ASAP. really swamped though these days....

**Comment by SteffenNa** [comment]
Hi Romel.
Happy New Year! Hope you had a nice holiday.

Just installed the upgrade to 1.8.0 Unfortunately it does not seem to work:

In [105]: from alpha_vantage.timeseries import TimeSeries

In [106]: ts = TimeSeries(key=API_key, output_format='pandas', indexing_type='da
     ...: te', retries=9)
     ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-106-608b2b5ad4c4> in <module>()
----> 1 ts = TimeSeries(key=API_key, output_format='pandas', indexing_type='date', retries=9)

TypeError: __init__() got an unexpected keyword argument 'indexing_type'

Can you please take a look?

**Comment by RomelTorres** [comment]
Hi, can you verify that the installation of the 1.8.0. Succeeded, it looks like it is not properly installed because the latest version with the indexing type works for me... with the version 1.8.0 installed.

**Comment by SteffenNa** [comment]
weird. installation seems ok. anyways. doesn't matter much as it works as long as default index is 'Date'. May i ask why you changed the column headers? In my humble opinion your previous solution ('open', 'high', 'low', 'close', ...) was superior and consistent with what you get back from other data providers.

**Comment by RomelTorres** [comment]
hi @SteffenNa, I should not modify the content of the data provided by alpha vantage even the names of columns, also doing that might lead to errors on other calls. Using their names is consistent with what alphavantage offers.
