### ISSUE TITLE
Anaconda can't find package 

### ISSUE THREAD

**Issue by Filiprb** [RomelTorres/alpha_vantage#39]
Hello, 

I'm trying to install the alpha_vantage package but I'm having some trouble. When trying to install it, the package can't be found. 

"
C:\ conda install alpha_vantage

Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:

  - alpha_vantage
"

What am I doing wrong?

**Comment by RomelTorres** [comment]
Hello @Filiprb, you can't install it with conda because I didn't push it to any conda channels. Nevertheless simply source your conda environment and inside do pip install alpha_vantage.

Saludos Romel
