### ISSUE TITLE
New version cannot address dataframe values anymore

### ISSUE THREAD

**Issue by miked63017** [RomelTorres/alpha_vantage#40]
Hi,

Thanks for the great module. I noticed since the new version you cannot address the data.column.values anymore without error. For example:
```
ts = TimeSeries(key=self.args.api_key, retries=3, output_format='pandas')
data, meta_data = ts.get_daily(symbol=self.args.symbol,outputsize='full')
print data.open.values
print data.close.values
```

These methods were really convenient to use with ta-lib. It seems in the new version the colum names are more like:
```
1. open
```
instead of just ```open```
```
4. close
```
instead of just ```close```

I guess there used to be something that stripped those off?

Thanks!

**Comment by RomelTorres** [comment]
Hi @miked63017 yes i had to remove that functionality because it causes other issues and I should not modify alpha vantage original content, therefore I changed that to be as they originally give it. I hope it does not cause you headaches :)

**Comment by miked63017** [comment]
Thanks for the quick response @RomelTorres, is there another easy way to get the .values method to work? I couldn't figure it out, but not a pandas expert either.

**Comment by RomelTorres** [comment]
@miked63017 you can do ```print(data['1. open'])``` should give you a data frame with the values u want.

**Comment by miked63017** [comment]
I am using it with ta-lib abstract api as shown here https://github.com/mrjbq7/ta-lib/blob/master/README.md

The print statements we're just as a quick example. I think may it will work there too with some tweaks, will give it a test tomorrow. Thanks again @RomelTorres !

**Comment by miked63017** [comment]
Sorry stupid phone autocorrect lol

**Comment by RomelTorres** [comment]
Hi @miked63017, did you manage to ork around this issue?

**Comment by miked63017** [comment]
Sorry, haven't had time to look. I just pinned the previous version for now. Feel free to close though if this change is intentional, I will work around it. I just thought it was a bug...
