### ISSUE TITLE
CSV output error

### ISSUE THREAD

**Issue by onefarad** [RomelTorres/alpha_vantage#42]
Hello,

The CSV output of the module is actually a csv reader object. If trying to iterate through it it will return each character of a line, not the fields.

The problem seems to be at the line 275 of alphavantage.py:
            csv_response = csv.reader(url_response)

In order for the reader to work correctly, the line should be:
            csv_response = csv.reader(url_response.splitlines())

Reproducing the issue:
```
#!/usr/bin/env python
from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries(key='API_KEY', retries=3, output_format='csv')
data_m15, meta_data_m15 = ts.get_intraday(symbol='GE', interval='15min', outputsize='full')
print meta_data_m15
print data_m15
for line in data_m15:
    print line

```

Output:
```
None
<_csv.reader object at 0x287b4b0>
['t']
['i']
['m']
['e']
['s']
['t']
['a']
['m']
['p']
['', '']
['o']
['p']
['e']
['n']
['', '']
['h']
['i']
['g']
['h']
['', '']
['l']
['o']
['w']
['', '']
['c']
['l']
['o']
['s']
['e']
['', '']
['v']
['o']
['l']
['u']
['m']
['e']
[]
[]

```

Output with the suggested change:
```
None
['timestamp', 'open', 'high', 'low', 'close', 'volume']
...

```

Thanks for the great work you did on the module.

**Comment by RomelTorres** [comment]
Hi @onefarad, thanks for the issue. Do you feel like trying a PR? I mean I can fix it myself but if you want you can do the PR :)

**Comment by onefarad** [comment]
Hi Romel,

It's ok, I'll try it. Gotta start somewhere. :)

One more issue I found is that when a CSV retrieval fails, the server will send actually a JSON. Example output for a symbol that does not exist:
```
{
    "Error Message": "Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_INTRADAY."
}

```

Probably will have to add some error checking (if the answer is json and not csv) in that area and raising an exception.

**Comment by RomelTorres** [comment]
Yes you can check the alphavantage.py

**Comment by RomelTorres** [comment]
Yep, good work! If you want to give it a try at handling the error messages you are welcome to give it a try. I did not write any unittests for the csv part of the library. Maybe I find time to improve on that later.

Thanks :D

**Comment by onefarad** [comment]
I'll have a look at error handling when I'll get some time. :) Want also to add to the documentation the CSV usage.
