### ISSUE TITLE
Time Series for Daily and Weekly

### ISSUE THREAD

**Issue by billtf** [RomelTorres/alpha_vantage#46]
This is a great project, so far I can get the intraday and techindicators to run with no problem. I was wondering how to run the daily and weekly data. I suspect this can be done by rolling up the smaller timeframes in Pandas, but wasn't sure. Thanks for your help.

**Comment by RomelTorres** [comment]
There are daily and weekly functions already that offer you the pandas data frames you are looking for. Am I not understanding something?

BR
Romel

**Comment by billtf** [comment]
In your examples you provided I didn’t see a way to do daily or weeklys, this seems to be calling the intraday function of the alphavantage api. 
From the alphavantage api documentation webpage I am trying to call the function=TIME_SERIES_DAILY, you probably built this out (I am just not seeing it).

from alpha_vantage.timeseries import TimeSeries
ts = TimeSeries(key='YOUR_API_KEY', output_format='pandas')
data, meta_data = ts.get_intraday(symbol='MSFT',interval='1min', outputsize='full')

Thanks

**Comment by RomelTorres** [comment]
Hi @billtf I have another repo called av_examples, check it out. But you can also check the documentation, where all the calls are outlined. ;) The link for all of this are in the readme file :)

**Comment by billtf** [comment]
i see it now....simply changing the function call from "get_intraday" to
"get_daily" does the trick (and removing the interval variable)..

data, meta_data = ts.get_daily(symbol='MSFT', outputsize='full')
