### ISSUE TITLE
OTC and PINK sheet

### ISSUE THREAD

**Issue by JeremieGauthier** [RomelTorres/alpha_vantage#47]
Could you tell me if I could pull OTC and PINK sheet data ($Volume, Volume, # trades, bid and ask) with Alpha Vantage Api? For instance, could I pull the last price for HEMP, MJNA, PHOT and POTN?

**Comment by RomelTorres** [comment]
Hi @JeremieGauthier. Honestly I have no idea :) I am not a finance guy just a python developer. But you can go to the alpha vantage forums they definitely know how to answer you better than I do.

All the best
Romel

**Comment by JeremieGauthier** [comment]
Could you try fetching HEMP for instance for me?

**Comment by JeremieGauthier** [comment]
I found my answer in testing out, thanks! Could you tell me if it is possible of doing a bulk download with something like data, meta_data = ts.get_intraday('HEMP', 'PHOT', 'MJNA')?

**Comment by robertpotts** [comment]
Hi,

I believe that he covers bulk downloads of current stock prices in his
example repository.  https://github.com/RomelTorres/av_example

I hope that helps!


-------------------------------------------


Robert E. Potts, III, Ph.D.

pottsre@ornl.gov

Graduate Research Assistant

Advisor: Sarah M. Cousineau

Accelerator Physics Group

Spallation Neutron Source

Oak Ridge National Laboratory


Mailing Address:

Robert Potts

U.S. DOE c/o UT Battelle, LLC

PO BOX 2008 MS6461

Oak Ridge National Lab/SNS Site

Oak Ridge, TN 37830



rpotts1@vols.utk.edu

Graduate Research Assistant

Department of Physics and Astronomy

University of Tennessee, Knoxville

-------------------------------------------

**Comment by RomelTorres** [comment]
Hey @JeremieGauthier, Yes as @robertpotts  said I have a small example in the other repo. If it is in the original Alphavantage api, then it is in my code too, and if it is not you post me an issue and it will be.

BR
Romel
