### ISSUE TITLE
Hong Kong Stock not working

### ISSUE THREAD

**Issue by Harryye01** [RomelTorres/alpha_vantage#49]
Dear RomelTorres
      Thank  you for the great package. I used it really comfortably. However, whenever I use 

symbol = '0005.HK'

It doesn't work and gives Valueerror.
0005.HK is a stock in Hong Kong, and it doesn't work for some reason. 
I can use the symbol in normal api documentation from the official website.

Details: 
line 173, in _format_wrapper(self, *args, ** kwargs)
line 158, in _call_wrpper_ 
retry wrapper 
raise ValueError(str(error_message))
ValueError Invaild API call. Please retry or ......

Thank you very much.

**Comment by RomelTorres** [comment]
Hi @Harryye01, I am sorry I have not been more active lately (lots of work and projects at the same time) Did you solve this? This you check the symbol on a browser?
