### ISSUE TITLE
Installation: Access is denied

### ISSUE THREAD

**Issue by dchebows** [RomelTorres/alpha_vantage#5]
During the installation of the package I reach a point where it stops due to access being denied.  I have confirmed that there is no administrator (administrator disabled).  I am running Windows 7, Python36-32.  Any help would be greatly appreciated.  Thank you.

![image](https://cloud.githubusercontent.com/assets/28958956/26460809/e8ee7e8c-4148-11e7-8dd2-dcbb986a07a4.png)

**Comment by RomelTorres** [comment]
Hi there, wow I haven't tested the package under windows so far... But i think a colleague used it with conda without problems. Would you be so kind as to test if you can install simple json without any problems. Also what procedure are you using for he installation?

Best regards
Romel

**Comment by RomelTorres** [comment]
I hope you have found a solution to your issue @dchebows. I am closing the issue now, if anything, let me know and we can reopen it. 

Best Regards
