### ISSUE TITLE
Data are being skipped

### ISSUE THREAD

**Issue by BhoopalanI** [RomelTorres/alpha_vantage#52]
Hi, 

I'm using alpha_vantage to access Indian NSE market. Check this URL: 

https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=INFY.NS&interval=30min&outputsize=full&apikey=*****

It misses out on data of 2018-03-14, 2018-03-15 and 2018-03-16. 

I even posted this on the website community (second post on that thread): 
https://www.alpha-vantage.community/post/missing-prices-for-one-date-for-stock-on-italian-market-9683004

When I posted that, only March 14th and 15th data was missing but 16th was available. (Probably because it was 16th itself). I think it starts to skip data after March 13 and shows the data only of the current date. Please check this.

**Comment by RomelTorres** [comment]
Hi @Bhoopalanl I cannot check this since this is API related. You have to contact Alphavantage directly (as you already did and wait for their answer)

Best regards,
Romel
