### ISSUE TITLE
 Inconstiney in SYMOBOL for Indian stock exchnage 

### ISSUE THREAD

**Issue by me-shivaprasad** [RomelTorres/alpha_vantage#53]
Hi While using the api found the inconsistent behavior some symbol work from TIME_SERIES_DAILY but the same symbol does not work when I use it in TIME_SERIES_INTRADAY

example NSE index symbole (NSEI took from yahoo as suggested from others) works in TIME_SERIES_INTRADAY, not in TIME_SERIES_DAILY

ex

https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=NSEI&interval=5min&outputsize=full&apikey=key

https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol= NSEI&outputsize=full&apikey=key

Another example of stock PVR code PVR.NS (as per yahoo finance) works for daily but not work for intraday

https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=PVR.NS&interval=5min&outputsize=full&apikey=key

**Comment by RomelTorres** [comment]
Hi @me-shivaprasad for inconsistencies in the alpha vantage api, you have to write to them personally. This is just a python wrapper to wrap around their API.
