### ISSUE TITLE
[feature request] save API key?

### ISSUE THREAD

**Issue by ifmihai** [RomelTorres/alpha_vantage#54]
Just found out alpha_vantage, and installed python module.
Not sure if i rushed to post this issue, but here i go:

Wouldn't be more elegant to save API key with some function like alpha_vantage.setAPIkey("apikey")
?
Quandl does this, and it's quite nice, not having to enter api key each time.
quandl.ApiConfig.api_key = "YOUR_KEY_HERE"

not sure where quandl saves the key though

anyway,
is this feature present in alpha_vantage?
I've looked around, but found nothing about this

**Comment by RomelTorres** [comment]
Hi @ifmihai the feature is not present. Maybe I could implement it (I am kinda busy with other projects ATM but I could lok at the best way of doing this later) what I do and should work for you (many people do it this way) is to save the key as an environment variable and use it as `os.environ["API_KEY"]` for example. You can check how to set environment variables in your operating system of choice. If you fancy tackling the problem yourself I am always happy with pull requests ;)

**Comment by Rishk** [comment]
@RomelTorres Do you think the best way of doing this would be to add the option of storing the API key in a configuration file?

We could use the configparser module; I have tested compatibility using 2.7.12 and 3.6.4, both work well.

I would be happy to implement this if so.

**Comment by Rishk** [comment]
@addisonlynch Thanks for the response, that makes sense. 

Based on this, do you think it would be worth adding a check for a specific environment variable, e.g. `AV_API_KEY` or `ALPHA_VANTAGE` if no key is specified? This should provide a more convenient way of storing the API key if users want it.

@RomelTorres

**Comment by addisonlynch** [comment]
@Rishk exactly! Here's an example implementation that I used for the [Pandas Datareader](https://github.com/pydata/pandas-datareader) AV reader:

https://github.com/pydata/pandas-datareader/blob/da18fbd7621d473828d7fa81dfa5e0f9516b6793/pandas_datareader/av/__init__.py#L17-L29

I can create a quick pull which will take care of it, if that works.
