### ISSUE TITLE
Cannot import name TimeSeries

### ISSUE THREAD

**Issue by jwallden** [RomelTorres/alpha_vantage#6]
Hello!

After a fresh `pip install alpha_vantage` in a virtualenv with python 3.5 I'm trying to do the example:

`from alpha_vantage.timeseries import TimesSeries`
`ts = TimesSeries(key='YOUR_API_KEY')`  
`data, meta_data = ts.get_intraday('GOOGL')`

However, when running this i get:

`Traceback (most recent call last):`
  `File "av.py", line 1, in <module>`
    `from alpha_vantage.timeseries import TimeSeries`
`ImportError: cannot import name 'TimeSeries'`

I also tried installing from source with the same result and also with python 2.7.

**Comment by RomelTorres** [comment]
Hi there, I am sorry but when I wrote the package. I for a reason unknown to me, wrote:
**Class TimesSeries**, instead of **Class TimeSeries** (with an extra s in the middle) , your problem is that you are trying to import TimeSeries instead of the TimesSeries.  I will fix that in the next, release.

For now, please import **from alpha_vantage.timeseries import TimesSeries**

Best Regards,

Romel

**Comment by jwallden** [comment]
Thanks for the fast response! Got it working :+1: 
At first I didn't give my api key and it seems to crash
Traceback (most recent call last):
  File "av.py", line 4, in <module>
    data, meta_data = ts.get_daily('STO:SAAB-B', outputsize='compact')
  File "/home/joakim/.virtualenvs/alphavantage/lib/python3.5/site-packages/alpha_vantage/alphavantage.py", line 152, in _format_wrapper
    json_response, data_key, meta_data_key = func(self, *args, **kwargs)
  File "/home/joakim/.virtualenvs/alphavantage/lib/python3.5/site-packages/alpha_vantage/alphavantage.py", line 138, in _call_wrapper
    return self._handle_api_call(url), data_key, meta_data_key
  File "/home/joakim/.virtualenvs/alphavantage/lib/python3.5/site-packages/alpha_vantage/alphavantage.py", line 76, in _retry_wrapper
    raise ValueError(err)
UnboundLocalError: local variable 'err' referenced before assignment

Maybe another issue for that?

**Comment by RomelTorres** [comment]
hey, yes, can you please put it on a separate issue. So that is clear for others. I will look closer to it.

Thanks
