### ISSUE TITLE
weird error - could not debug it

### ISSUE THREAD

**Issue by koren88i** [RomelTorres/alpha_vantage#62]
I am sorry for posting here, this is a last resort

ValueError: Thank you for using Alpha Vantage! Please kindly contact support@alphavantage.co if you would like to have a higher API call volume

I get this error even when doing sleep(5) between api calls. after like 5 - 6 symbol calls.

I got a different code working with 50 threads that does not make this error...

weird.... 

any one?

**Comment by TaroNguyen** [comment]
In my opinion, your number of calls has reached the hard limit set by Alpha Vantage. Maybe 200 calls /hour, I'm not sure, as far as my understanding, they aren't specific about that limit. Why don't you try again after 1 hour or even 1 day?

**Comment by koren88i** [comment]
When trying to run a different script when 50 threads with 50 api calls each - it's working... 

That's why I said it's weird..
