### ISSUE TITLE
Add request timeout argument

### ISSUE THREAD

**Issue by ecourreges** [RomelTorres/alpha_vantage#63]
Hello Romel,
The api calls have no request timeout set, and alpha vantage tends to timeout or cease to function on the weekends, my programs running every minute get stuck.
I would like the possibility to set a timeout for all calls, and in any case i would at least set the default to a reasonnable 30 or 60s instead of the current unlimited value.

I am not an experienced python dev, that’s why i haven’t made a pull request.

P.S: Thanks for the very practical lib, that got me into using pandas for cryptocurrency algorithms.

**Comment by addisonlynch** [comment]
@RomelTorres I can take care of this as well. Similar to the implementation we use for Pandas Datareader.

**Comment by addisonlynch** [comment]
Also, any interest in changing to the ``requests`` library and using session handlers? Would be happy to implement this as well. I have the time to work on it this week. Let me know what works best for you.

**Comment by RomelTorres** [comment]
Hi @addisonlynch the ```requests``` library was introduced in version 1.8.0 I reckon ;). Feel free to implement the timeout and send me a PR also about the sessions, can you elaborate on that? Maybe it is a good idea if you feel like implementing it I am all ears.

BR Romel

**Comment by addisonlynch** [comment]
@RomelTorres sorry, totally missed that ``requests`` was already implemented! I'll do the timeouts first. The sessions just allow for caching with ``requests-cache``.
