### ISSUE TITLE
'alpha_vantage' is not a package

### ISSUE THREAD

**Issue by tmdag** [RomelTorres/alpha_vantage#64]
Hi!

I saw people had similar issues which was resolved by updating to latest version 0.1.9.
I am currently trying to install/run your latest version 2.0.0 and getting the issue:

```
>  sudo pip install alpha_vantage
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting alpha_vantage
  Using cached https://files.pythonhosted.org/packages/90/62/c48ff7e3c7b6d7d6b50aefa48166abc3617fa724dba4bb51dab27c6288e4/alpha_vantage-2.0.0.tar.gz
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from alpha_vantage)
Requirement already satisfied: simplejson in /usr/lib64/python2.7/site-packages (from alpha_vantage)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests->alpha_vantage)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests->alpha_vantage)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->alpha_vantage)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests->alpha_vantage)
Installing collected packages: alpha-vantage
  Running setup.py install for alpha-vantage ... done
Successfully installed alpha-vantage-2.0.0
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

>  sudo pip3 install alpha_vantage
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting alpha_vantage
  Using cached https://files.pythonhosted.org/packages/90/62/c48ff7e3c7b6d7d6b50aefa48166abc3617fa724dba4bb51dab27c6288e4/alpha_vantage-2.0.0.tar.gz
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from alpha_vantage)
Requirement already satisfied: simplejson in /usr/local/lib64/python3.6/site-packages (from alpha_vantage)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->alpha_vantage)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->alpha_vantage)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->alpha_vantage)
Installing collected packages: alpha-vantage
  Running setup.py install for alpha-vantage ... done
Successfully installed alpha-vantage-2.0.0
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

>  python3
Python 3.6.5 (default, Apr  4 2018, 15:01:18) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import alpha_vantage
>>> exit()

>  python3 alpha_vantage.py
Traceback (most recent call last):
  File "alpha_vantage.py", line 1, in <module>
    from alpha_vantage.timeseries import TimeSeries
  File "alpha_vantage.py", line 1, in <module>
    from alpha_vantage.timeseries import TimeSeries
ModuleNotFoundError: No module named 'alpha_vantage.timeseries'; 'alpha_vantage' is not a package

```

**Comment by addisonlynch** [comment]
Can you please share the contents of the ``alpha_vantage.py`` file?

**Comment by tmdag** [comment]
sure, it was just an example from github:
```

from alpha_vantage.timeseries import TimeSeries
import matplotlib.pyplot as plt

ts = TimeSeries(key='my_api_key', output_format='pandas')
data, meta_data = ts.get_intraday(symbol='MSFT',interval='1min', outputsize='full')
data['4. close'].plot()
plt.title('Intraday Times Series for the MSFT stock (1 min)')
plt.show()
```

**Comment by RomelTorres** [comment]
Could you change the name to sth else?  see if it works that way?

**Comment by RomelTorres** [comment]
Hi @tmdag. Is this still an issue?

**Comment by tmdag** [comment]
Hi @RomelTorres 
Sorry for late reply. I've changed file name as suggested, but I am still getting that error:

```
 >  python3
Python 3.6.5 (default, Apr  4 2018, 15:01:18) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import alpha_vantage
>>> 
>>> exit()

>  python vantageTest.py 
Traceback (most recent call last):
  File "pistockcharts/vantageTest.py", line 1, in <module>
    from alpha_vantage.timeseries import TimeSeries
  File "/home/ats/Develop/Standalone/python/piStockChart/pistockcharts/alpha_vantage.py", line 1, in <module>
    from alpha_vantage.timeseries import TimeSeries
ModuleNotFoundError: No module named 'alpha_vantage.timeseries'; 'alpha_vantage' is not a package
>
```

**Comment by tmdag** [comment]
Hi!
Sorry for late reply. It was definitely stupid issue with file name matching module name. Changing it fixed it! Thank you for pointing that out. Unfortunately now I am getting to yet another problem. Looks different on python 2 and python3 (it's same example file, again fails on import):


>  python vantageTest.py
Traceback (most recent call last):
  File "vantageTest.py", line 1, in <module>
    from alpha_vantage.timeseries import TimeSeries
  File "alpha_vantage.py", line 1, in <module>
ImportError: No module named timeseries

>  python3 vantageTest.py
Traceback (most recent call last):
  File "vantageTest.py", line 1, in <module>
    from alpha_vantage.timeseries import TimeSeries
ImportError: bad magic number in 'alpha_vantage': b'\x03\xf3\r\n'

**Comment by tmdag** [comment]
Hi, @RomelTorres 

No issue anymore! :)

That was a definately stupid mistake from me by naming file same as module. Even After I removed it, I still had some problems as I did not noticed leftover .pyc file. All good now, works as expected!
Thank you!

**Comment by RomelTorres** [comment]
He tdag, not an issue at all. I would recommend you using some sort of virtual environment (I usually use anaconda, but virtualenv is also good) It is always a good way to keep your dependencies well managed.

Saludos
Romel

**Comment by MarissaHeloise** [comment]
![image](https://user-images.githubusercontent.com/34094725/52367966-96a8bd00-2a4d-11e9-9b54-8c40f46e7235.png)
Sorry, I have the same problem. I don't understand why. I use anaconda and I installed the alpha_vantage library in base env and it works in terminal. Then I try to run the same example code in spyder... It reported Module not found errors. What do you mean by changing the name to something else?

**Comment by RomelTorres** [comment]
Don't name it alpha_vantage.py name it something else ;)

**Comment by npanwar01** [comment]
Hi RomelTorres, using python 3.7 in windows and install the alpha_vantage using pip but whenever I am executing a program in which I am using the alpha_vantage it is giving me an error below:- 
ModuleNotFoundError: No module named 'alpha_vantage'

could you please help me with the solution.

Thanks!!!

**Comment by jirka1297** [comment]
Hi, I have same problem, Can you help me?

using this python `Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> `


`from alpha_vantage.timeseries import TimesSeries
import matplotlib.pyplot as plt

ts = TimeSeries(key='api key', output_format='pandas')
data, meta_data = ts.get_intraday(symbol='MSFT',interval='1min', outputsize='full')
data['4. close'].plot()
plt.title('Intraday Times Series for the MSFT stock (1 min)')
plt.show()`

`Traceback (most recent call last):
  File "/Users/jirirambousek/OneDrive/Documents/Akcie/stock_analysis.py", line 1, in <module>
    from alpha_vantage.timeseries import TimesSeries
ModuleNotFoundError: No module named 'alpha_vantage'`

**Comment by frankiebbb** [comment]
Hi everybody,

Did you solve this problem?

Every time I execute this in Spyder/Anaconda I obtain:

from alpha_vantage.timeseries import TimeSeries
Traceback (most recent call last):

  File "<ipython-input-9-0ea1d588e6b8>", line 1, in <module>
    from alpha_vantage.timeseries import TimeSeries

ModuleNotFoundError: No module named 'alpha_vantage.timeseries'

but when I execute import alpha_vantage, it works.

Thank you in advance!
Frank

**Comment by PatrickAlphaVantage** [comment]
@jirka1297, could you run the command `which python` this will tell you where you have python installed. It might be different from where you are running your script.

@frankiebbb, there is a good chance your python is installed in a different place your anaconda is. If you are using anaconda's python, it'll be installed at something like `/Users/frank/anaconda3/bin/python`, in which case, you can run `/Users/frank/anaconda3/bin/python -m pip install alpha_vantage`

**Comment by frankiebbb** [comment]
Thank you for your reply @PatrickAlphaVantage, when I execute which python I get:
/home/frank/anaconda3/bin/python

And after executing /home/frank/anaconda3/bin/python3 -m pip install alpha_vantage
Requirement already satisfied: alpha_vantage in /home/frank/anaconda3/lib/python3.7/site-packages (2.2.0)
Requirement already satisfied: requests in /home/frank/anaconda3/lib/python3.7/site-packages (from alpha_vantage) (2.23.0)
Requirement already satisfied: aiohttp in /home/frank/anaconda3/lib/python3.7/site-packages (from alpha_vantage) (3.6.2)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/frank/anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/frank/anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/frank/anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (2020.4.5.1)
Requirement already satisfied: idna<3,>=2.5 in /home/frank/anaconda3/lib/python3.7/site-packages (from requests->alpha_vantage) (2.9)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/frank/anaconda3/lib/python3.7/site-packages (from aiohttp->alpha_vantage) (1.4.2)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /home/frank/anaconda3/lib/python3.7/site-packages (from aiohttp->alpha_vantage) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in /home/frank/anaconda3/lib/python3.7/site-packages (from aiohttp->alpha_vantage) (19.3.0)
Requirement already satisfied: multidict<5.0,>=4.5 in /home/frank/anaconda3/lib/python3.7/site-packages (from aiohttp->alpha_vantage) (4.7.6)

It seems that everthing is in place, but I don't get why is not working. I had a similar problem with yahoofinancials, but eventually it worked.

**Comment by PatrickAlphaVantage** [comment]
https://stackoverflow.com/questions/39449725/python-modul-not-found-after-anaconda-installation

In a python shell, can you run:
```
import sys
sys.executable
```

**Comment by frankiebbb** [comment]
After all I did, what it really worked is restarting the kernel in Spyder!

**Comment by PatrickAlphaVantage** [comment]
Haha, the ol' "turn it off and back on again" trick. I love it!

**Comment by frankiebbb** [comment]
It is always like that, we forget the most obvious things, thanks for your help!

**Comment by codephilip** [comment]
Does someone have a use example for fundamental data?

**Comment by jouellnyc** [comment]
stumbled upon this -- /home/blah/anaconda3/bin/pip3 install alpha_vantage -- worked for me

OS / pip install did not - but I don't care -- I wanted it under spyder/conda anyway
