### ISSUE TITLE
No module named 'alpha_vantage' (Anaconda / jupyter)

### ISSUE THREAD

**Issue by M1nda** [RomelTorres/alpha_vantage#65]
Hi,

After several hours of googling and scratching my head, I was unable to find the problem as to why jupyter is not able to import alpha_vantage module and throws an error:

First I installed alpha_vantage:

C:\Users\minda>pip install alpha_vantage
Collecting alpha_vantage
  Using cached https://files.pythonhosted.org/packages/90/62/c48ff7e3c7b6d7d6b50aefa48166abc3617fa724dba4bb51dab27c6288e4/alpha_vantage-2.0.0.tar.gz
Requirement already satisfied: requests in c:\users\minda\appdata\local\programs\python\python36-32\lib\site-packages (from alpha_vantage) (2.18.4)
Requirement already satisfied: simplejson in c:\users\minda\appdata\local\programs\python\python36-32\lib\site-packages (from alpha_vantage) (3.14.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\minda\appdata\local\programs\python\python36-32\lib\site-packages (from requests->alpha_vantage) (2018.1.18)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\minda\appdata\local\programs\python\python36-32\lib\site-packages (from requests->alpha_vantage) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\minda\appdata\local\programs\python\python36-32\lib\site-packages (from requests->alpha_vantage) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\minda\appdata\local\programs\python\python36-32\lib\site-packages (from requests->alpha_vantage) (2.6)
Installing collected packages: alpha-vantage
  Running setup.py install for alpha-vantage ... done
Successfully installed alpha-vantage-2.0.0

Then tried to test with the following:

import alpha_vantage
from alpha_vantage.timeseries import TimeSeries
from pprint import pprint

ts = TimeSeries(key='YOUR_API_KEY', output_format='pandas')
data, meta_data = ts.get_intraday(symbol='MSFT',interval='1min', outputsize='full')
pprint(data.head(2))

It returned error:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-8b9e68a2f4d2> in <module>()
----> 1 import alpha_vantage
      2 from alpha_vantage.timeseries import TimeSeries
      3 from pprint import pprint
      4 
      5 ts = TimeSeries(key='YOUR_API_KEY', output_format='pandas')

ModuleNotFoundError: No module named 'alpha_vantage'

I have gone through libraries, checked all names and couldn't find any obvious issues as to why it is not working.. Any suggestion / idea would be highly appreciated.

Thanks

**Comment by RomelTorres** [comment]
Hi @M1nda, what python version are you using for installing alpha_vantage? And what python version is your jupyter notebook kernel using? Btw a virtual environment is always a really good idea for developing in python (I use anaconda). I have a second repo with a jupyter notebook with examples and that ran well.

**Comment by M1nda** [comment]
Hi Romel, I am using 3.6.4.

**Comment by RomelTorres** [comment]
Hi, and your jupyter kernel is also set to python 3? Have you tried the import from a python console?

**Comment by M1nda** [comment]
Hi Romel, after some more digging, I set up new env with py3.5, re-installed alpha_vantage and it worked! Perhaps I should have done that earlier. Many thanks for getting back to me and have a great day!
