### ISSUE TITLE
API is not working

### ISSUE THREAD

**Issue by debashisgithub** [RomelTorres/alpha_vantage#66]
Hello Romel,
It seems like the site is down, API is responding with 503 Service Unavailable
{
    "err": {
        "name": "RequestError",
        "message": "Error: socket hang up",
        "cause": {
            "code": "ECONNRESET"
        },
        "error": {
            "code": "ECONNRESET"
        },
        "options": {
            "resolveWithFullResponse": true,
            "simple": false,
            "uri": "https://www.alphavantage.co/query?apikey=...&symbol=AWK&interval=1min&outputsize=full&datatype=json&function=TIME_SERIES_INTRADAY",
            "method": "GET",
            "transform2xxOnly": false
        }
    }
}

**Comment by bbuchanan** [comment]
https://www.alpha-vantage.community/post/why-is-alphavantage-inaccessible-so-frequently-9727187?pid=1304066574

Looks like it's been down for hours at this point and no one is telling anyone why. That's discouraging.
