### ISSUE TITLE
API Returns wrong data sometimes

### ISSUE THREAD

**Issue by RiyasPrecise** [RomelTorres/alpha_vantage#67]
When i try to fetch today's data from the api, it returns different date data for each request instead of today data just like below response.

example:
---------
https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=BSE:TCS&apikey=XXXXXXXXXXXXX

**Same time responses**
**Response 1** : `"Time Series (Daily)": {
        "2018-04-30": {
            "1. open": "3455.0000",
            "2. high": "3547.0000",
            "3. low": "3438.2000",
            "4. close": "3531.3999",
            "5. volume": "92393"
        },
        "2018-04-27": {
            "1. open": "3540.0000",
            "2. high": "3543.1499",
            "3. low": "3449.3000",
            "4. close": "3454.8000",
            "5. volume": "107456"
        },
        "2018-04-26": {
            "1. open": "3471.0000",
            "2. high": "3560.0000",
            "3. low": "3469.0000",
            "4. close": "3540.3501",
            "5. volume": "150998"
        },
}`

**Response 2** : `"Time Series (Daily)": {
        "2018-05-02": {
            "1. open": "3533.0000",
            "2. high": "3560.0000",
            "3. low": "3475.6001",
            "4. close": "3491.7000",
            "5. volume": "28210"
        },
        "2018-04-30": {
            "1. open": "3455.0000",
            "2. high": "3547.0000",
            "3. low": "3438.2000",
            "4. close": "3531.3999",
            "5. volume": "92393"
        },
        "2018-04-27": {
            "1. open": "3540.0000",
            "2. high": "3543.1499",
            "3. low": "3449.3000",
            "4. close": "3454.8000",
            "5. volume": "107456"
        },
}`

**Comment by dul3l3s** [comment]
I have been experiencing a similar problem. I have candlesticks being built with the data. I have noticed during the open or high volume periods data is changing, specifically open/close. Candlesticks even change color because the data is inaccurate.  I am pulling 15 min data from Alphavantage and have an app updating every minute being displayed using Plotly and Dash. 

Why is there data discrepancy?
