### ISSUE TITLE
API failure multiple times

### ISSUE THREAD

**Issue by debashisgithub** [RomelTorres/alpha_vantage#68]
Hello Romel,
API failure multiple time with response code 503
response: 
{
    "statusCode": 503,
    "body": "<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\t\t<meta charset=\"utf-8\">\n\t\t<title>Application Error</title>\n\t\t<style media=\"screen\">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src=\"//www.herokucdn.com/error-pages/application-error.html\"></iframe>\n\t  </body>\n\t</html>",
    "headers": {
        "connection": "close",
        "server": "Cowboy",
        "date": "Wed, 02 May 2018 09:18:23 GMT",
        "content-length": "506",
        "content-type": "text/html; charset=utf-8",
        "cache-control": "no-cache, no-store"
    },
    "request": {
        "uri": {
            "protocol": "https:",
            "slashes": true,
            "auth": null,
            "host": "www.alphavantage.co",
            "port": 443,
            "hostname": "www.alphavantage.co",
            "hash": null,
            "search": "?function=TIME_SERIES_INTRADAY&symbol=AWK&interval=1min&outputsize=full&apikey=XXXXXXXXXXXXXX",
            "query": "function=TIME_SERIES_INTRADAY&symbol=AWK&interval=1min&outputsize=full&apikey=XXXXXXXXXXXXXX",
            "pathname": "/query",
            "path": "/query?function=TIME_SERIES_INTRADAY&symbol=AWK&interval=1min&outputsize=full&apikey=XXXXXXXXXXXXXX",
            "href": "https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=AWK&interval=1min&outputsize=full&apikey=XXXXXXXXXXXXXX"
        },
        "method": "GET",
        "headers": {}
    }
}

Also sometimes it's returning response status 200 but response data like below
{
    "statusCode": 200,
    "body": "{\n    \"Error Message\": \"Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_INTRADAY.\"\n}",
    "headers": {
        "connection": "close",
        "server": "gunicorn/19.7.0",
        "date": "Wed, 02 May 2018 09:21:23 GMT",
        "transfer-encoding": "chunked",
        "allow": "GET, HEAD, OPTIONS",
        "content-type": "application/json",
        "x-frame-options": "SAMEORIGIN",
        "vary": "Cookie",
        "via": "1.1 vegur"
    },
    "request": {
        "uri": {
            "protocol": "https:",
            "slashes": true,
            "auth": null,
            "host": "www.alphavantage.co",
            "port": 443,
            "hostname": "www.alphavantage.co",
            "hash": null,
            "search": "?function=TIME_SERIES_INTRADAY&symbol=AWK&interval=1min&outputsize=full&apikey=XXXXXXXXXXXXXXXXXX",
            "query": "function=TIME_SERIES_INTRADAY&symbol=AWK&interval=1min&outputsize=full&apikey=XXXXXXXXXXXXXXXXXX",
            "pathname": "/query",
            "path": "/query?function=TIME_SERIES_INTRADAY&symbol=AWK&interval=1min&outputsize=full&apikey=XXXXXXXXXXXXXXXXXX",
            "href": "https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=AWK&interval=1min&outputsize=full&apikey=XXXXXXXXXXXXXXXXXX"
        },
        "method": "GET",
        "headers": {}
    }
}

**Comment by rtruxal** [comment]
Hi Guys - Status 503 is an internal server error, often brought about when a server is overloaded, and that's its way of telling you it can't handle your request right now. This is the most likely case, especially if the API works just fine for you in other places. **If** this is the problem, putting a `time.sleep()` in ther might help. Here's how I'd try:
```python
MAX_RETRY_PER_SYMBOL = 3
for symbol in list_of_symbols:

    # Gets M1 data for around 14 days
    try:
        m1_data = ava_api.get_data(
            endpoint='TIME_SERIES_INTRADAY&symbol=' + symbol + '&interval=1min&outputsize=full&apikey=' + ava_api.get_api_key())
    except:
        for retry_cnt in list(range(MAX_RETRY_PER_SYMBOL)):
            try:
                m1_data.get_data(endpoint='TIME_SERIES_INTRADAY&symbol=' + symbol + '&interval=1min&outputsize=full&apikey=' + ava_api.get_api_key())
                break
            except:
                print("Failed to get M1 data (%s) on try # %s" % symbol, retry_cnt)
                continue
        continue

    if m1_data is None:
        continue

    if 'Time Series (1min)' not in m1_data:
        print("No m1 data in time series from AvaAPI for (%s). Continue with next symbol." % symbol)
        continue
```

Another possibility is that one of alphavantage's web-servers is under maintenance, and they just forgot to tell the load-balancer. Either way, a `50x` status code is s webserver's way of telling you it's messed up, not you.
