### ISSUE TITLE
apikey is sent in the url and not in a header.. is this secure?

### ISSUE THREAD

**Issue by lippirk** [RomelTorres/alpha_vantage#69]
``` 
if self._append_type:
                url = '{}&apikey={}&datatype={}'.format(url, self.key, oformat)
            else:
                url = '{}&apikey={}'.format(url, self.key)
            return self._handle_api_call(url), data_key, meta_data_key
```

in `alphavantage.py`

**Comment by RomelTorres** [comment]
Hi lippirk, 
probably not... Do you have any recommendations on how to send it on the header? If you want send a pull request with the changes.

All the best
Romel

**Comment by lippirk** [comment]
i've made the following post on the alpha vantage forum: 
https://www.alpha-vantage.community/post/can-i-put-my-api-key-in-a-header-rather-than-as-a-query-parameter-9733135?pid=1304138294#post1304138294

we'll see what they say.

i'm happy to do this once we get an answer back :)

**Comment by RomelTorres** [comment]
Hi @lippirk , did you get an answer back?

Best Regards
Romel

**Comment by lippirk** [comment]
hi! i didn't get a proper answer unfortunately, i think we're going to have to leave it as is. i looked at the js wrapper for this api and they put the api key in the url also
