### ISSUE TITLE
Daily data missing.

### ISSUE THREAD

**Issue by mnoorali** [RomelTorres/alpha_vantage#74]
My scripts started to fail today due to missing data from previous business day.

Technical Analysis: MACD": {
        "**2018-05-23 12:08:22**": {
            "MACD_Hist": "0.2640",
            "MACD": "4.3336",
            "MACD_Signal": "4.0696"
        },
        "**2018-05-21**": {
            "MACD_Hist": "0.3581",
            "MACD": "4.3617",
            "MACD_Signal": "4.0036"

MACD data is missing for yesterday, 2018-05-22. I scanned thru full json data and don't find the data for this date. This data is missing for all technical indicators.

Is it common for data to be missing with Alpha Vantage?

Thanks!

**Comment by RomelTorres** [comment]
I actually don't know, did you get an answer in their forums?
