### ISSUE TITLE
How to get the fractional price?

### ISSUE THREAD

**Issue by johntechdev** [RomelTorres/alpha_vantage#75]
Someone knows how get the price to non-default batch (fractional share, fractional stock)? For examples, PETR4F, VALE3F, I don't know if exists thing like AAPLF

**Comment by jackmoody11** [comment]
@johntechdev For something like AAPL, you can just divide the current price by whatever fraction you have of the stock. It might result in a rounding error, but I'm not sure that Alpha Vantage offers prices for fractional share prices.
