### ISSUE TITLE
Question: ForeignExchange Daily

### ISSUE THREAD

**Issue by Dave-Vallance** [RomelTorres/alpha_vantage#82]
Do you have plans to support the daily, weekly and monthly ForeignExchange calls? 

I see Intraday was recently added 

Here is the link
https://www.alphavantage.co/documentation/#fx-daily

Or perhaps it is already available and I am being a dumbo?

Curiously I am able to get daily data throught `TimeSeries` but this is all returned with the same values for open, high, low and close (so I assume it is returning close data only). 

Any pointers or comments would be highly appreciated. 

Many thanks!

**Comment by tuxskar** [comment]
Hi, I was the one doing the pull request to support the intraday on ForeignExchange and I plan to create more pull requests for the missing support soon.

**Comment by Dave-Vallance** [comment]
Hi @tuxskar 
 
Thanks for letting me know and I appreciate you helping the community. 

Roughly (without sounding pushy), when do you expect to take a look at this? I understand completely that you will work to your own timescale. I am just trying to decide if I should wait or look for an interim solution via another API like Oanda. 

Many thanks again.

**Comment by tuxskar** [comment]
Hi @Dave-Vallance my plan is to work on it on this week and at least have the daily between today and tomorrow (CEST)

**Comment by Dave-Vallance** [comment]
@tuxskar Thank you very much for the information! 

Closing the question.
