### ISSUE TITLE
How to get intraday data of Forex ?

### ISSUE THREAD

**Issue by swishderzy** [RomelTorres/alpha_vantage#85]
How to extract data intra-daily (1min, 5min, 1h, ... ) of ForeignExchange ?

**Comment by tuxskar** [comment]
Hi @swishderzy,

This is an example on how you could get intraday data of the forex pair 'EUR/USD' with 15 minutes period using the object ForeignExchange and the function get_currency_exchange_intraday

```
from alpha_vantage.foreignexchange import ForeignExchange
import matplotlib.pyplot as plt

fx = ForeignExchange(key=ALPHAVANTAGE_API_KEY, output_format='pandas')
data, meta_data = fx.get_currency_exchange_intraday('EUR', 'USD', '5min', 'full')
data['4. close'].plot()
plt.title(f'Intraday Times Series for the {from_currency}-{to_currency} stock (15 min)')
plt.show()
```
And as return you should get something like this:
![image](https://user-images.githubusercontent.com/576885/46098666-36635e00-c1c5-11e8-821f-44a510c473cc.png)

**Comment by swishderzy** [comment]
Thank you for the response but i get an error:
AttributeError: 'ForeignExchange' object has no attribute 'get_currency_exchange_intraday'

**Comment by tuxskar** [comment]
Sorry, I didn't mention this on my previous comment.

This new code is on the public package on the version 2.1.0, you can install it using:
```
# pip install -U alpha-vantage==2.1.0
```

Or if you are using the source code you need to checkout to the `develop` branch
```
# git checkout develop
```

**Comment by swishderzy** [comment]
Worked perfectly
Thank you very much

**Comment by adgomiza** [comment]
hi Romel, How to extract data intra-daily (1min, 5min, 1h, ... ) in Javascript?
please, the full code. if you can.
thank you.

**Comment by RomelTorres** [comment]
Hi, I am sorry I don't do JavaScript.

**Comment by adgomiza** [comment]
> 
> 
> Hi, I am sorry I don't do JavaScript.

thank you Romel .

**Comment by ahita** [comment]
Hi, 

How long is the full series?


Thanks in advance

**Comment by hayyyyyyden** [comment]
Hi, I got the same error of  `ForeignExchange' object has no attribute 'get_currency_exchange_intraday`

in the latest version of `2.1.3`.

It's weird, the function is there, I checked on my pip, however, I just can not call it. Only `get_currency_exchange_rate` worked on that class.

![image](https://user-images.githubusercontent.com/6135847/79290596-e1ef1300-7f0f-11ea-94d0-b6000762a84e.png)
