### ISSUE TITLE
'TimeSeries' object has no attribute 'get_quote_endpoint'

### ISSUE THREAD

**Issue by aspenforest** [RomelTorres/alpha_vantage#90]
>>> from alpha_vantage.timeseries import TimeSeries
>>> ts = TimeSeries(key='xxxxxxxxxxxxxxxxxxx')
>>> data, meta_data = ts.get_quote_endpoint('ACB')
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    data, meta_data = ts.get_quote_endpoint('ACB')
AttributeError: 'TimeSeries' object has no attribute 'get_quote_endpoint'

**Comment by RomelTorres** [comment]
It is not implemented yet :( I am kind of busy at the moment, I might be free over the weekend to implement it, but I am not sure! If anyone wants to do it before me, be my guest. It is actually quite simple.  

:D

**Comment by sanderbrauwers** [comment]
Yes, please. I need this endpoint https://www.alphavantage.co/documentation/#latestprice

**Comment by umutsoysal** [comment]
I am getting "AttributeError: 'TimeSeries' object has no attribute 'get_intraday_extended'" error on python 3.7.4 for this line "ts.get_intraday_extended(symbol="FB", interval='15min', slice=f'year1month5')" same line works for Python 3.8.X
