### ISSUE TITLE
Inspect deprecation warning

### ISSUE THREAD

**Issue by ilcardella** [RomelTorres/alpha_vantage#94]
Hi, first thanks to all the contributors for the great job done so far!
I am opening this issue because I am using alpha_vantage in my trading script and when I run my unit test (pytest) I get this warning:
```
/home/alberto/.local/lib/python3.6/site-packages/alpha_vantage/alphavantage.py:93: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
    argspec = inspect.getargspec(func)
```

I have resolved this locally by just replacing `getargspec` with `getfullargspec`.
Should I open a PR for this?

**Comment by RomelTorres** [comment]
Oh thanks, yeah it is a good idea. Do the PR and I'll merge it. :)

**Comment by RomelTorres** [comment]
Merged ;)
